### ISSUE TITLE
Elder Guardian not recognized as separate mob.

### ISSUE THREAD

**Issue by CyaNox** [Ipsis/Woot#101]
When poking a Elder Guardian with a mob prism it always says Woot:none:Guardian and when placed in a factory only produces the normal Guardian drops.

I'd love to be able to farm them sponges from the Elder Guardians too ;)

**Comment by Ipsis** [comment]
Didn't even know the Elder Guardian existed!
From the code it should be trivial to add support to identify it correctly.

**Comment by Ipsis** [comment]
Code added.
Elder Guardians are now generating (with looting III)
Prismarine Shards
Fish (!)
Sponge
Prismarine Crytstals

**Comment by CyaNox** [comment]
Awesome thanks a bunch ;)
