### ISSUE TITLE
Blood Magic integration should output the life essence into the altar directly

### ISSUE THREAD

**Issue by CyaNox** [Ipsis/Woot#105]
Currently you need to pipe the blood around using tanks, pipes or other means of liquid transport even though both Woot and Blood Magic do not provide any of these capabilities therefore the life essence should be put directly into the blood altar akin to the Ritual: Well of Suffering.

Further arguments to favor this change is that the Woot spawner produces Life Essence at a rate much faster than the blood altar will actually accept especially when you can't produce the "Acceleration Rune" (Tier V) yet.

**Comment by Ipsis** [comment]
I can see where you are coming from here.
I play so much with big mod packs, that I have never had the situation where liquid transport was not an option.

I'm considering doing the following:

* if the ritual detects an altar in a specific range, then it will act the same way as the Well Of Suffering, including how it calculates the Life Essence to put into the altar
* if the ritual does NOT detect an alter in a specific range, then it will output to the tanks as is

That at least gives a pack with no tanks, pipes or liquid transport a viable option.
If of course I can get the code to do this - which I think I can

**Comment by CyaNox** [comment]
I think the bigger issue is the rate at which the Blood altar can accept life essence in the two different ways.

Blood magic deliberately limits the input and output rate of Life essence in liquid form in the blood altar. By default the input rate (without runes that modify this) is 20mB per second. This is so slow that it does not even compare to manually filling the blood altar using the sacrificial dagger and purely relying on vanilla healing.

Furthermore the best way to increase the input rate of life essence into the blood altar using pipes/tanks is the Acceleration Rune. This rune is Tier V. i.e. near end game. Even so the fastest this rune can make (maximum of 19 of these runes anymore has no effect) it is 400mB per second without the use of Displacement Runes.

Now I believe there is no limit on displacement runes beyond the actual limit of the altar itself which makes the maximum possible transfer rate:

184 Total rune places (Tier VI)
* 19 Acceleration Rune (Making each input and output operation activate every single tick).
* 165 Displacement Runes adding an additional 330mB per operation to the original 20mB (20% per rune)

Making it a total of (20mB + 330mB * 20 ticks) = 7000mB per second.

Now nobody in their right mind would actually use this maxed out setup to get this transfer rate because it makes the altar itself quite useless since there are no "Useful" runes.

Knowing these numbers I would not use Woot in its current state to fill my blood altar but rather a conventional (and thus laggy) mob killing farm and thus this defeats the purpose of having Woot.

As both a player and server maintainer (pack author) I'd rather have a more useful Woot in combination with Blood Magic and thus have it transfer (or a config option to enable this) directly into the Blood altar by default.

**Comment by Ipsis** [comment]
Thanks for the numbers information. My knowledge of BM is limited so that helped a lot as to why this is a good idea. So yes, I will be looking at implementing direct Altar filling. I'm hoping it won't be too tricky synching up the ritual code with factory code :)

**Comment by RealGrep** [comment]
Came here specifically due to this issue after setting up a ritual for this. Yeah, I have to agree very strongly. I'm glad you're looking into this and can't wait to have it output directly to the altar. It is sorely needed. At the moment, it's so terrible, I would just end up doing it the old way, with a bunch of witches, a traditional spawner, or cursed earth. If it worked like the Ritual of Suffering (and why not), I would definitely use this and be quite happy with it.

Seeing this, though, I'll obviously just wait on it. Thanks for being awesome! :)

**Comment by Ipsis** [comment]
Next release will be targeting Blood Magic and will have this added. I wanted to get some others things out of the way first. On reflection I should have made it work this way to begin with, but I thought it would be OP. Shows you how much I know about Blood Magic :)

**Comment by Ipsis** [comment]
A quick update. This is still in development. Adding to the altar is "easy". Getting the factory and the altar to sync up is ...... not quite so easy.

**Comment by Ipsis** [comment]
42ebc3247718307610e57b3d86ae27943d245134

**Comment by Ipsis** [comment]
After some testing this seems to be working.
With a Tier III factory, Tier III mass upgrades, Tier III rate upgrade and the Tier III Blood Magic upgrades it becomes ... quite powerful, even more so when you throw some Sacrifice runes into your Altar!

So the way it works is as follows:

Ritual has the same range to the factory and the altar that the Well Of Suffering does.

If the factory finds a tank beside it, then Life Essence will be placed into the tank and the altar ignored.
In this setup:
Blood Magic TI Upgrade - 10 sacrifice runes applied to each mob
Blood Magic TII Upgrade - 20 sacrifice runes applied to each mob
Blood Magic TIII Upgrade - 30 sacrifice runes applied to each mob
User is responsible for getting the Life Essence somewhere useful

If there is no adjacent tanks then the ritual will directly fill the altar.
In this setup:
Blood Magic TI Upgrade - Each mob is worth 20 Life Essence,
Blood Magic TII Upgrade - Each mob is worth 30 Life Essence,
Blood Magic TIII Upgrade - Each mob is worth 40 Life Essence,
These are the base values given to the Altar for each mob BEFORE the Altar applies its rune configuration to the kill as well.

Remember that if there is no adjacent inventory to the factory then the factory still runs, you just don't get the loot. The Life Essence will still be generated though.

I'll release this update in the next couple of days.
I'm sure you will let me know if there are any tweaks needed :)

**Comment by RealGrep** [comment]
That seems pretty good. I'll know more once I take it for a spin, of course. Will be nice to reduce the attraction of keeping 50 witches under your altar, that's for sure. And yes, I've seen that. lol

Of course, as usual, being able to tweak the values in the config would be a nice touch, as well.

Can't wait to try it out! :D

**Comment by Ipsis** [comment]
Guess who forgot to add config options ;)
I will add that before release to allow access to the upgrade values for both tanks and altar.

**Comment by Ipsis** [comment]
Config added
c8c894d6f03a9d7de4c9f3285d3fdd358384d401
