### ISSUE TITLE
Blood Magic integration should be more lenient

### ISSUE THREAD

**Issue by CyaNox** [Ipsis/Woot#106]
Blood Magic rituals that need to be "near" the Blood altar have a decent range in which you can place it. 

For the Well of Suffering this range is in a 10 x 20 x 10 area.

Since both this ritual and woot serve a similar purpose I'd propose a similar leniency on the placement of the Woot spawner.

**Comment by Ipsis** [comment]
Does this mean that the ritual is NOT working if it is not close enough to the Altar?
I had not added anything in the code that would make that link be required, well I thought that I hadn't.

**Comment by CyaNox** [comment]
We haven't experimented with the distance from the blood altar from the viewpoint of the Ritual of the Infernal Machine (Though to test this properly #105 should probably be looked at first). 

What we are talking about is the distance (or relative position) from the Woot spawner in comparison to the Ritual of the Infernal Machine.

**Comment by Ipsis** [comment]
Right, I understand now.

I have it set for a fixed distance of 6 blocks below. The reason for the fixed distance is that it fits on top of the Tier IV factory.

**Comment by CyaNox** [comment]
We'd love to see that fixed distance more lenient similar to the Well of Sufferings area.

**Comment by Ipsis** [comment]
The ritual fits into the factory structure, so I'm not sure how allowing the separation of the factory and ritual helps. I'm just not understanding what benefit it brings.

**Comment by CyaNox** [comment]
I'd say the benefit is cosmetic and makes it more user friendly.

We like to make our stuff look good and having more freedom in the placement of these larger structures allows us to be more free in our designs.

Furthermore one of our players had some major head scratching when it did not work (she had it placed one too far down yet perfectly aligned). Allowing similar freedoms as the rest of Blood Magic provides makes these kind of mistakes almost never happen.

**Comment by Ipsis** [comment]
I'll see about making this a bit more flexible after I've got #105 working.

**Comment by Ipsis** [comment]
Ritual range updated to match the Well Of Suffering
