### ISSUE TITLE
Woot manual - use Guide-API

### ISSUE THREAD

**Issue by CyaNox** [Ipsis/Woot#107]
When closing the woot manual it always resets to the first page. This gets really annoying when the information you need (i.e. the Tier IV block requirements) is nearly at the end of the book.

In addition to remembering the page you were on the first page should have a functional Table Of Contents this way the "Home" button actually becomes useful.

**Comment by Ipsis** [comment]
The manual needs a LOT of work. These are two features that I want to add soon.

**Comment by Ipsis** [comment]
For speed, just port the current text to the Guide-API based book.
I can redo the full book in 1.11.2.

**Comment by Ipsis** [comment]
Actually did this for 1.12!
Wonders will never cease
