### ISSUE TITLE
Woot 1.1.0 unable to get mob heads to drop

### ISSUE THREAD

**Issue by topher2010** [Ipsis/Woot#108]
We are unable to get mobheads to drop in order to start using the mod.  Not sure if the mod makes it's own chances of head drops, or if it uses vanilla.  Any pointers on how to get mob heads to start using Woot?

**Comment by Ipsis** [comment]
Something that I had not actually considered. I always play with other mods that help with this. Vanilla relies on wither skeletons being the easiest way.

**Comment by demethan** [comment]
My two cents,

A decapitate enchant would be fine if Ender IO is not detected or something like that. 

*Co-pack Dev BreakfastSpecial with Topher.

**Comment by Ipsis** [comment]
I like the idea of an enchant.
I'm not sure if Ender IO adds an enchant or not, or if it only works with the Ender IO sword.
I'll see about adding something in that will allow you to get Creeper, Zombie and Skeleton heads.

**Comment by Ipsis** [comment]
Adding a "Decapitate" enchant.
This will be a rare enchant that will give a fixed percentage change of causing a head drop from vanilla mobs. It will only work on Creepers, Zombies and Skeletons.
Tragically, due to an error in manufacturing it wont work on Wither Skeletons 👿
