### ISSUE TITLE
LootBag drops dont get picked up

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#109]
LootBags drops its item in world, but with a different Y offset.

random.nextInt(2)+1) => origin.y + 1 -> origin.y + 2

The lootbox area is only Y = 0, 1, 2
Mob will be spawned at Y = 1
Loot bag could spawn at Y = 2 or 3.

So it is possible that the lootbags will spawn in a non-air block causing them to be accelerated upwards.

**Comment by ghost** [comment]
This is happening (happening again I suppose) in version 1.4.1 for Minecraft 1.10.2 (woot-1.10.2-1.4.1.jar)
..Huh. I cut the power for a second and now it is no longer raining loot bags.

..Yeah I can't reproduce this. Must have been a fluke. Thanks for the amazing mod, also happy new year!

**Comment by Ipsis** [comment]
It is possible that in a newer version of Loot bags they are being generated slightly higher. They then escape the spawn box. I've changed this workaround I'm 1.12 to hopefully stop this from ever happening again.
