### ISSUE TITLE
Mob tag is case sensive in costing from globalSpawnCostList and causes a mismatch

### ISSUE THREAD

**Issue by RealGrep** [Ipsis/Woot#110]
I am trying to rebalance the mob spawning costs, and this includes the wither skeleton. However, changing the value in the config in globalSpawnCostList for Woot:Wither:Skeleton seems to do nothing.

For example, I increased the spawn cost for it to 80, it costs 720RF/tick. I've got it set to 100. Still 720RF/tick. I do get this in the log: "[Woot/Woot]: Adding mob cost: Woot:Wither:Skeleton=100" but the RF/tick value seems to still not be changing.

So I poked around for a while in the code. The issue is that it is case sensitive. Or at least that the default values listed in the config have the wrong case. If I make the config entry "Woot:wither:Skeleton", then it works as expected. The "List of mobs and spawn costs" line above that list shows it as defaulting to "[Woot:Wither:Skeleton=10]".

Sure enough, "/woot mobs" shows it as "Woot:wither:Skeleton". Making it that in the config fixes the issue.

Might be best to take case entirely out of that equation, really. I suspect this also affects the default value. Wouldn't surprise me if this also affects the tier requirement setting for them.

As an aside, it is quite difficult to balance this to a pack, particularly the wither boss. The cost is obscenely small, particularly since it removes the requirement for wither skulls and soul sand. Doing what I can, but something I hope you'll consider. Might also be good to be able to remove tier IV entirely if desired. I could block wither bosses and any other boss, but that tier would remain.

Thanks a lot for a really interesting and nice mod! If I can get it balanced somewhat, this'll be a great addition.

**Comment by Ipsis** [comment]
I knew that mob naming system was going to haunt me :)

I hadn't even realised that the default Wither Skeleton value was wrong. It should be xp=10 and forced to be a tier III mob.
I'll probably go ahead with the case ignoring idea, which is what I should have done in the first place.

As for balance, it is a continuing problem. I don't want to have any fixed coding for any mobs, which means I've got to use xp levels and balance low and high xp mobs. Currently it is all balanced around EnderIO stirling generators all maxed out. I'm also looking at how much it costs with spawning systems from other mods.  

As new power gen arrives from mods this will make it too easy, so I'm always open to adding new config options to allow people to modify things. 

The only things different from Tier III to Tier IV is that ability to spawn  the highest tier mobs, which is everything with an XP of 50+. So if you blacklist the bosses then any player creating a Tier IV will be wasting their time as they could achieve the same with a Tier III.

One of my biggest aims with this mod, was to have it just work with mobs from new mods without having to add specific entries to config files. However all this does have it's drawbacks as you saw with power balance.

**Comment by Ipsis** [comment]
Hopefully I've not broken anything with this change. It all looks good from my testing.
It should also mean that Wither Skeletons now cost 10 xp and should be a Tier III mob .... maybe
