### ISSUE TITLE
Some modded enchanting books do not work in the recipes.

### ISSUE THREAD

**Issue by KitKat31337** [Ipsis/Woot#119]
Specifically, I think this has to do with enchanting plus.

**Comment by Ipsis** [comment]
I'll try putting that mod in my dev environment and see if I can work out what is going on.

**Comment by KitKat31337** [comment]
If you like, I can send you my curse manifest and even bring you on the server for testing.

**Comment by Ipsis** [comment]
The curse manifest would probably help, as it will make it easier to replicate and test the fix.

**Comment by KitKat31337** [comment]
https://puu.sh/sl4eD/8ab896dfb4.zip

**Comment by KitKat31337** [comment]
Message me on discord if you want to take a peek at the server.  KitKat31337#8080

**Comment by Ipsis** [comment]
So I've tried running your Curse project .... and run out of memory.
What memory line do you use to run your modpack?

**Comment by Ipsis** [comment]
Ignore that last comment, I just added the Enchanting Plus mod to my test mod instance and I can replicate the issue. Nothing seems different between the vanilla and E+ books in terms of metadata or NBT.
However the E+ books are working for a Blood Magic recipe, which I also have installed.

I'll dig a bit further and see if I'm added in the recipe in such a way that anything that is not a direct copy of a vanilla enchanted book will not work.

**Comment by Ipsis** [comment]
Found the different.
Vanilla: {StoredEnchantments:[0:{lvl:1s,id:48s}]
E+  {StoredEnchantments:[0:{lvl:1,id:48s}]

That lvl:1s to lvl:1 means that the recipe does not match.
I'll have to see if there is something I can do, since other mods seems to handle this ok.

**Comment by Ipsis** [comment]
After some more digging, I'm not alone in this.
The books from E+ are, as shown above, slightly different and may not work in other mods that require a specific enchanted book. As a general enchanted book in a recipe, they are fine. The problem occurs when a recipe wants a "Looting I" or a "Power V" book.

The Woot recipe works fine with an Ender IO enchanter based book, just not an E+ plus.

I'll keep looking, but I'm not seeing an easy fix in Woot for this.

**Comment by KitKat31337** [comment]
Yeah, Based on what you found, the only fix I could see is checking if E+ is installed and loading different recipes.  Or additional ones.

**Comment by KitKat31337** [comment]
Oh, and yeah, that pack crashes with less that 5GB Ram for some reason.  Evne though once launched sits around 2-3 used for me.

**Comment by Ipsis** [comment]
From what I can see, it wouldn't just be a different recipe, I would have to add a custom recipe handler that didn't just match NBT data, but allowed almost a fuzzy-match on the NBT.

So for now, I'm not sure if I'm going to add a workaround for the E+ books.
Once I've got 1.11 out the way, I'll come back and consider what to do about this.
