### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 4 woot-1.10.2-1.2.1

### ISSUE THREAD

**Issue by SDUBZ** [Ipsis/Woot#122]
one of my clients has had a crash thought you guys might wanna have a look into it 
crash report:
https://openeye.openmods.info/crashes/125cb6c2b6ff51382f55bde0ac13bbd5

another one triggered not long after 

https://openeye.openmods.info/crashes/17e29be2c5170e5aff1acf04eee851ac

**Comment by Ipsis** [comment]
Thankfully someone sent me a pull request a couple of days ago to fix exactly that problem. Well I think it is the same issue.
Sloppy coding on my part.

New release will hopefully be out this week with it fixed.

https://github.com/Ipsis/Woot/commit/345f0fdc6222a3ceb1d234fa86bbcd070feb6c7b

**Comment by Ipsis** [comment]
Fixed as part of https://github.com/Ipsis/Woot/commit/345f0fdc6222a3ceb1d234fa86bbcd070feb6c7b
