### ISSUE TITLE
[1.10.2] Crash on Client Start

### ISSUE THREAD

**Issue by YOYOK9** [Ipsis/Woot#125]
When loading up my modpack everything works fine till it gets to Woot, then it crashes. 

Woot: 1.10.2-1.2.2
Mc: 1.10.2
Forge: forge-1.10.2-12.18.3.2185

Crash Report:
http://pastebin.com/i3tde1SN

Notes: 
Have tried deleting Woot folder & Config, Still crashes

Edit: added oneprobe and it no longer crashes. Crashes if oneprobe is not in pack....

**Comment by Ipsis** [comment]
That is a bit strange since my TOP support is only supposed to start if TOP is present.
I'll try and get this fixed quickly and push a hotfix release.

**Comment by Ipsis** [comment]
I've introduced this with the 1.2.2 release and it is to do with showing the drop percentage chance in the TOP information. Not I just have to work out to disable it when TOP isn't present :(

**Comment by Ipsis** [comment]
https://github.com/Ipsis/Woot/commit/611e12a175662495e23dcfc2bc192c804501459b

**Comment by YOYOK9** [comment]
1.2.3 isnt crashing without TOP!! Thanks. Really love this mod best mod for modpacks with mob farming!
