### ISSUE TITLE
Hidden simple recipes for upgrades...

### ISSUE THREAD

**Issue by darkphan** [Ipsis/Woot#126]
There appears to be some hidden recipes that let you make the upgrades fairly cheaply compared to normal. See attached screenshot for some examples: http://i.imgur.com/B5wGEKv.png

**Comment by Ipsis** [comment]
Well that is ....... absolutely unintended.
How on earth did I manage that, as I cannot see them showing up in JEI.

I've replicated it and I can create a variety of different recipes.
Leaving the full recipe on the crafting table, I can remove 1 or 2 items and the output is still valid.
It all depends on which item.

This looks like it will be a fun one to fix!

**Comment by Ipsis** [comment]
Found the problem in my recipe subclass where I was accepting the full recipe, based on the enchanted book being correct!.

I think I've got a fix in place, but I'll do more testing first instead of rushing out half-a-fix, which I'm quite good at ;)

**Comment by darkphan** [comment]
haha, thats great!

**Comment by Ipsis** [comment]
fb55008c2aa90800387f779b524894d45d161f3e

**Comment by darkphan** [comment]
Is 1.2.4 coming out soonish? Holding off updating a modpack for this update :D

**Comment by Ipsis** [comment]
Apologies. I've been checking the issue lists regularly (including the closed ones!) and this one was never highlighted!

I'll push a release tomorrow when I get back from work.

**Comment by Ipsis** [comment]
I've pushed the new release to Curse.
Again apologies for missing your update.
