### ISSUE TITLE
Some mod drops either not dropping or all the same drop type for an item

### ISSUE THREAD

**Issue by DoomSquirter** [Ipsis/Woot#127]
woot-1.10.2-1.2.3
Reliquary-1.10.2-1.3.3.606
EverlastingAbilities-1.9.4-1.2.3
EnchantingPlus-1.10.2-4.1.0.115

so, Reliquary items aren't dropping at all (I saw previous closed issue, wasn't sure if this is a new issue or understood they won't drop (?) 

Everlasting Abilities drops a ability totem (fertility) but ONLY the fertility one, and at a pretty high drop rate...  

Enchanting plus is similar to above.  Drops only one enchanted scroll and it's always Infinity.

Assuming nbt or damage isn't being looked at for these items I guess?  

Also I have InfernalMobs-1.10 and not sure but think the special drops (armor, etc) aren't coming from there either.

**Comment by Ipsis** [comment]
This looks new as I had previously fixed the Reliquary drops. Granted that was a while ago.
I basically learn the exact loot dropped, so NBT and metadata should be handled.

I'll have a look at it with your rmod setup and see what is special about these mods and if I have broken something or need to extend the way that I learn.

**Comment by Ipsis** [comment]
I've now blacklisted "eplus:scroll" and "everlastingabilities:abilityTotem" until such time that I decide if I want to add special handling for NBT based drops. 

This will be in the next (1.2.4) release.

**Comment by Ipsis** [comment]
ae75ac94803efa7597e466c75c2f5c4b3518cdd5

**Comment by Ipsis** [comment]
For InfernalMobs, I think I have found the reason.
The mod modifies a mob, when it is spawned into the world via EntityJoinWorldEvent, however the way that I fake spawn mobs, does not allow that event to be raised.

Basically, I don't ever learn from InfernalMobs mobs.
However since I don't want to shortcut, combat based mods, it is not something that I would be adding support for.

**Comment by DoomSquirter** [comment]
totally understand about the infernal mobs.  just throwing it out there that it was the way it was.  

As far as nbt goes, maybe look at that as a tradeoff.  want a rf -> mob loot option?  maybe certain things don't get dropped, for those you need to make a real mob farm, etc.   

As far as reliquary, I wasn't getting any tho now that I think about it, doh, I was spawning zombies as a test thus probably why I wasn't seeing any.  Sorry about that.  I was doing that in a creative world and am playing survival now and about to make a woot farm, so you're probably right, they are dropping.  if not, I'll update issue.
