### ISSUE TITLE
similar to another closed ticket but would like some clarification - mod: cyberware

### ISSUE THREAD

**Issue by DoomSquirter** [Ipsis/Woot#129]
similar to #113 

config shows no blacklist/whitelist but can't prism a cyber zombie (so assuming this is code level blacklisted?)

says Mob Zombie cannot be captured (Woot:none:cyberware.cyberzombie)

getting only trench coat and glasses from a zombie farm.  

if I read #113 correctly, that will never change?  I only ask cause in that issue, it is mentioning blacklists/whitelists but I don't see anything in configs for that.

Also, in that issue, you mention that woot learns not only from it's kills but from manual kills in time.  how does it do that?

**Comment by Ipsis** [comment]
Cyberware mobs are internally blacklisted - felt it was completely unfair to the mod author.
The next version of the mod has a manual page added to show which mods/items are internally blacklisted to make it a bit clearer.

For the loot learns, I learn in two ways:
* when you create a factory I start to learn from fake kills of that factories mob/enchant pairing.
* when a mob is killed in any other way, I learn the drops from that mob and the enchant level of item that killed them - including no enchant.

**Comment by Ipsis** [comment]
All Cyberware items are blacklisted now, so they wont show up for any mobs.
Manual has been updated to make it clear which wont work.

8e603e07a4dc99b7952c3fa2157992eb7377e1f0
