### ISSUE TITLE
Autocrafting AE issues with crafting 

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#138]
Shift-clicking may eat the dyes.
Need to investigate the whole autocrating of the items.

**Comment by Ipsis** [comment]
1. Autocrafing with a hammer recipe, uses the hammer up completely.
2. Autocrafting with a dye recipe, uses the dye up completely.

**Comment by Ipsis** [comment]
See https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2752

**Comment by Ipsis** [comment]
So my custom recipe handling is wrong.
Look at the vanilla handling and work from there . eg. buckets.

**Comment by Ipsis** [comment]
eg. Cake recipe uses three water buckets and gives you back three empty buckets

**Comment by Ipsis** [comment]
Changed the YahHammer and Dye to hasContainerItem = yes and dropped the ShapedOreHammerRecipe. That means the only problem now is the obsidian in the recipe.

**Comment by Ipsis** [comment]
015f445173b458cfcdd121cbeaab93b577f32c8a

**Comment by Ipsis** [comment]
Fixed and tested with AE2.
My some of those recipes are complicated!

**Comment by andremiller** [comment]
Is this fix included in Woot 1.10.2-1.2.6? That's the version currently in FTB Beyond and my AE2 crafting patterns are still consuming the hammer and dyes :(

**Comment by Ipsis** [comment]
The fix is in 1.10.2-1.30 which I'm hoping to release this weekend. Feature creep has slowed down that release a bit.

**Comment by andremiller** [comment]
Thank you Ipsis. Reading " Ipsis added this to the 1.10.2-1.2.6 milestone on Feb 19 " in one of the updates above was what made me think it was in 1.2.6, so no worries!

**Comment by Ipsis** [comment]
Github doesn't seem to update with the new milestone, so I can fully understand the confusion.
