### ISSUE TITLE
[1.11.2-0.1.0] giving power to an unformed factory crashes dedicated server

### ISSUE THREAD

**Issue by kreezxil** [Ipsis/Woot#141]
Everything but the mob prison was added when the power cell was placed and then server crashed but wouldn't go down and doesn't come back up.

Here is the related crash that was reported to RFTOOLS which was the mod with the powercell that was used. Mcjty's response is attached that explains how to fix it.

https://github.com/McJty/RFTools/issues/1046

**Comment by Ipsis** [comment]
And there is me getting caught by something that I knew McJty had already pointed out to be people. I feel ashamed now :( I'll get this fixed up and I'll have to solve it for 1.10.2 as well.

**Comment by Ipsis** [comment]
I've had a look at my code and I'm really confused.

I cannot see a path in my code that would generate this crash and I believe that the rules that McJty explained I'm following.
I also cannot replicate the crash while running Woot and RFtools with a client instance or a dedicated server.

Is there anything in the server logs on startup that explains what it stopping it from starting?

**Comment by kreezxil** [comment]
I'll setup a special test and hey back to you.

-----Original Message-----

**Comment by kreezxil** [comment]
This is likely the very same crash issue as I'm trying to duplicate just that, but this time I have specific details on how to duplicate it. Now I'm going to use just rftools and woot together in their own pack by themselves to see if I can duplicate this or if there is an odd mod conflict somewhere.

Issue:  1.11.2-0.1.0 crashes dedicated server Forge 1.11.2 build 2237

Notes:
     crash while placing a powercell from rftools to a mob factory proxy extender, but when the powercell is connected directly to the woot factory there is no crash

crash report:
https://gist.github.com/c1c06c6959307efeda4d0942f2208144

fml server latest:
https://gist.github.com/96eee6737b9505783234ee38ef4416a9

**Comment by Ipsis** [comment]
Excellent, I can reproduce that. The extender bit set it off for me as well.

**Comment by kreezxil** [comment]
I made just a build of pack with only mcjty mods and woot, and got the following

https://gist.github.com/8d7077a4378b441157efda08fa9fb034

**Comment by kreezxil** [comment]
Gonna try with a different power source to see if I can get you a more refined target.

**Comment by Ipsis** [comment]
Fixed - I think

bf2f0559857e4b998bc6d7a9ca854fb121286bd5

**Comment by Ipsis** [comment]
I've uploaded a new version to Curse which should be available soon.
1.11.2-0.1.1

**Comment by kreezxil** [comment]
cool, I'll test it here shortly.

**Comment by kreezxil** [comment]
ok, i tested it and it is now fixed.

**Comment by eslachance** [comment]
Is this fixed/going to be fixed in 1.10.2? I'm on the FTB Beyond pack (on a server) and we're having this issue: https://github.com/McJty/RFTools/issues/1080

**Comment by Ipsis** [comment]
I forgot to release the 1.10 fix which I will be doing tonight

**Comment by Ipsis** [comment]
See https://github.com/Ipsis/Woot/issues/149
Fixed version for 1.10.2 uploaded to curse.
