### ISSUE TITLE
Add support for modded Ender Dragon

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#144]
This bug covers only the modded versions of the Ender Dragon, such as Draconic Evolution

**Comment by Ipsis** [comment]
* supported by config file entry
* no support for looting

eg.
S:EnderDragonLoot <
20,1,draconicevolution:dragonheart,
100,8,draconicevolution:draconiumdust
percentage,stacksize,item
>

**Comment by CidsADev** [comment]
Is this config going to be only for the Ender Dragon or are other mobs going to be configurable too?

**Comment by Ipsis** [comment]
Only for the EnderDragon as I'm going to treat it as a special case.
The EnderDragon is one of the only mobs that has a non-standard death sequence, therefore my normal loot learning technique will not work. 

Theoretically for any other mob, if you were to modify the vanilla loot tables, then my mod would pick up those new drops ...... assuming that the mod support vanilla loot tables ..

**Comment by Ipsis** [comment]
Configuration options added for any drops required from the EnderDragon.
