### ISSUE TITLE
[Question] Adding mobs from other mods ?

### ISSUE THREAD

**Issue by Thyriel** [Ipsis/Woot#145]
Is it possible to add non-vanilla mobs so they can be farmed with woot (when i tried the prism returned an error) ?
If yes, what do i need to configure ?

**Comment by Ipsis** [comment]
They should just work with no extra setup. However I blacklist some mods for compatibility reasons. Which mob are you having trouble with?

**Comment by Thyriel** [comment]
Cyberzombies from Cybeware mod

**Comment by Ipsis** [comment]
That would be one of the blacklisted ones. See #113 for the reasoning for that particular mod. There is a page in the manual that shows what is internally blacklisted.
Sorry about that.

**Comment by Thyriel** [comment]
Np, thanks anway ;)
