### ISSUE TITLE
Support Draconic Evolution

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#148]
Blacklist all mobs from Draconic, as they use non-standard loot dropping mechanics.
Add support for the Draconic drops from the Ender Dragon.

**Comment by Ipsis** [comment]
[CHAT] Mob Chaos Guardian cannot be captured (Woot:none:draconicevolution.ChaosGuardian)

**Comment by blacksythe** [comment]
http://i.imgur.com/6xORRKu.png

**Comment by Ipsis** [comment]
The real Draconic support will be in the next release, so you can capture it just now. Enjoy it while you can :)

**Comment by blacksythe** [comment]
Perhaps i should elaborate on my previous comment as that picture was taken at 01:30 in the morning, draconicevolution:dragon_heart entity spawns at your feet as apposed to being put into a chest, additionally gaining hearts this way is way to op to actually have them in the mod without some sort of additional requirements

**Comment by Ipsis** [comment]
It is the way that Draconic generates it's drops for both the Ender and Chaos Dragon. When I add the correct support then you won't get all those drops on the ground.

**Comment by Protheus** [comment]
this is Awesome !!... don't care if it is OP or not 👍
