### ISSUE TITLE
Wrongly placed Proxy crashing the game

### ISSUE THREAD

**Issue by Thyriel** [Ipsis/Woot#149]
I initially thought the main issue is in the Immersive Engineering mod, so please see my report there too. BluSunrize explained the issue that Woot's "Mob Factory Proxy" Block is causing - when wrongly placed - on a technical Forge level there:  (... is illegally returning null for a getCapability check. Per Forge's convention, this is not allowed  ... )
https://github.com/BluSunrize/ImmersiveEngineering/issues/1961#issuecomment-285970172

To repeat the problem, build a woot farm, connect a Mob factory extender on it's bottom, then a second extender on that one, and then a proxy on the side of the 2nd extender. (See screenshot: http://imgur.com/a/weKyU )

If you then connect any power to that Proxy block (that does connect, e.g. conduits from EnderIO seem to check that the block isn't valid and don't connect at all. Immersive Engineering for example does connect so it crashes then and renders the savegame useless)

Crashlog: http://pastebin.com/TWurJ0Fh

Background why i even tried to place a proxy there: As IE's best cable connector can only provide 4k RF/tick and the tier4 max upgrades wither farm needs over 30k i would have needed 8 connectors, so 1 proxy is too less to get it fully powered.

**Comment by Ipsis** [comment]
From a quick read of Blue,s comments this is the thing I fixed in 1.11 but never pushed the 1.10.2 fix for.  I'll try and push a hotfix tonight.

I didn't even know more than one proxy block would work :)

**Comment by Ipsis** [comment]
1ac305e10aedae51c161c54235b3d28ef1c45a1a

**Comment by Ipsis** [comment]
Uploaded to Curse and should be available soon
https://minecraft.curseforge.com/projects/woot/files/2392812

**Comment by Thyriel** [comment]
Thanks :)
