### ISSUE TITLE
Crash on server when placing a base block

### ISSUE THREAD

**Issue by kwpugh** [Ipsis/Woot#15]
MC 1.9
Forge 1865
Mod version woot-1.9-0.1.0-beta.jar

When I placed a base block on the ground to begin building a structure, the server crashed.

crash report: http://pastebin.com/raw/tazF9G4u

**Comment by Ipsis** [comment]
That looks like a stupid mistake on my part. I'll try to get a fix up quickly.

**Comment by Ipsis** [comment]
Fixed in woot-1.9-0.2.0-beta
