### ISSUE TITLE
Spawning Ars Magica "Dryad" mob will cause mass numbers of Nature Guardians to spawn in world.

### ISSUE THREAD

**Issue by JaSpr** [Ipsis/Woot#151]
So, Ars Magica adds a passive mob cause the Dryad.  If you kill too many of these, a Nature Guardian will show up and they're really damn hard.  So, to avoid them, I captured a Dryad in a Woot prism and stuck it in my Tier 4 spawner/farm/grinder.  After about 20 seconds TONS OF Nature Guardians started spawning in the 3x3x3 cube that Woot uses to drop (and collect) loot.  I turned off the spawner after about a minute, and now it's about 10 minutes later, and they just keep spawning.

We're going to blacklist the Dryad, but I wanted to make sure you guys were aware, as both Ars Magica and Woot are part of the "All the Mods 1" pack

**Comment by Ipsis** [comment]
I'll blacklist that mod in the next release.
It is the one disadvantage of trying to support all mods without special code, there are always a few funny ones that need banned.
Thanks for the info.

**Comment by JaSpr** [comment]
the Mod id (for woot) is Woot:none:arsmagica2.Dryad

**Comment by Ipsis** [comment]
Fixes in the 1.10.2-.1.2.7 release.
