### ISSUE TITLE
[Request] Stacking Mob Prism, to use it

### ISSUE THREAD

**Issue by Blizzor** [Ipsis/Woot#152]
I have a request, which can make the Mod harder.
First I want to say, I love the idea, to reduce the lag with only spawn the items.
But it is to easy. You can spawn a wither, run away and spawn netherstars like it is dirt.
All you need is energy. With a Netherstar generator it is done.

But now the idea. Can you let the Mob Prism Stack, so you need to kill 100 Mobs with the Prism, to get a useable Mob Prism.
So the player first need to kill some of this mobs to can spawn it.
The Mob Prism should be do more Damage for this idea.
And because it should be expensiv, if it makes more damage than an Diamond Sword, it should cost something like 4 Diamonds and an Netherstar (or something similar).

This would change the ritual to a "mid-game" ritual and would make the mod more interesting and difficult.

**Comment by Ipsis** [comment]
The mod, as it stands, is similar to the other spawner systems.
For EnderIO you just capture with the soul vial, with MFR it was the safari net.

Originally I did think of the "100 kills" idea, but that took it too close to the "Soul Shards" mod.

The factory tiers are supposed to bring some sort of progression to the mod. For example you cannot farm the Wither Boss, until you have enough Nether Stars to create all the Tier IV factory blocks.

I may be changing the capture mechanics to require you kill the mob and the prism would be programmed on the mob death .... but I'm still considering that.

**Comment by bookerthegeek** [comment]
Another Idea, is maybe add some integration with SoulSards? 

Maybe a config to craft a soul shard into the mob prism of that mob?

**Comment by Ipsis** [comment]
So for 1.12, we now have a kill count for the prism.
This defaults to 1, so you have to kill one mob.
It can be configured on a per-mob basis.
