### ISSUE TITLE
Server Crash Loot table is full.

### ISSUE THREAD

**Issue by dillyo09** [Ipsis/Woot#153]
When loading up 1.10 FTB beyond on the server, we get the error of this error: http://pastebin.com/ctWEspuG

We only used a tier 2 factory with other mob controller sitting on a wall nearby for use.

**Comment by Ipsis** [comment]
This is somewhat confusing as to how this happens. Can you post the loot.json file that is loaded on boot please. I'm wondering if something in there is corrupting the Loot Manager on boot. One thing you could do in the meantime, is remove the loot.json file and restart the server, which should at least let the server start.

**Comment by dillyo09** [comment]
The loot table json file is empty.(Might be because we took into single player and remove all of it including the plugin). When we did have it up when looking the mob controller, what ever it was maybe walla said hold shift to view loot table, when I did so it was constantly ticking up.

Example: when I had a skeleton in it, the loot table was ticking up the bone starting at one and going up every couple of seconds highest I saw it was over 200, I am not sure if it ever stop ticking it up.

![capture](https://cloud.githubusercontent.com/assets/3910464/24016283/cc7086a6-0a48-11e7-9ff6-19cebf9201a7.PNG)

**Comment by Ipsis** [comment]
Out of interest is this just a Beyond server or is it running some extra packages such as Sponge?

**Comment by dillyo09** [comment]
The only thing installed on the VM is a Beyond server with no extra packages.

**Comment by Ipsis** [comment]
I'm not completely sure what is going on and I cannot seem to replicate it.
But there may be a bit of code that is suspect when the loot file is loaded.

I think it is possible that if the loot file to load for reasons other than it didn't exit,, then the lootMap might be null, therefore causing the "ipsis.woot.manager.loot.LootTableManager.isFull(LootTableManager.java:139)"  error.

I'm going to try and replicate the conditions that it might break and see if they cause the same error.

If I'm correct, then deleting the loot file would fix the issue.

The Waila tooltip counting up over 200 is a different bug that I think I've fixed. The number that you see in the loot table display is the percentage chance of the drop. Under some circumstances the percentage was report as > 100% which is clearly wrong.

**Comment by Ipsis** [comment]
I've managed to replicate the problem.

Basically I'm not catching the exception when loading the file, that the file is empty.
The then leaves the lootMap being null and you get the crash when anything tries to access it.
I'll have to cleanup the loading of the loot file and handle the "exists but is empty" case as well.

**Comment by Ipsis** [comment]
Fixed in 1.10.2-1.2.7
