### ISSUE TITLE
Blood Magic Tank Output isn't working (altar output does work, though)

### ISSUE THREAD

**Issue by rakutenshi** [Ipsis/Woot#157]
I have it working with altar out put, but I cannot for the life of me get it to output to any tank. I've tried placing multiple different types of tank blocks in front of the Mob Factory block, the Mob Controller block and the factory proxy block, none of them seem to work and EnderIO conduits don't detect it as a fluid compatible inventory. I've even tried the blood magic blood tanks, to no avail.

Does it need to have a specific type of tank in order for the Life Essence to output to it?

**Comment by Ipsis** [comment]
I've tested with a standard EnderIO tank placed directly beside the proxy or the factory. I'll retest to make sure I've not broken anything since I last tested. I gather this is 1.10.2?

**Comment by Ipsis** [comment]
I've retested with a Fluid Tank and a Pressurised Fluid Tank from EnderIO and both of those work.
The fluid conduit doesn't work on mine either, probably because it is not of the correct internal type.

I tested with the tank in front of the main factory block and on four sides of the proxy block with no issues.

My test basically consisted of the factory, ritual and altar setup.
Then I placed down the EnderIO tanks and they started filling.

Could you please post a picture of you setup.

**Comment by rakutenshi** [comment]
went and made a pressurized fluid tank from EnderIO to test with and neither is getting fluid,  first image is in place of the chest I use to accept loot output before sorting out to pipes and drawers, second is attached to proxy (front, relative to main factory block), was given a couple of minutes to run before screenshot was taken in each case, and tank was set to draw from side facing Woot factory.  I also checked the version that the server was running and it is the 1.2.5, so this may have been corrected in the updates to 1.2.7, also possibly relevant is that the modpack is ResonantRise, I will contact the server admin about updating the mod to current and see if that resolves the issue. 
Are there any possible config settings that could be responsible for this behaviour to check?
![woot_factorytopressuretank](https://cloud.githubusercontent.com/assets/22158900/24080748/71cc1834-0c7b-11e7-920e-8510b093b1de.jpg)
![woot_proxytopressuretank](https://cloud.githubusercontent.com/assets/22158900/24080749/71ccd490-0c7b-11e7-85c1-a079fb5bbbfa.jpg)

**Comment by rakutenshi** [comment]
Does an altar also have to be placed within range of the ritual before it starts outputting to tanks? 
You said the test setup included an altar, was that present when thank was filling or did you have it removed when you tried the tank?

**Comment by rakutenshi** [comment]
(farnsworth voice) Good news Everybody!
Apparently the server update has resolved the issue, gonna go ahead and close this, thank you for taking the time to look into it though, Ipsis!
