### ISSUE TITLE
"Not Enough Wands" Acceleration Wand speeds up mob factory by 10-20 times.

### ISSUE THREAD

**Issue by JaSpr** [Ipsis/Woot#160]
I attempted to add the Mob Factory block to the blacklist for BBW's acceleration wand, but have been unsuccessful.  I'm not sure what their config is looking for, but here are the values I've tried:

S:blacklisted_blocks <
        woot:factory
        woot:factory/0
        tile.Woot:factory
        tile.Woot:factory/2
        TileEntityMobFactory
     >

Still, the acceleration wand causes the mob factory to output something like 10-20 times faster than it normally would

**Comment by Ipsis** [comment]
I'll need to look into how the BBW code works as I don't really want to allow this to work. I'm away for the next few days so I'll look into it when i get back.

**Comment by Ipsis** [comment]
Since I'm not confused after looking at the BBW code. Is this actually from Not Enough Wands or am I just missing something obvious?

**Comment by JaSpr** [comment]
Well, now that I look at it, yes. It is Not Enough Wands.  I'll look into their config.

**Comment by JaSpr** [comment]
I'd bet that items that aren't affected by the acceleration wand are items that compare elapsed time, instead of number of ticks.

**Comment by Ipsis** [comment]
I'll look at the Ender IO code to see how that works. Strange that NEW doesn't have a blacklist.

**Comment by Ipsis** [comment]
EnderIo has shouldDoWorkThistick. I think this stops the wand from working on misaligned ticks.
