### ISSUE TITLE
Woot Altar wont spawn Squids!

### ISSUE THREAD

**Issue by 2000game** [Ipsis/Woot#166]
It seems that Squids drop nothing. My altar is correctly build. Testet it on sp and on server with sponge.

**Comment by Ipsis** [comment]
I'm seeing 100% drop rate for ink sacs in a Tier I factory 

So what other mods are you using apart from Woot?
I know there are issues with drops and Sponge, however I'm guessing that your SP test means that Sponge is not involved at all.

/woot loot Woot:none:Squid
[16:44:29] [Client thread/INFO]: [CHAT] Learned loot for Woot:none:Squid/No Enchant: 25 [ 25xInk Sac @ 100.00% ]
[16:44:29] [Client thread/INFO]: [CHAT] Learned loot for Woot:none:Squid/Looting I: 41 [ 41xInk Sac @ 100.00% ]
[16:44:29] [Client thread/INFO]: [CHAT] Learned loot for Woot:none:Squid/Looting II: 0 
[16:44:29] [Client thread/INFO]: [CHAT] Learned loot for Woot:none:Squid/Looting III: 0

**Comment by 2000game** [comment]
I play Beyond from FTB and in SP the Command /woot loot Woot:none:Squid gives no output. If i type something like /woot loot Woot:none:Zombie i get an output. If i type /woot loot sljflsafjsl i dont get an output too.

**Comment by 2000game** [comment]
Just testet it out it is the older woot version that on the server is.

**Comment by Ipsis** [comment]
So which versions are being used?

**Comment by 2000game** [comment]
woot-1.10.2-1.2.6

**Comment by Ipsis** [comment]
I'll have to retry this with Beyond and not within my Dev environment. It could well be that something else grabs squid drops in the modpack and I never get to see them.

**Comment by 2000game** [comment]
Well, it seems that this the bug issn't because of your mod, im playing with oh an server who has an launcher for the modpacks and it seems that they edited the loot config so nobody can cheat. The problem was they forgot the squids xD. You can close this.

**Comment by Ipsis** [comment]
At least it was something simple :)
Thanks for the update.
