### ISSUE TITLE
OreDict recipies

### ISSUE THREAD

**Issue by SiblisCu** [Ipsis/Woot#175]
Recipies don use oredict, for examples diamond shards have the nuggetDiamond tags but tier 3 upgrade plates don accept other items with nuggetDiamond tag. This causes problems with modpacks that unify items with the same oreDict tag.

**Comment by bookerthegeek** [comment]
On the same tier, can we get a config to remove all Ore dictionary types please? Seems odd to smelt my nether quarts into woot quartz shards.

**Comment by Ipsis** [comment]
Recipes do not use ore dictionary in 1.12.
