### ISSUE TITLE
Duplicating glitch

### ISSUE THREAD

**Issue by Henkieboy112** [Ipsis/Woot#182]
When you destroy a mob controller or drop an item on the floor while the farm is running it dissappears, so when you want to destroy something you have to do it with the farm off. But the problem I found is that the items disappear but then drop from the farm with a random chance. So basically it deletes the item that has been dropped on the floor and then it starts giving it as drop. So right now the farm is dropping me item conduits and mob controllers aswell.

**Comment by Ipsis** [comment]
I think this is fixed in the new release as the items are dropping in the loot learning area. I've now moved this to a world height to alleviate this kind of problem. My guess is that you have the factory near bedrock?

**Comment by Henkieboy112** [comment]
I have the newest release, its the 1.3.0 version of Woot. The spawner is at y-level 65

**Comment by Ipsis** [comment]
That is a bit strange, the fake spawning box should be occurring at y-level 253.
I'll need to look into this as it sounds like I've made a mistake somewhere when I relocated the loot-learning box. 

Out of interest, is this a vanilla dimension or a custom one?

**Comment by Ipsis** [comment]
I managed to replicate this ..... and I'm very confused.
I try and work out what on earth is going.

**Comment by Henkieboy112** [comment]
Alright, thanks for working on it so quick! Your mod is awesome. Keep doing what you're doing!

**Comment by Ipsis** [comment]
New release is up on Curse and should be available when they approve it.
Hopefully I've not messed anything out pushing out the release quickly :)

**Comment by Henkieboy112** [comment]
Thanks a lot dude!
