### ISSUE TITLE
Item/tile/describtion name not display in their language

### ISSUE THREAD

**Issue by useenzhekoay** [Ipsis/Woot#184]
The place able blocks such as controller, colored block, etc and one Yah Hammer are not correctly showing their name in game. 
Description for "Mob: @s" include mobs' name does not change when switch language file.

![temp](https://cloud.githubusercontent.com/assets/5300396/24687486/643e5fd2-19ec-11e7-93e8-5c1bc702b2bc.png)

**Comment by Ipsis** [comment]
Not sure what I've got wrong there. I'll have to have a look and see where the translation lookup is missing as I thought I had coded that all correctly.

**Comment by useenzhekoay** [comment]
Okay, just take your time to do it. Thx for your efforts~

**Comment by Ipsis** [comment]
It only appears to be blocks that represent multiple blocks with one id and the hammer.
That should make it a little easier to track down.

I'm not sure I can fix the "Mob: Ender Dragon" as I store that text in the NBT of the object. But I'll check to see if I am not picking up the translated display name correctly for that. So future controllers and prisms might be fixed.

**Comment by Ipsis** [comment]
I've worked it out and it is something trivial.

Your language files were using XXX:woot instead of XXX:Woot.
The modid starts with a capital, so it was not picking up some of your translations.

**Comment by Ipsis** [comment]
FIxed the EnderDragon text for the prism.
This will only work on newly created EnderDragon prisms and mob controllers programmed with that new prism.

There are a couple of other fixed strings that I've noticed, which I will try and move to the language files.

**Comment by useenzhekoay** [comment]
Okay, noted. and sorry for my silly mistake for the mod id in lang file~ Thanks~ It will be more prefect if the Mob: @s  -> "Mob" can be change according to it language too~ The string mentioned only appear in the tooltips of learned prism and programmed mob controller.

**Comment by Ipsis** [comment]
The second commit fixed the Mob: Ender Dragon which I had as a hard coded string.
I tested other mobs and the prism and controller was showing the correct translated text already.
Can you try capturing a different mob and see if you have a problem on the display.

**Comment by useenzhekoay** [comment]
Sorry for not mentioning well, i had try for the mobs' name, all had change well, include the blocks'/tiles' name. Just now i just state only for the hard coded string.
