### ISSUE TITLE
No Wither spawning

### ISSUE THREAD

**Issue by djpanda** [Ipsis/Woot#187]
We are using the "New frontier" pack from curse and i build the max Mob factory with Wither Mob-Controller placed inside a Minecolonies Colony but i didn´t got one spawned and there are no loots @ the chest. 
Could Minecolonies prevent the witherspawning or where could my problem come from ?

Version 1.11.2-0.1.1

**Comment by Ipsis** [comment]
There has not been much testing of the 1.11.2 version so this could be a bug. It is also possible to blacklist mobs and specific loot drops. It can also be another mod grabbing the loot drops before my mod gets a chance.
Wither Boss does work on the 1.10.2 release, but I'll boot up my Dev environment and confirm that there are no issues with 1.11.2.

**Comment by Cal26lum** [comment]
This definitely seems to be an issue in 1.11.2-0.1.1

**Comment by Ipsis** [comment]
Looks like when I create the entity to try and learn the drops, then the WitherBoss is returning null, therefore nothings happens. So I'll have to investigate what is different with this mob from all the rest.

**Comment by Ipsis** [comment]
I've fixed it but I don't like it!
Basically before when you hit the WitherBoss, you got told the entity was WItherBoss and you could spawn it back by using the text WitherBoss.
Now, in 1.11, although the name that is returned is WitherBoss, you need to spawn it with Wither.

So I've put a quick workaround in for that boss, but now I'm wondering how much this is going to happen for other mobs.

**Comment by Ipsis** [comment]
4df8ee6fe084152eadd9929892a5ee913540a93b
