### ISSUE TITLE
[Request] Refine Recipes

### ISSUE THREAD

**Issue by Skar78** [Ipsis/Woot#192]
Hi,

First of all, i love the mod.

Really fantastic. I also like the design concept of being forced to reach the "mob tier" with regular means before being able to have the respective factory.

Because I like it so much, i am motivated to share some feedback to you.

1.) Yeh Hammer Recipes with Obsidian
I was annoyed by the obsidian as i usually by accident auto-stacked it into a Storage Drawer system instead of keeping it somewhere and had to keep track of keeping one for usage with Woot early game.
I just think that is unnecessary, it could have been an Obsidian Workbench or similar, so you cant easily mix it up with other obsidian for different purpose.

2.) Somewhat related: General crafting concept
It just does not feel particularly great to me to have to deal with those dyes and the hammer etc.
If the dyes, hammer are supposed to gate the access somewhat i dont feel how its significant more gating than the nether requirement and it just doesnt feel very smooth.
Several options come to mind, from a placable anvil with recipes to a dye chest (think tic stencil chest) etc. Could even create another shard anvil or similar machine to flash it out a little.
Its not a key point just would add to the quality/experience of the crafting.

3.) Alignment of recipes
If you go from tier 1 to tier 4 you should not end up with left over materials in skulls/capstones imho.
For example if a recipe creates 4 white factory blocks the final amount of white factory blocks from tier 1 to 4 should be a multiple of 4. Same for all other recipes. I built exactly one Tier 4 factory but on the way i had a bunch of left over materials...

4.) Factory upgrade path
As the layout block does not overlay the actual block placed i had a very hard time to spot that the tier 2 caps have to go for tier 3. the notification system was on spot, i just had trouble to come the conclusion to remove the cap stones to check it out. In the end the cap stones remained in my storage as they were suddenly not used anymore - didnt like that.
Think its easier if you "only add" new blocks to the tier below and do not have to remove anything.

Keep up the good work!

**Comment by Ipsis** [comment]
A quick reply while I'm on train.

1 - obsidian is gone from the recipes as is now standard cobblestone which is used on each crafting op. This is mainly to make it compatible with vanilla and therefore AE2 autocrafting.

2 - the main reason for the hammer was to ensure that I only used vanilla items and that that recipe layout was sane. I didn't want to go adding new ores etc, so to give me more freedom I added the hammer and die mechanic. It was never really meant for any gating mechanic.

3 - there was some logic behind the whole costing mechanism for the capstones, but I cannot for the life of me remember what it was. (It was more than just sadism though)

4 - Yes that is a pain. The tiers have to be different to allow the validation code to identify the correct tier. I was having issues with recursion and the simplest fix was to make them distinct. I need to do something about the guide block in this situation but I'm not sure what. I could possibly allow the guide block to verify and highlight the incorrect block - i think.

**Comment by Skar78** [comment]
Well I play on Beyond, with Environmental Tech and Draconic Evolution. Woot is not the biggest OP offender in that pack :)

Regarding 1-2: I would recommend to reconsider the design goals and maybe collect more feedback and revisit it later on.

Regards 3: Also applies to shards. Did you try to figure out how many nether stars you need for the initial tier 4 upgrade? i kind of completely missed the goal and manually farmed 10. The whole 1 star 9 shards and 9 shards 81 blocks thing i completely missed...

Regarding 4: Why one controller for all tiers? Maybe one tier 1 controller than a recipe for tier 1 controller + stuff for tier 2 and so on.
Further: I really expected tier 4 factory to be able to "produce" 1 mob of each tier... Man i was disappointed by that (maybe thats why i am not in the OP camp).

**Comment by Ipsis** [comment]
Since I'm rewriting for 1.12 I'm going to be incorporating some of these suggestions.

**Comment by Ipsis** [comment]
Since I'm a good way through 1.12 now.

2 - we now have a in-world anvil which you use the dies and ingredients on and you have to hit it with the hammer.
3 - recipes are now a bit more exact and dont generate extras. 
4 - rewrote the factory structure parsing and the tiers now built upon the others eg. if you break a tier IV block you would get a tier III factory.

**Comment by Ipsis** [comment]
See 1.12 alpha release for the changes.
