### ISSUE TITLE
Creative Instant Build

### ISSUE THREAD

**Issue by desagas** [Ipsis/Woot#195]
This an enchancememt recommendation.

Are you able to make it so that the display block can be clicked somehow while in creative mode to instantly build the woot structure. When trying to test a world and builds, it would save so much time and effort.

Thanks.

**Comment by Ipsis** [comment]
Its actually something I was considering as I'm sick of building the different tiers during testing.

**Comment by Ipsis** [comment]
I've added some code that will allow you to right-click the guide with a piece of redstone. If you are in creative mode then it places all the structure blocks for you.

**Comment by desagas** [comment]
That's awesome. I can't wait to try it out!!
