### ISSUE TITLE
[Test] BloodMagic test with server/client

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#202]
People still seem to be having issues with the Blood Magic support which I cannot replicate. However it may be possible that this is a server/client specific issue, where I have been testing with client only.

**Comment by MonstersCrafts** [comment]
Currently having the following problem with blood magic support:
The link between mob spawner/ritual and the altar is not functioning.
The mob spawner starts and runs.
The ritual activates with an owner.
The altar is usable (in my case it's all the way to tier 5).
But there is no LP being moved into the altar above.
Configuration is the master ritual block on the 5th block above the mob controller, then the altar on the 3rd  block above the master ritual block.
