### ISSUE TITLE
[Question] Meaning of woot

### ISSUE THREAD

**Issue by wormzjl** [Ipsis/Woot#204]
Hello, I'm a translator and I'm trying to make a localization for this mod.
However I'm having difficulty translating the word "woot", does it corresponds to the explanation here?
http://www.urbandictionary.com/define.php?term=woot
Thank you

**Comment by Ipsis** [comment]
Yes, it is the definition you mentioned. The mod is all about generating loot drops from mobs, so I thought it would be appropriate to call it Woot. 😀

**Comment by wormzjl** [comment]
ok thank you!
