### ISSUE TITLE
Witch farms create water bottles but witches don't drop them normally

### ISSUE THREAD

**Issue by SilverBranch** [Ipsis/Woot#206]
I'm playing on FTB Beyond and my witch farm makes water bottles along side other drops.
Witches, unless modified, do not drop water bottles normally.
Just thought I'd mention it in case it's a bug or intended.

**Comment by Ipsis** [comment]
I would expect empty bottles, I think, but not water ones. Woot learns drops from mob kills and doesn't have any hardcoded drop information. It may just be blind luck, but I'll test witches to make sure I'm not converting empty bottles to water bottles.

**Comment by Ipsis** [comment]
I've ran a quick test for Witches with dev environment and I get the following:
sugar - 16%
stick - 41%
gunpowder - 14%
spider eye - 14%
redstone - 15%
glass bottle - 12%
glowstone - 18%

When I check the chest in front, then I'm also getting empty bottles.
I wonder if there is something specific in FTB Beyond that is adding water bottles to Witch drops.

**Comment by SilverBranch** [comment]
I made another farm in single player and it only had the drops you listed but when I went on to the server that I play on, the farm had 10 different drops. http://i.imgur.com/ED2MKh6.png

**Comment by Ipsis** [comment]
The hats are fine as I think they come from Reliquary. 
The fact that there is only a 1% chance of the water bottle, may mean it is either a really rare drop that has been added from modded, or it has been learned by accident.

**Comment by SilverBranch** [comment]
I'm going to assume that it was learned by accident because it's not there on singleplayer
