### ISSUE TITLE
[1.10.2] Dragon Question

### ISSUE THREAD

**Issue by YOYOK9** [Ipsis/Woot#209]
This is just a config question, What's the difference between the death cost and spawn cost for the dragon? Want to increase the power intake for the spawner to make my players work harder for it. Which would I increase?

config.Woot:globalDeathCostEnderDragon
    I:globalDeathCostEnderDragon=500

XP cost to use for spawning the EnderDragon
    I:globalSpawnCostEnderDragon=750

**Comment by Ipsis** [comment]
Spawn cost plugs into the maths to calculate the power needed to spawn.
Death cost is used to define the XP that the XP upgrade will generate.

**Comment by YOYOK9** [comment]
Ah ok thank you for the fast response.  Any plans to add the chaos dragon from DE? or too much at that point?

**Comment by Ipsis** [comment]
DE Chaos Dragon is internally blacklisted, mainly because its a boss battle added by a mod, which seems unfair to bypass.
