### ISSUE TITLE
[1.9] Server crash on blaze in Tier III

### ISSUE THREAD

**Issue by kwpugh** [Ipsis/Woot#21]
Forge 1865
mod: woot-1.9-0.3.0-beta.jar

Crash report: http://pastebin.com/raw/g5LG3Wn9

I have a Tier III with Mass and Fortune upgrades and a blaze in the controller.   crashed aft a few minutes of running.

**Comment by Ipsis** [comment]
I've reproduced that one and it is nothing to do with the farm, but the way I handle the LivingDropEvent.

I thought it was only raised when non-player entities died ..... and it isn't.
Basically when the player dies my LivingDropsEvent handler is being called with a player class, which causes it to fall over.

So I'll get that fixed when I get home from work and get a new release pushed out.

**Comment by kwpugh** [comment]
Thank you for addressing.   I was starting to get other random crashes on LivingDropsEvent that seem unrelated to the Woot farm directly.

I look forward to testing the new version.

BTW: Players are really liking Woot.

**Comment by Ipsis** [comment]
Fixed in 1.9-0.4.0-beta.

It is the simple things that you forget to test :(
