### ISSUE TITLE
Woot Ender Dragon

### ISSUE THREAD

**Issue by Morphosiz** [Ipsis/Woot#211]
Hi, I would like to ask if the ender dragon is disabled for the woot farm. Currently, I built a woot farm and inserted the ender dragon mob prism. When i try to activate it, it tell me that 'Mob Ender Dragon is Blacklisted (Woot:none:EnderDragon).

**Comment by Ipsis** [comment]
There is a global config value that defaults to true, to support the EnderDragon. It is possible that your pack may have it turned off. (globalAllowEnderDragon)

**Comment by Morphosiz** [comment]
ohhh okay, thanks Ipsis!
