### ISSUE TITLE
Slash Blade Swords Dropping in world.

### ISSUE THREAD

**Issue by braingkk** [Ipsis/Woot#216]
When killing ender dragon with the [SlashBlade](https://minecraft.curseforge.com/projects/slashblade) mod, it normally drops a "broken yamoto" on the ground.
the woot farm learning seems to drop them on the surface above the mob farm, leaving a few hundred swords that dont despawn.
https://puu.sh/vLNx8/4dc27d985b.png

Related mods:
SlashBlade-mc1.11-r9
woot-1.11.2-0.2.0

**Comment by Ipsis** [comment]
That is a bit strange as I dont ever kill the Ender Dragon. It is the only mob that I hardcode the drops from. I'll need to look into it and make sure I'm not still doing the fake kills for that.

Could you see if there is any information in the woot/lloot.json file for the EnderDragon.

**Comment by braingkk** [comment]
https://pastebin.com/rHqEStaV only thing i can see on the server is myst ag drops at ~line 9302.

side note, dont know if the server owner is using wierd configs or what, as the dragon wasnt dropping eggs or breath, only myst ag and silents gems scales. but if its a hardcoded thing, then that makes more sense.

**Comment by Ipsis** [comment]
I'll put the mod in my dev setup and see if I can track down the issue. Just out of interest, how did you create the Dragon prism? Capture it or craft it with a dragon egg?

**Comment by braingkk** [comment]
approached the dragon during breath phase and smacked it.
is there another way im supposed to do it?

side note, im using the "new frontier" modpack by ichigo on curse in case there are other mods messing up mob names etc

**Comment by Ipsis** [comment]
That tells what is going on. In 1.10.2 I made it such that you couldn't hit the  dragon, you had to craft the prism. With the internal name change you are no longer prevented from hitting it and spawning it in the usual way in the factory. It bypasses all the name checks for the dragon support. I'll need to fix this up.

The mob naming is purely inside Woot.

So now I know that EnderDragon support is broken in the current alpha, when hitting it with prism and crafting with the egg.

I'm going to try and tidy up 1.11.2 and get a new alpha pushed soon.

**Comment by braingkk** [comment]
kk glad to help, thnx for your quick response
