### ISSUE TITLE
Can't get LP from factory

### ISSUE THREAD

**Issue by forestbat** [Ipsis/Woot#217]
![2017-05-13_12 02 33](https://cloud.githubusercontent.com/assets/23413915/26022333/c93e1bba-37d4-11e7-9d13-400fc9245c72.png)
My controller is in y=86，and I place my altar（y=89） and ritualstone（y=93）like this，but there isn't LP in the altar，why？

**Comment by Ipsis** [comment]
Is this 1.10 or 1.11? (I'm guessing 1.10)
I'll create the same and see what happens.

**Comment by forestbat** [comment]
@Ipsis Yes，1.10。

**Comment by Ipsis** [comment]
I've built the same setup that you have.
I'm seeing the altar above the factory slowly filling with LP.
Every 320 ticks it adds some LP

![2017-05-13_08 54 30](https://cloud.githubusercontent.com/assets/5602759/26023694/f1111ac2-37b9-11e7-97a8-58eac3ea7e5b.png)

**Comment by forestbat** [comment]
Does the ritual only support rune of sacrifice to build altar？

**Comment by Ipsis** [comment]
All it bothers about is that the altar exists. It call the exact same code as the Well Of Suffering and you get the benefit of any runes that are part of the altar.

**Comment by forestbat** [comment]
![2017-05-13_16 45 35](https://cloud.githubusercontent.com/assets/23413915/26024050/e9385328-37fb-11e7-8bf8-67fca21f7b7d.png)
I added Rate 3 upgrade to the factory and wait for a long time，however，there is still not any LP in the altar。

**Comment by Ipsis** [comment]
What if you replace the chest with an tank, does it start filling with LP?
(Something like an EnderIO tank, as I know that works for me)

**Comment by forestbat** [comment]
![2017-05-13_18 21 29](https://cloud.githubusercontent.com/assets/23413915/26024761/529debfc-380b-11e7-9995-7acaf4dc29e7.png)
![2017-05-13_18 24 52](https://cloud.githubusercontent.com/assets/23413915/26024760/529a4a24-380b-11e7-940f-894034d6bbf4.png)
Not only TE but also EIO，there isn't LP。

**Comment by Ipsis** [comment]
This is really confusing and going to be difficult to fix if I cannot replicate it.
Are you playing on a server or just a normal single player world?

**Comment by forestbat** [comment]
A normal single player world。

**Comment by Ipsis** [comment]
Silly question, but have you activated the ritual with the weak activation crystal?

**Comment by forestbat** [comment]
Yes I have activated many times，and my LP was cost to 0.

**Comment by Ipsis** [comment]
So you had LP in your network before activating and you got the "Flow of energy rushed through the ritual" message? I'm just trying to ensure that the ritual is correctly activated as I'm running out of ideas here. Apologies if you have used Blood Magic rituals before and I'm asking simplistic questions.

**Comment by forestbat** [comment]
Yes I have about 200，000LP before activating and I get the message。

**Comment by JanusNeubauer** [comment]
Ftb beyond 1.10 (1.10.2) 

I have a similar problem. The factory won't fill any kind of tank. If I put a blood altar right above the ritual of the infernal machine it gets filled. But tanks won't work no matter where I place the tank or if there is a blood altar or not. 

The world is running on a server I rent, if you want a look or the world folder as a zip no problem.

**Comment by Ipsis** [comment]
Which kind of tank, just so I know it is not a capability problem. 
If the world folder is not too big then getting access to that would be handy.

**Comment by JanusNeubauer** [comment]
Ender Tank, Portable Tank (thermal expansion), drums (extra utilities). Tried placing them directly and with ducts/conduits. I'll zip up the world folder and upload it, might take a day or two, my upload is based on carrier pigeons.

**Comment by TachiOni** [comment]
Actually Thank you so much Ipsis, I forgot about the activation crystal cause I'm new to blood magic (and was very tired at the time, so that "silly question" was really helpful.
