### ISSUE TITLE
doDaylightCycle false broken

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#218]
With the fix for tick acceleration, the doDaylightCycle=false support has been broken.

**Comment by Ipsis** [comment]
Looks like there are two "world times".
getWorldTotalTime increments per tick
getWorldTime only increments per tick if doDaylightCyle = true

So if I change over to getWorldTotalTime, then both features should start working again.

**Comment by Ipsis** [comment]
914d73322d8e1aa817498049a4173c78dbb9d266

**Comment by brisingraerowing** [comment]
@Ipsis This is also an issue in the latest 1.11.2 Alpha. Just FYI.

**Comment by Ipsis** [comment]
I may have fixed that in 1.11.2 and then forgotten to release it! I'll try and get that done soon.

**Comment by Ipsis** [comment]
Fixed in 1.11.2-0.3.0
