### ISSUE TITLE
Useless Demonic Wills

### ISSUE THREAD

**Issue by TechnicianLP** [Ipsis/Woot#221]
I found a problem with my bloodmagic-wootfarm: 
the demonic wills that are put into the outputchest (could not find the code for those ...) have a value of 0 (and are therefore useless) 
the first 3 wills were working and have a value of 0.47... but it suddenly just stopped working ...
weak bloodshard are being dropped just fine

**Comment by Ipsis** [comment]
This is strange as I don't have any support for demonic wills. It is something that I have to add custom code for as it requires the use of a specific item when killing mobs. Which mod pack are you running and which versions of Woot and BMW.

**Comment by TechnicianLP** [comment]
Woot 1.11.2-0.2.0 
BM 1.11-2.1.10-79
Youre saying you didnt add that drops? where are they coming from then?

**Comment by Ipsis** [comment]
I think I know what is going on. 

Woot learns from both fake player kills and from normal kills. 
My fake player kills cannot cause will to be dropped. 
My guess is that someone killed a mob and that generated some will, which Woot then added to its learned loot tables.

Ill try and release a new version that filters those drops out to avoid broken will drops. 

Woot for 1.11 is currently getting a rewrite and I'm hoping to add proper will support in that.

**Comment by TechnicianLP** [comment]
A thing for the rewrite: is it possible to add suport for custom loottables? eg: place a file named like the mob into the configfolder and itll overwrite the learned loottable (preferably with support for tier/upgrades(looting/bm))

**Comment by Ipsis** [comment]
I'm reluctant to add user configurable mob drops. I need to understand more as to why this would be needed and what kind of drops would have to be manually added this way. So if there is a good reason I'll change my mind :)
