### ISSUE TITLE
Woot.json dosen't generate

### ISSUE THREAD

**Issue by AncientWyvern** [Ipsis/Woot#222]
I build the tier1 woot farm with enough energy and space for items but it will not generate any loot tables

I'm using woot version 1.10.2-1.4.0.jar

the "/woot flush all" and "/woot status" doesn't work

**Comment by Ipsis** [comment]
Does the woot directory get created in your game instance?
Are there any error messages in the logs?
If you have TOP, does sneak looking at the main factory block show any information regarding drops.

What does "/woot mobs" output?
Which mob do you have in the farm and is the farm formed?
What does "/woot loot <mobname>" output?

**Comment by AncientWyvern** [comment]
yes, the factory is formed it's a tier 1 and the mob in it is a skeleton.
nor error in the log.
no drops shown. 
the folder woot is generated and it is a loot.json in it  but its empty
/woot mobs show nothing
/woot loot also nothing

**Comment by Ipsis** [comment]
Bit of a shot in the dark here. Sponge isn't involved in any way?

**Comment by AncientWyvern** [comment]
no, I play singleplayer in the mod pack ftb beyond only mod I added is optifine

**Comment by Ipsis** [comment]
Can you post a screenshot of your factory as this is somewhat confusing.

**Comment by AncientWyvern** [comment]
can't make screenshot today I will make it eventually later

**Comment by AncientWyvern** [comment]
screenshot links incoming sry that it take so long


https://ibb.co/cRHbhk
https://ibb.co/g9GDTQ
https://ibb.co/m41Qa5

**Comment by Ipsis** [comment]
From the screenshots nothing is wrong.
I have the exact same setup but the factory ticks over for me and generates loot.
The factory did not generate anything when it was a vanilla ender chest, but did with a normal chest.

However that should not stop the progress bar from increasing.
It cannot be a tick problem as that would stop the factory from forming.
eg. doDaylightCycle=false would break the factory

You could try /woot dev true
This will disable all power requirements and it what I use when developing.

My best theory is that the reason the progress bar is not increasing is that there is not a single entry in the loot table for the mob. And that would happen if a) no mobs were being spawned to learn from or b) the event that fires on a mob death was being grabbed and cancelled by another mod before I get to it.

Can you try without optifine just to see if that is causing issues, as I'm running out of ideas.
I'm actually running FTB Beyond in SP and I'm not seeing this happen.

**Comment by AncientWyvern** [comment]
i will try that and give you feedback

**Comment by AncientWyvern** [comment]
ok so after I removed optifine and world edit it works fine think it was a mod problem

**Comment by Ipsis** [comment]
Optifine is closed source so I cannot take a look and see what it might be doing. But I'm glad you have it working now.
