### ISSUE TITLE
Woot Spawner freezes at 0 RF, and unlike similar issue, can't be restarted

### ISSUE THREAD

**Issue by ArtOfCombat** [Ipsis/Woot#223]
We've got woot spawners. They were working for a little while, now suddenly they've all stopped, and are not accepting power. We've tried breaking and replacing, rewiring, and changing which mods the wires are from; nothing works.

We are on the attonbitus fork of the FTB Beyond pack, running Woot 1.10.2-1.4.0. The only thing we've changed recently in server settings is turning day/night cycles off.

**Comment by Ipsis** [comment]
That is the problem. The daylight cycle stops the world time from ticking. I have worked around this in 1.4.1

**Comment by Ipsis** [comment]
Fixed in 1.10.2-1.4.1
