### ISSUE TITLE
Blood magic

### ISSUE THREAD

**Issue by GizmoTheAssassan** [Ipsis/Woot#224]
Is there a cap on how much lp you can get from the ritual of the infernal machine because every thing i do it makes a max of 2000 ish lp

**Comment by Ipsis** [comment]
It should fill the altar directly to its capacity. Or your network if an orb is in the altar.
Are you talking here about LP per operation rather than Capacity? 
If it is per operation then the altar runes would determine how much LP is generated as I just call directly into Blood Magic.
