### ISSUE TITLE
Woot Farm Not Getting Power From Mekanism cables/Actually Additions laser 

### ISSUE THREAD

**Issue by Nodnam** [Ipsis/Woot#225]
Mekanism cables are not connecting and Actually Additions laser wont provide power

**Comment by Ipsis** [comment]
Which version of Woot are you running?

**Comment by Nodnam** [comment]
1.4.0

**Comment by Ipsis** [comment]
It will only work with cables that use the Forge energy capabilities. I don't think Mechanism does but I will have to check the AA code. (From a quick look AA should work, so Ill take a look)

**Comment by Ipsis** [comment]
I've now confirmed that AA with Woot doesn't transfer power by loading up the r105 mod in my dev environment.
However looking at the 1.10.2-r105  codebase for AA they are using the COFH API and not the Forge power capability system.

So neither Mekanism or Actually Additions support the Forge power capabilities in their 1.10.2 releases, so they will not be able to transfer power to Woot.

My guess is that AA moved over to Forge power caps in 1.11.2.

**Comment by ahWill** [comment]
Is there any work around to get power from Mekanism to Woot for 1.10, I have just about every other mod but my primary focus has been Mekanism, and that's where all of my energy is kept in.

**Comment by Ipsis** [comment]
None that I know of. If you could get Mechanism to RF then you could maybe manage it but I don't know if that is possible either.

eg. Mechanism to RF to EnderIo conduits

**Comment by ktole1999** [comment]
you should be able to use an energy cube without issues.
