### ISSUE TITLE
Decapitate Upgrades MC 1.11.2

### ISSUE THREAD

**Issue by FlyingScotsman1** [Ipsis/Woot#226]
After testing on creative mode with multiple mob prisms I keep having an issue where the factory will not give either zombie heads or Skeleton Skulls, decapitate seems to work fine for creeper heads and wither skeleton skulls, even at Tier 4 nothing from normal skeletons or zombies, am I missing something, more than enough power is going to the factory and the decapitate is upgraded to Tier 3.

Please help

Thank you in advance.

**Comment by Ipsis** [comment]
It is perhaps not identifying them correctly in my code and therefore not creating the drops for the skeletons. Ill see if I can replicate it and get it fixed.

**Comment by Ipsis** [comment]
I've tested this with 1.11.2-0.2.0 and checked the code which I thought might be wrong.

I've got a Tier 4 farm with Tier 3 decapitate and I've tried creepers, skeletons and zombies.
All of them generate skulls for me.

Are  you getting other drops for the creepers and skeletons while the factory is running?
Which modpack are you running or is it a custom one?

**Comment by FlyingScotsman1** [comment]
Yes I get normal drops from zombies and skeletons, (bones, arrows, flesh, etc) just no heads.

I have custom mods installed, quite a few really, they include Solar Flux, buildcraft, villager trade tables, extra utils, elevator mod, enderstorage, forestry, autopickup, JEI and JER, minecolonies, weirding gadget, waystones, tech expansion and torcherino, and of course, woot.

I build the T4 factory and add Tier 3 upgrades for Rate, XP, Mass and Decapitate, as i said before I know power is no problem (High Tier solar panels) and I get Creeper Heads and Wither Skulls fine, but not the other 2.

**Comment by Ipsis** [comment]
It is as if the zombie and Skeleton are not vanilla, so the head drops don't match.
Can you let me see the loot file that Woot has generated woot/loot.json
I can use that to see the raw names.

**Comment by FlyingScotsman1** [comment]
I don't know any of my mods that change the mobs at all, but idk maybe something that's messed around with it, hope not
[loot.zip](https://github.com/Ipsis/Woot/files/1121456/loot.zip)

Any here's the json, (zipped thanks to this site not accepting json's) thanks for taking the time to look into this one.
Also just to note,the decapitate enchantment on swords works fine on those mobs, only seems to be the factory.

**Comment by Ipsis** [comment]
The enchantment uses a slightly different method to map mobs to head, which I cannot use for the drops. I'll take a look at the Json when  I get home tonight and see if it points to anything.

**Comment by Ipsis** [comment]
The answer is I'm an idiot!
I forgot that I had fixed the names in the latest code, but I've not released the update yet, which is why it was working for me and not you.
So hopefully I'll push a new release this weekend, as there are a few other name things in there as well for 1.11.

**Comment by FlyingScotsman1** [comment]
LOL alright looking forward to the update, great work on an amazing mod and thank you for your help and time.

**Comment by Ipsis** [comment]
Fixed in 1.11.2-0.3.0
Hopefully I haven't broken anything else....
