### ISSUE TITLE
Woot not forming

### ISSUE THREAD

**Issue by WazUpItsZion** [Ipsis/Woot#227]
Hello,

I used the layout block to help me create a Woot farm. When I create the woot farm and right-click the Mob Factory, it says that there is a valid layout, but the farm won't form. I have added power, chest, and a mob in the mob controller and nothing works.

Thank you for the help.

**Comment by Ipsis** [comment]
A few things. 
Which version of Woot.
Does the Wails or Top output show that the controller is programmed. 
Which mob did you use and which tier of factory.

**Comment by WazUpItsZion** [comment]
I think the version is (woot-1.10.2-1.4.0.jar) in Minecraft 1.10. I am using woot on the modpack FoolCraft.

FoolCraft just got updated a couple of weeks ago and that is when the issue started. Before the Foolcraft 1.4.3 my woot farm had no issues.

The mob controller says that it is programmed with the mob. But the mob factory doesn't say it's programmed at all.

I have tried Wither (Tier 4), Slime, Zombie, Witch (Tier 1).

**Comment by Ipsis** [comment]
You dont happen to use doDaylightCycle=false do you?

**Comment by WazUpItsZion** [comment]
My doDadoDaylightCycle was false. I have updated it to true and the farm now forms.

Thank you for the help! :)

**Comment by Ipsis** [comment]
The 1.4.1 release has a fix that allows that to be set to false. 
But I'm glad you back to a working state with Woot now :)
