### ISSUE TITLE
[1.10.2] XP spawn cost not working

### ISSUE THREAD

**Issue by heyoomimi** [Ipsis/Woot#230]
I have the spawn cost of the Ender Dragon set to 750 XP, but every time the dragon spawns, there's no XP being subtracted? Where does the XP cost apply? Am I missing something?
Woot version: 1.4.1
Forge version: 12.18.3.2316

**Comment by Ipsis** [comment]
The spawn xp is used to determine the power cost.
The death xp is used to determine how much xp is generated by the factory.
My explanation in the config files may not be clear.
