### ISSUE TITLE
Shouldn't "dye" be "die"?

### ISSUE THREAD

**Issue by weedenbc** [Ipsis/Woot#231]
Just started playing with the mod and love it, but I have to ask - should the mob use the term "die" instead of "dye"? Or is there some play on words I'm not getting?

The "dyes" the mod uses to create all of its items seem to be manufacturing dies:
https://en.wikipedia.org/wiki/Die_(manufacturing)

**Comment by Ipsis** [comment]
I thought I had fixed that!?
All the language files should be using the word "die".
(Although the underlying internal names might use original, wrong term dye)
Which version are you running?

**Comment by weedenbc** [comment]
Ah - I'm playing it via the Nuts and Bolts Torqued modpack, and I guess it hasn't been updated to the latest version yet. 

Sorry about that - should have checked that before!

**Comment by Ipsis** [comment]
No, that is quite okay.
There is always a chance that I've missing a couple of them :)
