### ISSUE TITLE
Wither not providing loot

### ISSUE THREAD

**Issue by OGKaiser** [Ipsis/Woot#233]
Hey there, I'm new to the modpack so I'm sorry if my issue is known or incompetence but I have been unable to get a wither farm to provide any items. I am playing on All the Mods mod pack, everything is correctly built and the progress bar shows the system completing a kill on a wither but no items spawning. I have tested the same setup with other mobs and it has provided loot, although I haven't been able to test it with a dragon yet. Has there been any changes to the modpack or reports of any similar issues? Thanks.

**Comment by OGKaiser** [comment]
Also worth noting that I do have a diamond chest setup in the correct position to recieve the items.

**Comment by olavim** [comment]
Happening to me too.
All the mods v3.0.0
Minecraft 1.10.2
Woot 1.10.2-1.4.1

**Comment by AMartinie** [comment]
Also having the issue on ATM1.
Woot V1.4.1 for MC1.10.2

Checked configs to make sure I didn't miss anything.

**Comment by Ipsis** [comment]
I'll need to look at the mod pack but it is possible for the pack creator to blacklist item drops. As the nether star drops are considered a bit OP they may have done that. 

Just a first guess though.

**Comment by olavim** [comment]
I just realized the wither boss requires 4 soulsand and 3 wither skeleton skulls as per the pack's default `woot_spawnreq.json`. 

I found the documentation for this only from the changelog:

> - If items are required then they must be in a chest above the mob controller
> - If fluid is required then it must be in a tank above the mob controller

I'll test if this was the issue. Please consider documenting required items and how they are provided to the factory somewhere more easily accessible :)

**Comment by OGKaiser** [comment]
After some testing, yes my issue has been not having the required items in a chest above the mob controller. I had a feeling it was partially my incompetence but I couldn't find a set place where this was explained, even online so hopefully this thread will atleast help others with the same issue.

**Comment by Ipsis** [comment]
Woot allows mod pack makers to specify extra spawn requirement in the woot_spawnreq.json file. By default this file is empty. ATM is adding the extra requirement to reduce the OP part of the Wither.
(I'm actually impressed someone used this feature!)

If you right click on the formed factory mob controller it will show you what extra items you require.

The (very poor quality) in-game manual has a few pages titled "Extra Spawn Requirements" that explains how to check what items are required and where to put the chest/tank.

**Comment by OGKaiser** [comment]
Now that you mention that, I did see the factory mob controller mentioning wither skulls and soul sand but I just didn't put together what was expected. Thank you for the quick and detailed response!

**Comment by OGKaiser** [comment]
It seems that this pack is limiting the reward as well, only giving 1 netherstar per wither being killed. Has anyone been able to locate where that restriction is in the game files?

**Comment by Ipsis** [comment]
Isn't one star per Wither standard even with looting? 
Don't think I let people play with drop stack sizes.

**Comment by OGKaiser** [comment]
Hmm apologies, I think a video or two that I watched skewed my perception of it a little bit. I was under the impression it somehow enhanced the amount of stars dropped when looting was added.
