### ISSUE TITLE
Using mobs from other mods

### ISSUE THREAD

**Issue by SuperSoupr** [Ipsis/Woot#235]
Is there a way to add mobs from other mods into woot?
that would be super useful!

**Comment by Ipsis** [comment]
The way that Woot works is that is automatically learns the drops from any mod that is installed.
There are exceptions when I have blacklisted specific mods or mobs for reasons of balance or out of respect for other mod authors progressions.

Is there some specific mob that is not working for you?

**Comment by SuperSoupr** [comment]
Woow what a fast response time first of all!
And not really, i wanted to know in case i make a modpack and want to disable/change mob drops to not make stuff too easy

**Comment by SuperSoupr** [comment]
I kinda wrote the question wrong....

**Comment by Ipsis** [comment]
You cannot change mob drops but you can blacklist items from being produced.
ie. stop nether stars from being dropped by and mobs from the factory.
