### ISSUE TITLE
Chaos Guardian

### ISSUE THREAD

**Issue by MelanX** [Ipsis/Woot#236]
I know, you removed the Chaos Guardian but I really wanna have the Chaos Guardian in the Factory. Is it possible to add a Tier V factory made with Chaos Shards? And then you may could use so much power (maybe 1000RF/t as default). Do you think it's possible? It would be really nice. You may could integrate in config so you can turn off Tier V.
I'm trying so hard to farm Chaos Shards right now but I cannot find any solution for that, everything I try says "blacklisted" or "InvalidMob" :D

**Comment by Bass2style** [comment]
there is no interest to have the chaos dragon, the drops are identical that the normal dragon. (xp + heart + sometimes draconium dust), nothing more.

**Comment by MelanX** [comment]
Yes, you're right. I forgot that the Chaos Shards are dropping by Chaos Crystal. But there are small piles of the Shards.. Isn't it possible to Let the smallest piles are the loot? Or is it only possible that real-mob-loot can be Woot-loot?

**Comment by Bass2style** [comment]
i dont know, i'm not the mod author, only a user. :D but i think it's possible, a Dragon factory loot's Dragon Breath, a non-mob loot, i think that piles or something is possible.

**Comment by MelanX** [comment]
That's right.. we will see what happens ^-^

**Comment by Ipsis** [comment]
The Dragon Drops are user-configurable via the config file and that is where the Draconic Dust is added. You should be able to add Chaos Shards to that if you can get the correct name.
Not saying I agree with it - but the option is there :)

**Comment by MelanX** [comment]
Ok, thank you :)
I just thought there is a way to get the Chaos Guardian in the Woot factory, because I hate mess and it's mess for me if I get Chaos Shards by Ender Dragon :D 
But thank you :) maybe a Tier V will be added which is very hard to get, think about it :D

**Comment by Bass2style** [comment]
ah, cool, never noticed that. a bit too overkill to set it, but nice to have that possibility.

any ETA for an 1.12 (pré)release ? :D

**Comment by Ipsis** [comment]
I had problems with the Chaos Guardian learning which is why I had to internally blacklist it. The way it dropped items for me to learn from just didn't work. 
1.12 is getting a complete rewrite with basically everything configurable. I'm hoping to get a alpha out on a few weeks with the basics in. (Possibly, maybe, hopefully) :)

**Comment by MelanX** [comment]
Ok, then I wish you good luck with this alpha, I hope with you. It's a great mod. :)
