### ISSUE TITLE
Consider allowing all upgrades on Tier IV

### ISSUE THREAD

**Issue by viveleroi** [Ipsis/Woot#240]
First off, I really enjoy this mod. It felt like a good balance in materials, and being able to farm mobs without actually spawning them has greatly improved my modded mc experience. I can't tell you how many times mobs got out due to some unrelated event, and how much extra grind had to be made to make things safe, not even mentioning the extra entity lag.

Secondly, this may have been done intentionally or may already be possible, if so I can't seem to find reference anywhere.

I'd like to put all upgrades on my Tier IV. Part of why I spent time working towards tier IV is to have the best farm possible, but to truly make it work as I hoped I need to switch out upgrades. 

Thanks!

**Comment by Ipsis** [comment]
It is very much a deliberate choice.
The idea was that there was only so much space for upgrades and you had to choose between them.
With the change in design of the farm layout in 1.12 there is no physical space to support any extra upgrades.
So unfortunately you wont be able to do this. Sorry :(
