### ISSUE TITLE
Draconium dust is too less

### ISSUE THREAD

**Issue by forestbat** [Ipsis/Woot#243]
@Ipsis 
I‘m using 0.3.0 in 1.11.2.
S:globalDropListEnderDragon <
        NO_ENCHANT,minecraft:dragon_egg,1,20.0
        LOOTING_I,minecraft:dragon_egg,1,40.0
        LOOTING_II,minecraft:dragon_egg,1,60.0
        LOOTING_III,minecraft:dragon_egg,1,80.0
        NO_ENCHANT,minecraft:dragon_breath,2,80.0
        LOOTING_I,minecraft:dragon_breath,4,80.0
        LOOTING_II,minecraft:dragon_breath,6,80.0
        LOOTING_III,minecraft:dragon_breath,8,80.0
        NO_ENCHANT,draconicevolution:dragon_heart,1,20.0
        LOOTING_I,draconicevolution:dragon_heart,1,40.0
        LOOTING_II,draconicevolution:dragon_heart,1,60.0
        LOOTING_III,draconicevolution:dragon_heart,1,80.0
        NO_ENCHANT,draconicevolution:draconium_dust,30,20.0
        LOOTING_I,draconicevolution:draconium_dust,40,40.0
        LOOTING_II,draconicevolution:draconium_dust,50,60.0
        LOOTING_III,draconicevolution:draconium_dust,60,80.0
These are what the config displays，but I can only get several draconium dusts from the factory even if I added looting 3 and changed DE's config。
![2017-09-20_22 41 58](https://user-images.githubusercontent.com/23413915/30650667-11a35748-9e56-11e7-8823-65633b960ca8.png)

**Comment by Ipsis** [comment]
That turned out to be checking an itemstack against null instead of isEmpty!.
32e72f9ea74292947e6c208234e1709c448a4a54
