### ISSUE TITLE
Iron golems

### ISSUE THREAD

**Issue by CreepyerGamerX** [Ipsis/Woot#244]
I made an iron golden farm on 1.10.2 with this mod but it's not spawning anything are iron holes like disabled via a config or something because I can't seem to figure out why.

**Comment by Ipsis** [comment]
Just gave this a try with my test world.
100% iron ingot
70% red rose

That was in a Tier I farm.

Can I take it that the farm is forming when you put the programmed controller on?
If you have top installed then sneaking while looking at the main farm block should show you the progress and which drops it will produce. Is the progress increasing and does it register any drops.
Are other Woot farms working for you?
