### ISSUE TITLE
Increase Max Upgrade Totems Allowed

### ISSUE THREAD

**Issue by AndrewR73** [Ipsis/Woot#249]
Could we please have more than four concurrent Upgrade Totems?

http://prntscr.com/h2gba3

-- Andrew

**Comment by Ipsis** [comment]
Afraid not.
It was a design decision to force people into choosing what they actually wanted rather than letting them just slap on every upgrade. You can always get all the loot, you just have to trade off the  getting it as fast as possible against the power needs.
