### ISSUE TITLE
Headhunter enchant causes crash on player death

### ISSUE THREAD

**Issue by kragnoth** [Ipsis/Woot#250]
Mekanism is 326
Minecraft is ... version 31 I think

Most of the info I think is in the crash log itself

https://pastebin.com/L5RDPS1d

Cheers for a great mod.

**Comment by Ipsis** [comment]
Looks like it is the headhunter enchantment that I've screwed up. I'll replicate and get that fixed.
From a quick look that enchantment code is a bit of a mess :(

**Comment by Ipsis** [comment]
It should now be safe for the player to die.
The headhunter enchant is still not correct, but at least you shouldn't crash anymore.
