### ISSUE TITLE
Ticking Player (Casting Exception)

### ISSUE THREAD

**Issue by artman41** [Ipsis/Woot#251]
> Encountered an unexpected exception
> net.minecraft.util.ReportedException: Ticking player
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:194)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:787)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.ClassCastException: net.minecraft.entity.player.EntityPlayerMP cannot be cast to net.minecraft.entity.EntityLiving
> 	at ipsis.woot.enchantment.EnchantmentHeadhunter.handleLivingDrops(EnchantmentHeadhunter.java:98)
> 	at ipsis.woot.event.HandlerLivingDropsEvent.onLivingDropsEvent(HandlerLivingDropsEvent.java:15)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1564_HandlerLivingDropsEvent_onLivingDropsEvent_LivingDropsEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
> 	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:510)
> 	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
> 	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
> 	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
> 	at crazypants.enderzoo.entity.EntityDireSlime.func_70100_b_(EntityDireSlime.java:193)
> 	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:600)
> 	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:571)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2167)
> 	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
> 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
> 	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
> 	... 5 more

Minecraft Version: 1.12.2
Woot Version: 0.0.1

**Comment by artman41** [comment]
looks like a duplicate of #250 
Think the way to replicate is to die since the moment I died the game crashed with the error

**Comment by Ipsis** [comment]
I pretty much screwed that piece of code up. The trace looks like the same casting problem. I'll try and get that fixed quickly and push a new release as soon as possible.

**Comment by Ipsis** [comment]
Same bug, but this certainly pointed at the player death being the problem, which made it much easier to replicate. I'll close this one as duplicate and fix against #250.
Thanks for the extra debug info.
