### ISSUE TITLE
[1.12.2] Guide book instructions for die creation are wrong

### ISSUE THREAD

**Issue by Morpheus1101** [Ipsis/Woot#256]
When right clicking on the Anvil it dosent bring up any GUI interface to allow the creation of Die's

**Comment by Ipsis** [comment]
There is no gui. The guide explains how to use it, but I'll certainly expand on that if it is not clear. Basically you right click with a valid item which will appear on the anvil. Then drop the other items on the anvil and activate with the yah hammer. (By expand on that I mean I can also add extra information to the guide)

**Comment by Morpheus1101** [comment]
Ohh ok, That explains it, being that i admittedly used JEI to look up the recipe rather then using the guide book, explains why i assumed the anvil had a gui.  thanks for clearing that up.

**Comment by Ipsis** [comment]
I detest writing gui code hence the in-world crafting :)

**Comment by Morpheus1101** [comment]
lol, dont blame you, although in this case at least for the Shard die you place the Nether Quartz on the anvil, drop the stygian iron plate on the anvil an then right click on it with the hammer.  The in game guide book sais the opposite :)

**Comment by Ipsis** [comment]
That will teach me not to proof read.
I'll get that fixed up for the next version.
