### ISSUE TITLE
[1.12.2] Stygian Anvil consumes whole stack

### ISSUE THREAD

**Issue by wamc2017** [Ipsis/Woot#258]
Hi,

I know the manual says "drop **one** of each ingredient on top off the anvil", but I tried to throw a stack of diamonds on top of it, before making shards, the result is, the whole stack gets consumed and you only get 3 shards instead of 192... (maybe there should be a count of item check or something...)

Modlist: https://pastebin.com/3vvqCJ8S
Version: woot-1.12.2-0.0.2

Thanks for looking into it.

Kind regards
wamc

**Comment by Ipsis** [comment]
I've updated the code to fix this.
Now when you craft by dropping a stack of the ingredients, then it will only consume the correct amount and leave the rest. 
You will of course have to click multiple times, to process multiple crafting operations, but it is at least a step forward from losing all your stuff :)
Still got to test all the recipes work, but it is looking promising.
