### ISSUE TITLE
Problem with Factory Controller in 1.12

### ISSUE THREAD

**Issue by CharitableClas** [Ipsis/Woot#262]
I added your mod to a personal modpack that I am using and tried to use the Tier 4 version and when I go to verify the factory after having placed everything including the Factory Heart, Factory Controller, Battery, Importer, and Exporter it says that the Factory Controller needs to be placed in a certain location in which that is placed. So I don't know if this is a bug you are trying to fix or if I am just doing something wrong but I read the guide book you have in the game and its not very clear about it. Also how do you make the Mob Controller in the game I have the ender shards with the mob data in them fully programed but when i go to make the controller on the anvil it says recipe does not exist.

**Comment by Ipsis** [comment]
The programmed mob controller that comes out of the anvil goes one block back and up from the heart.
If you cheat a controller in then it won't be programmed. Use "woot give player mob name" to get a programmed one, as that is what I use during debug.  You can tab out both player and mob.

To create one in game. Right-click a full ender shard on the anvil, then drop the other components on top and right click with the yah hammer. The guide should show you what the other components are. That should generate a programmed controller. The shard is only full when you have hit and killed at least one mob. The tool tip should show the count.

**Comment by CharitableClas** [comment]
ok so what you are saying is the recipe that JEI shows is what you use on the anvil but instead of a blank ender shard you use one of the fully programed ones and it makes the mob controller then you place that on the factory where it shows the factory controller and then you hit the factory heart with the torches to validate the factory and start it up?

**Comment by Ipsis** [comment]
Yes. 
I cannot work out yet how to make JEI show the glowing Item stack to make it clearer, but it is on my todo list, as I can see how it could be confusing. 
The structure should firm when you place the last block. 
The torch thing is just for asking it to validate the current structure so you know where the error is. Torch stack size determines which Tier you want to check against.

**Comment by CharitableClas** [comment]
Ok thank you I will do that later today. Also does this work on peaceful or do you have to at least have it on easy since this does not actually spawn the mob just the items they drop?

**Comment by Ipsis** [comment]
As long as you can get the programmed controllers it should work on peaceful.
The mobs I learn from never get spawned into the world. 
Of course how you get programmed controllers or ender shards is up to you. (add them to treasure chests in the world, fully programmed???)

**Comment by CharitableClas** [comment]
Yes I have it working for me on peaceful mode but how long does it take to do the bosses like the ender dragon and wither boss? also can you use multiple of the same upgrades like two full looting tiers instead one?

**Comment by Ipsis** [comment]
Each mob can have their own spawn time, but I only up them for the EnderDragon (10min?) and Wither Boss (will be 5min).
Only one upgrade totem of each type,  they don't stack.

**Comment by CharitableClas** [comment]
Just a heads up don't use the full XP totem upgrade for the Ender Dragon unless you have a huge storage for the XP shards that it produces it filled a chest on me and I didnt get the dragon head or egg from it sadly

**Comment by Ipsis** [comment]
That doesn't sound right. A dragon should drop 500xp, but with full xp totem that bumps to 900xp. Each xp item is 16 xp, So that should be one stack of xp. I'll need to take a look and make sure I've not screwed up the maths again.

**Comment by CharitableClas** [comment]
16 xp per item and a stack of 64 of them will give you 1024 xp only thing is with the ender dragon if you are translating what it usually drops into items you get 70 levels out of the enderdragon which im not sure how much XP that is but it is a lot. 

    On Wednesday, November 29, 2017 2:28 AM, Ipsis <notifications@github.com> wrote:
 

 That doesn't sound right. A dragon should drop 500xp, but with full xp totem that bumps to 900xp. Each xp item is 16 xp, So that should be one stack of xp. I'll need to take a look and make sure I've not screwed up the maths again.—

**Comment by Ipsis** [comment]
I'm using a fixed value in the config file for the dragon xp.
It is possible that my code is ignoring the value and using the real dragon value. 
I'll need to try this and see what my xp gen code is doing.

**Comment by CharitableClas** [comment]
That sounds to me like what is happening is that your code reads where you want it to use the XP Shards amount but instead of using your code its reading the XP amount of the Enderdragon and giving the appropriate number of shards for it.

**Comment by Ipsis** [comment]
From my experiments:

Dragon (No Mass upgrade)
Tier I XP: 500XP =>31 XP shards
Tier II XP: 705XP => 44 XP shards
Tier III XP: 901XP => 56 XP shards

Dragon (Tier III Mass upgrade = 6 Dragons)
Tier III XP: 5409XP => 338 XP shards => 5.5 stacks

So my debug is showing that each Dragon death is generating a base value of  500XP, which I'm then converting into then appropriate XP shard count. (This matches the value I have in my config files).

Granted with the Tier III XP and Mass it generates 5.5 stack of XP shards, but that still gives space for the Dragon Egg and Dragon Breath in a standard chest.

So I'm not seeing the same problem that you are - which means this gets a lot more difficult to fix.

Grated if you didn't have an output chest and then ran the factory with these upgrades, there will be nowhere to put anything. The Dragon drops will never be generated, but the XP still builds up inside the factory. If you then put an output chest in place, the next Dragon spawn would dump all the stored XP into the chest.

**Comment by CharitableClas** [comment]
Thats the thing I am using the Iron chest mod and had a Diamond chest sitting there when I started using the Ender Dragon controller I was waiting on it then decided to try something else so I went and mined the controller to replace it when i got back to the chest it was full of xp shards
