### ISSUE TITLE
[1.12.2] Factory ignores mass modifiers

### ISSUE THREAD

**Issue by OneEyeMaker** [Ipsis/Woot#264]
Hello.
I found strange issue with Woot mob factory. It looks like mob factory ignores modifiers when it "kills mobs" (*searches its' loot*).
I built Tier 4 mob factory *without any modifiers*, placed chest near exporter and creative energy cell near bettery. Factory worked perfectly and produced 2-4 items per cycle.
After adding Looting III upgrade (column from all 3 upgrade blocks), power usege is *increased* (it's OK), but amount and quality of loot **didn't  change**.
The same behavior occurs after adding Mass III modifier and *both* Mass III and Looting III.
I tested it with such mobs as Zombie and Enderman mob types.

Maybe, other modifiers also affected (I didn't tested).

Please, check and fix this.

P. S. Thank you for your work!

/*
  MC 1.12.2
  Forge build 2556
  Woot 1.12.2-0.0.2
*/

**Comment by CharitableClas** [comment]
With Looting its more of a chance to get better loot than outright getting a lot of it. I think with Looting III you get maybe a 60 - 80% chance of more loot. From what I understand of the mod (I am not an expert coder or anything of that nature I just started playing around with it) it acts like you are killing the mobs it spawns but without the actual danger of doing so. So its like you have a Loot III sword going around killing mobs you get a higher chance for a head and a better chance for more of the regular loot but its not guaranteed to always be that way.

I let mine run with the Mass III Rate III and Loot III for a while and got a few heads from the wither skeletons I was doing. but it was like if I went after them myself. Just without going to the nether and looking for them.

**Comment by OneEyeMaker** [comment]
@CharitableClas 
Description of Looting modifier [directly says](https://github.com/Ipsis/Woot/blob/1_12/src/main/resources/assets/woot/lang/en_US.lang#L235), that it increases amount of drops (like Looting enchantment does).
Description of Mass modifier says, that it increases count of 'killed' mobs per cycle. Mass III by default searches loot for *6* mobs.

Just try to kill 6 Zombies with sword with Looting III. You'll get about 20 Rotten Flesh (+ carrots/potatoes). Woot mob factory with Looting III and Mass III gives about 1-3 Rotten Flesh.
From that I assume that it's bug.

**Comment by CharitableClas** [comment]
This is just from my experience and from reading things around here the factory has to learn the loot that each mob has while it works so it will be a little slow at first once it finishes learning all the loot it will get better I started using a Slime factory and it was making 2-5 slime balls to start with with the looting III tier on it. I left it alone for a bit and came back a few mins later and it had two stacks of slime balls. So from that what I get from it is that it takes a minute to learn what loot each mob drops and when it finishes learning that it starts adding the looting III and things like that. Of course I could be completely wrong as well and its a major bug but this is just my opinion.

**Comment by OneEyeMaker** [comment]
I know about learning of factory. But how long is this learning?
I tested it before creating issue and test it again now. Factory outputs 1-3 items with Mass III + Looting III - no matter how long to wait (1 minute, 30 ninutes or hour).

**Comment by CharitableClas** [comment]
which mobs are you using on it? because I got it to do the Elder Guardian and was getting a lot of stuff Slimes took longer because they are different sizes and zombies can carry and drop so much stuff its hard to tell if its working or not.

**Comment by Ipsis** [comment]
I'll need to do some experiments to make sure that both the looting and the mass are being applied correctly.

What is supposed to happen is that that the factory will learn the drops for that looting level - eg. 40% chance of dropping flesh.
When loot generation occurs then for each item that could be dropped it checks to see if you were lucky enough to get the drop and that generates the loot for that kill.
That process is then applied for each mob - ie multiple times if there is a mass drop.

So from a quick look at the code there is a problem with the mass upgrade.
I'm clearing the loot that can be generated after the first mob has been processed, so you only get loot for the first mob.

So the chances are that is the bug you are seeing  - mass upgrade has no effect on loot output.
That will be fixed in the next alpha release.

**Comment by Ipsis** [comment]
I'm now getting multiple drops generated for a creeper with a mass upgrade.
