### ISSUE TITLE
[1.12.2] Factory not forming

### ISSUE THREAD

**Issue by Ar4093** [Ipsis/Woot#265]
Trying to set up a basic Woot farm, starting with Tier I. When I fill in all the blocks displayed by the Factory Layout block, the following issues arise:

The multiblock doesn't form. Right-clicking the Heart with a torch brings up the information:
`Validating factory forTier I`
`No Power Cell`
`No Importer`
`No Exporter`
These blocks aren't displayed at all in the Layout.

Then I tried to place those items (Factory Importer/Exporter and Basic Power Cell) on the factory, but it didn't seem to work.

Playing around a bit, placing the three blocks somewhere directly below the Heart causes the message to go away, so right-clicking with a torch only says `Validating factory forTier I`. The factory still doesn't form though. Do these need to go into specific positions?

Also, the block immediately below the Heart looks to be empty, is that intended?

### Versions
Forge: 2531
Woot: 1.12.2-0.0.2

**Comment by Ipsis** [comment]
The three blocks have to be in a certain order which is documented in the guide book. They also have to be directly below the heart, but can be up to 10 blocks away. 
And yes, the block below the heart is supposed to be empty. 
I'll eventually get some images in the guide book to make this all a bit clearer, as it is all text just now and easily missed.

**Comment by uehlbran** [comment]
Where is this guide book at? It's not an item in 1.12, it's not on the wiki (which is literally useless general statements like "used to kill a mob"). Why did you not document your work? Do you comment your code? This is extremely frustrating.
