### ISSUE TITLE
[1.12]Crafting bug about Factory Casing

### ISSUE THREAD

**Issue by SihenZhang** [Ipsis/Woot#266]
Minecraft Version: 1.12.2
Forge Version: 14.23.0.2556
Mod Version: 0.0.2
Singleplayer/Multiplayer: Singleplayer

Additional Information:
![](https://i.imgur.com/sKyqAbY.png)
![](https://i.imgur.com/e2R05nE.png)

**Comment by Ipsis** [comment]
I've either got the recipe wrong or the tool tip wrong. Either way it should be a simple fix for me.

**Comment by Ipsis** [comment]
I was close it was the language text AND the texture!
Casing + Flesh -> Factory Flesh Cashing (structure_block_0)
Casing + Bone -> Factory Bone Cashing (structure_block_1)
