### ISSUE TITLE
Should decrease rate of woot for getting witherboss and enderdragon？

### ISSUE THREAD

**Issue by forestbat** [Ipsis/Woot#267]
https://tieba.baidu.com/p/4954648741
https://tieba.baidu.com/p/4599388374
https://tieba.baidu.com/p/5445143857
I know you don't understand Chinese，but I can explain them for you。
In the first post，the author can get 900 dragon hearts in an hour，means 4 seconds 1 heart，with phantom bees in FR and TT，draconic bow and so on。
The second post said the author can get a nether star in 3 seconds with Chopper in TConstruct，electric spawner in EIO and DE's grinder。
The third post means somebody used masher in MobGrindingUtils，900 skulls in 20 minutes，means 15 witherbosses in a minute。
So in fact，we already can get nether star or draconic heart in serveral seconds without woot，woot of 1.10 isn't so OP——instead，now 6000 ticks a witherboss or dragon is too slow。
I hope you can recovery the speed of killing witherboss and enderdragon like 1.10——although we can change rate in config，in fact，most of players don't know this they only will say it's too slow。

**Comment by Ipsis** [comment]
I'll consider this as there are examples of alternatives that are far faster.
If Woot is not an attractive solution then people may use the, possibly higher lag options, which kind of defeats the purpose.

So I will certainly look into this, however I'm still torn on what the default will be.
No matter which option I take people are not going to like it - ie the backlash against the Nether Star generation rate with a Nether Star generator being "free RF".

**Comment by Ipsis** [comment]
My current thinking is this - and this is just an idea at present.

Defaults will be slow for the EnderDragon(4@10min) and WitherBoss (4@1min), with full rate upgrades these will reduce to EnderDragon(4@5min) and WitherBoss(4@30sec). This is to combat the OP part of those mobs. (Therefore you can get an EnderDragon drops every 1.25seconds and a WitherBoss drop every 7.5seconds)

However there will be a new special block to attach the factory.
With a Tier IV factory, plus full mass upgrade and full rate upgrade, this block will override the special spawn times and will use the defaults instead. => EnderDragon and WitherBoss 4 every 8 seconds.

This block will be enabled by default and can be completely disabled via config option.
The recipe will be something like the Dragon Head plus high-tier enchanted books etc.

**Comment by forestbat** [comment]
I think it's good。
