### ISSUE TITLE
No documentation for 1.12.2

### ISSUE THREAD

**Issue by uehlbran** [Ipsis/Woot#268]
I've been looking around for some kinda documentation for woot 1.12.2 and I can't find anything. Nothing in game, no mod spotlights for the updated version. How does this all work I can't figure this out...

The prism when you hit a mob doesn't program. I've hit every single vanilla mob in minecraft and it never programmed it like in 1.10.2. How do you program it? I used the /woot give command, but using that the factory won't form. All it says is factory not formed yet. It has power, a programmed mob controller and is built correctly. What is the problem with this?

**Comment by OneEyeMaker** [comment]
There's in-game documentation.
Now Woot requires Guide-API. And all documentation Woot adds in book **_with Guide-API_**.
(Just search in JEI for ```@guide```).

**Comment by Ipsis** [comment]
I've never worked out how to get the guide to show up in JEI with @woot, so as ObeEyeMaker says you need to search for the guide API specifically.
Hopefully there is some way as it is really confusing trying to find it.
