### ISSUE TITLE
I can't use Prism?!

### ISSUE THREAD

**Issue by ulobaka** [Ipsis/Woot#273]
Version 1.12. Tried to kill and shift+right click doesn't work. HOW IT WORK? Help.

**Comment by Ipsis** [comment]
Hit the mob with a EnderShard and that will program it. Then keep that in your inventory and kill the mob. The EnderShard should now be glowing.
Then use the Anvil to craft the EnderShard into a controller.

**Comment by ulobaka** [comment]
Thank you! ^_^
