### ISSUE TITLE
Tier I not formed

### ISSUE THREAD

**Issue by ulobaka** [Ipsis/Woot#274]
Make my first build, but it's not working? I attack ender shard my cow then I kill it. Make Factory Controller with Cow 1 tire, but messages say; Factory not formed? Build factory how saw me blue block(guide block). Help me XD How start my factory?
![screen](https://user-images.githubusercontent.com/34457970/33880005-3d1e4d3e-df41-11e7-9ce4-3f389a5e63ae.jpg)

**Comment by Ipsis** [comment]
Did you add the remote blocks underneath the factory. It explains in the in-game guide where they can be and the order to place them. They are not (yet) displayed by the guide blocks.
The remote provides the input, output and power blocks.
If you right-click with a single torch on the main factory heart, it will also tell you what is wrong. Each torch validates a different tier

**Comment by ulobaka** [comment]
I am trying build factory in creative mod, but it's doesn't work. =( Add export, inmport, power cell blocks under factory it didn't work. 

![2017-12-13_01 54 44](https://user-images.githubusercontent.com/34457970/33907896-bef242d8-df97-11e7-9c32-e37333b2d4af.png)

**Comment by ulobaka** [comment]
![2017-12-13_02 02 38](https://user-images.githubusercontent.com/34457970/33908224-bd967bc4-df98-11e7-8646-14838fc34376.png)
i did used torch but it's not help me XD Wrote me Validate for Tier1 and that's all

**Comment by Ipsis** [comment]
I'm a little confused as I just tested this with a cow and if worked perfectly.
I used "/woot give Player326 minecraft:cow Cow" and that gave me the programmed controller.
Placing it on the factory immediately formed it.

What order do you have the remote blocks in?
It should
top - power cell
middle - importer
bottom - exporter

From the picture it looks like you have (?)
importer
cell
exporter

**Comment by ulobaka** [comment]
Ipsis Thanks! ^_^ It's Working now. I think u make some guids about Factory because guide block didn't help me with my problem, i love y and this mod so much=) Good luck with u mod!

**Comment by Ipsis** [comment]
There is a guide book , but it doesn't show up in JEI.
If you search for woot in JEI you should find it provided by the guide-api.
All text just now in the guide book, but hopefully some more useful images will be included soon!

Glad you've fixed your problem.
