### ISSUE TITLE
Problem with Spawner

### ISSUE THREAD

**Issue by gamerforme** [Ipsis/Woot#275]
![2017-12-12_17 38 29](https://user-images.githubusercontent.com/34485393/33897111-de48f650-df64-11e7-86b9-97d3127cf4e4.png)
Why does not a multiblock formed?

I Hoppe you can help me

**Comment by Ipsis** [comment]
Which block do you have at that location?
Which mob did you create the controller from?

**Comment by gamerforme** [comment]
I have found my mistacke i have made it with an Enderman, but now I've put in a zombie and it's called Factory not Formed


Gesendet von Mail für Windows 10



Which block do you have at that location?
Which mob did you create the controller from?

**Comment by gamerforme** [comment]
Sorry the importer was fals

**Comment by Ipsis** [comment]
Each mob has a minimum factory tier that is show in the controller tooltip. That would be why the Enderman wouldn't work. 
The remote column of power cell, importer, exporter can be up to 10 blocks beneath the factory heart.
