### ISSUE TITLE
Power cell recipes don't use the correct json in recipes

### ISSUE THREAD

**Issue by ulobaka** [Ipsis/Woot#277]
Hello, today i built Factory Tier IV when I was finding 1 problems with craft( I'm playing on FTB Direwolf20). Craft didn't see a enchanted book(Power II), how can i fix this problem? All Basic power cells didn't use anywhere!
![2017-12-15_18 13 31](https://user-images.githubusercontent.com/34457970/34043651-0648d33c-e1b3-11e7-959b-7c53cb8b345d.png)
![2017-12-15_18 13 38](https://user-images.githubusercontent.com/34457970/34043652-06821fc0-e1b3-11e7-9bab-37e96a71ff26.png)

**Comment by Ipsis** [comment]
This is what I thought might happen.

Basically there was a change in the more recent versions of Forge that impacted how the enchanted books are handled via the json recipes and the nbt they contain. The new recipes wont work with the older Forge.

I've checked the recipes and I forgot to update the cell recipes, but I did update the upgrade recipes.
So I'll need to fix that - sorry :(

**Comment by Ipsis** [comment]
5f127d8e4c7ae353f49a446a636d275539160fca

**Comment by ulobaka** [comment]
How i fix this? on my minecraft. I need y help Ipsis Xd

**Comment by Ipsis** [comment]
I need to release a new version.
I don't know if there is a way for you to update the recipe files.
Possibly vanilla let's you override recipes?
Or just cheat a cell in just now and delete the ingredients from your inventory.

**Comment by ulobaka** [comment]
ohh, my world without creative =( so I'm waiting a new version from your mod. Thanks for help lpsis !

**Comment by Ipsis** [comment]
I'm hoping to get a 0.0.4 release out today, just got a couple of things to tidy up first.

**Comment by Ipsis** [comment]
https://minecraft.curseforge.com/projects/woot/files/2510256

Hopefully that fixes your problem and doesn't introduce any new ones :D
