### ISSUE TITLE
Bug with enchanted books again.

### ISSUE THREAD

**Issue by ulobaka** [Ipsis/Woot#279]
Hello its me^_^ Today i tried craft upgrade modules and was finding bug with enchanted book in recipe, it didn't see a book again =(( problems with efficiency II and rate II, possible  next upgrades has this problem too. Need update Ipsis =)

**Comment by Ipsis** [comment]
I've just rechecked with 0.0.4.
I can create all the upgrade recipes with vanilla enchanted books.
Which version of Woot are you running?

**Comment by ulobaka** [comment]
0.0.4 my version, and woot can use refined storage mod? and all connect under factory?
![2017-12-17_18 11 33](https://user-images.githubusercontent.com/34457970/34079754-d252489a-e344-11e7-8d53-3ed58b65ea6c.png)
![2017-12-17_18 11 37](https://user-images.githubusercontent.com/34457970/34079755-d2aa5fbc-e344-11e7-84da-e5b35e84f380.png)
![2017-12-17_18 11 58](https://user-images.githubusercontent.com/34457970/34079756-d2d28118-e344-11e7-89ba-669a1a00efe7.png)

**Comment by Ipsis** [comment]
Do you have Actually Additions to see the NBT data?
Can you try the craft in a vanilla crafting table?
I tested with vanilla and with RFTools crafters.

**Comment by ulobaka** [comment]
Yes i have. For this craft i use vanila crafting table 
![2017-12-17_18 28 45](https://user-images.githubusercontent.com/34457970/34079892-14179f6c-e347-11e7-8a86-2d6634f7d118.png)
![2017-12-17_18 28 52](https://user-images.githubusercontent.com/34457970/34079893-143be782-e347-11e7-944d-ae11cefb16f9.png)

**Comment by Ipsis** [comment]
So this is confusing.
Which version of forge?
Can you enable advanced tooltips and show the extended debug from Actually Additions when you hover over the book. (Think it is ctrl-shift and it should show the complete NBT of the item).

**Comment by ulobaka** [comment]
My forge  version is 14.23.1.2555 I can't use advanced tooltips, because i'm playing witout creative. My mc it's FTB Direwolf20.

**Comment by Ipsis** [comment]
I'll need to load up a DW20 instance and drop Woot in as I need to see the enchanted book information.
Just out of interest, how did you get an enchanted book - vanilla or modded method?

**Comment by ulobaka** [comment]
Vanila method, with 15 bookshelfs and 1 enchated table

**Comment by ulobaka** [comment]
Ipsis, why u mod don't accept in factory anything? I tried make Factory Wither, there is work, but don't give me Nether star! I tried use, hoppers, chests, pipe and it didn't give me my nether star )

**Comment by Ipsis** [comment]
Put a chest in front of the exporter block and as long as the factory is formed it should produce a nether star.

**Comment by ulobaka** [comment]
Yes i did it, but it's not produce and not use items for spawn? but hud wrote , that factroy is working=/ 
![2017-12-17_20 37 03](https://user-images.githubusercontent.com/34457970/34081142-0af66996-e35a-11e7-96a1-f7785e21f371.png)
![2017-12-17_20 44 13](https://user-images.githubusercontent.com/34457970/34081144-0ba11f4e-e35a-11e7-8108-47fdccf042ac.png)

**Comment by Ipsis** [comment]
The hud is telling you which items you must feed the factory with to spawn a single wither.
You need to put wither skulls and soulsand into a chest beside the importer block.
The nether stars are then generated in the chest beside the exporter block.
By default only the Wither and EnderDragon have ingredients.

**Comment by Ipsis** [comment]
I just tested with the latest DW20 pack and added Woot 0.0.4.
All crafting recipes for upgrades worked correctly inside an AE2 terminal.
Enchanted books from the vanilla enchanting table, correctly created the upgrade when used in a vanilla crafting table.
All NBT in the recipes matched up with the enchanting table output.

**Comment by ulobaka** [comment]
Ohh, thanks, may be i reinstall Woot, and it'll work. I have 1.2.0 ver Direwolf20 but now is 1.3.0 need update this FTB.
