### ISSUE TITLE
Tier V

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#285]
Add a tier V factory.
The only reason for this to exist is to allow the bypassing of the spawn and mass restrictions and have it spawn mobs at a silly rate.

It will default to enabled but you will be able to disable it in the configuration.

Why am I adding this?
Because some people like to spawn stuff as fast as possible.
Why is it configurable?
Because other people don't like this sort of thing.

**Comment by OneEyeMaker** [comment]
It would be very nice!
If you plan to add next tier of factory for spawning in silly amounts, maybe you consider allowing spawn of *forbidden* mobs (such as Chaos Guardian from Draconic Evolution, most bosses from Twilight Forest,...) **only at this tier**.
If it is technically possible, of course.

**Comment by Ipsis** [comment]
For anything that isn't "broken" I only blacklist forbidden in the config files, so they can be enabled again. So you should be able to assign a Twighlight Forest boss to a Tier V factory.

eg. The following are forbidden, but would actually work
    "twilightforest:naga",
    "twilightforest:minoshroom",
    "twilightforest:hydra",
    "twilightforest:ur_ghast",
    "twilightforest:yeti_alpha",
    "twilightforest:snow_queen",
    "twilightforest:giant_miner",
    "twilightforest:armored_giant"


Initial testing of the Tier V spawning 8 Wither every 4 seconds .... > millions of RF/tick required :D
(Might need to tweak that a bit!)

**Comment by forestbat** [comment]
Millions？Oh it's too much，only reactors in DE or MEK can support it。

**Comment by Ipsis** [comment]
It is a combination of the mass upgrade scaling the power cost per mob, then the dramatic rate reduction causing the RF/tick to sky rocket.  So yes millions of RF/tick is excessive and I need to find some way of bringing that down.

However even after I make some more changes, spawning mobs in a Tier V to get them running at - in the example above - 1 Wither every 0.5 seconds - is going to be power hungry,

**Comment by OneEyeMaker** [comment]
Millions of RF/t isn't so big cost. Many mods can produce energy in such amounts (except those already mentioned - EnvironmentalTech, NuclearCraft, Advanced Generators; the last one should be configured properly).
Also, would be very useful to have some *base energy consumption value* for Tier V in config, on which total energy cost calculation is based.

**Comment by Ipsis** [comment]
I'll maybe update the Wiki with how the power cost is calculated so people can see how configuration impacts the calculation. 

Until I get round to that though the below is the calculation code.
The base values really come down to how much health the mob has, how much power is required per health unit and how many mobs you are spawning.

https://github.com/Ipsis/Woot/blob/1_12/src/main/java/ipsis/woot/power/calculation/Calculator.java
https://github.com/Ipsis/Woot/blob/1_12/src/main/java/ipsis/woot/power/calculation/UpgradePowerCalcMass.java

**Comment by Ipsis** [comment]
https://github.com/Ipsis/Woot/wiki/Woot-PowerCalc

A start of the explanation.

**Comment by Ipsis** [comment]
Config explanation (defaults) https://github.com/Ipsis/Woot/wiki/Woot-WootCfg
Config explanation (mob specific) https://github.com/Ipsis/Woot/wiki/Woot-FactoryConfig

**Comment by Ipsis** [comment]
So I've been playing with Tier V and these are my rough plans.
They are all based off the fact that Tier V is for sheer greed :)

Tier V will only override a full upgrade totem. eg. Rate II will act the same as normal, you need to use Rate III to see the impact.

Rate III - 20 ticks
Mass III - 8 mobs
Decapitate III - 100%
XP III - 200%
Looting III - no impact
Efficiency III - 50%

WitherBoss (Mass scales at base2)
Rate III - 20 tick spawn rate =  1.3M RF @ 63.3K RF/tick
Mass III - 8 Wither Boss every 1200 ticks = 153M RF @ 127.9K RF/tick
Rate III + Mass III - 8 Wither Boss every 20 ticks = 153M RF @ 7.7M RF/tick

EnderDragon (Mass scales at base2)
Rate III - 20 tick spawn rate = 12.7M RF @ 636.0K RF/tick
Mass III - 8 Dragons every 12000 ticks = 1.6G RF @ 127.9K RF/tick
Rate III + Mass III - 8 Dragons every 20 ticks = I wouldn't bother even trying that one!

Blaze (Mass scales linearly)
Rate III - 20 tick spawn rate = 185.6K RF @ 9.3K RF/tick
Mass III - 8 Blaze every 320 ticks = 179K RF @ 560 RF/tick
Rate III + Mass III - 8 Blaze every 20 ticks = 307K RF @ 15.4K RF/tick

Of course you can just not run both Rate III and Mass III at the same time on Tier V, or use Rate II or Mass III which will use the default values. Or you could add the efficiency upgrade to bring down the power cost.
