### ISSUE TITLE
Factory not forming 1.12.2

### ISSUE THREAD

**Issue by sathanis** [Ipsis/Woot#289]
Hello!

Been searching around on and off for 2 days now, but haven't found any solutions. I've read the other Issue post where he couldn't get it to work either on this version.
Problem is that I really can't get it to work at all. I'm placing down the template block and is building it exactly like it says. I've tried all Tiers, but to no avail. It always says "Factory not forming". I've tried it on a clean minecraft (forge), same results, i've tried it with and without power block, export and import (with and without chests) but it will not work.
I tried the 1.10 version and that one I got to work on first try. 
Am I missing something obvious or is it a bug?

Thank you for making it, I would love it if it worked! :)

**Comment by Ipsis** [comment]
As a starting point, take a stack of torches with the same number as the tier you are trying to build.
If you hit the factory heart with those torches it will validate the factory and tell you what is wrong. 
You do need the cell, exporter and importer beneath the factory which isn't shown by the guide (yet)

**Comment by sathanis** [comment]
So i've been playing around with the tips you gave me, I didn't know about the torch thingie or that they must be placed straight under it. It still won't work though.
It says: "Validating factory forTier xx" (xx=tierlevel) when hitting it with torches, and still factory not formed when hitting the heart.
Any more tips? So far i've just tried on a modpack, should I try it on the clean version aswell?


EDIT:
I got it to work. I'm so sorry for misunderstanding, it was the order of which to place exporter, importer and cell that was wrong.

Thank you for a great mod and I hope I didn't bother too much! Merry Christmas!

**Comment by Ipsis** [comment]
The book really needs pictures added as this has caught a few people out.
But I'm glad you finally got it sorted out.
