### ISSUE TITLE
[1.12.2] few issues with woot 

### ISSUE THREAD

**Issue by JoeSGT** [Ipsis/Woot#290]
Versions i am running is 
Forge - `1.12.2 - 14.23.1.2581` also tried `1.12.2 - 14.23.1.2555`
Woot - `1.12.2-0.0.4`

So when i attempt to create the woot T. 1
and i right click it it said `Factory not formed` then i used torches and right click the factory heart
it said this 
```
Validating factory forTier I
Block at 7781,73,-26463 should be a Factory Controller
No Power Cell
No Importer
No Exporter
```
then i used a quick tp to those cords by using the command `/minecraft:tp` <username> `7781 73 -26463`
and it's at the location of the where i put the Factory Controller
i'm not sure why it's not detecting the Factory Controller
under the Factory Heart i put Factory Exporter and then under exporter i put Factory Importer then i used premium power cell under the importer i had also used basic power cell
then after doing this it still said `Factory not formed`  then again i attempt to use the Torches to figure out why it's not forming any thing and it seem that the Factory  Controller is still not being detected 
after reading a few issues here on this github about other having issues  i saw that you can use the redstone to auto build the tiers for you
so i place down the Factory layout with T 1 and i tried T2, T3, T3 ,T4 and used a redstone right click it on it once it's auto build i get rid of the layout and place down the remaining blocks Factory Heart and Factory Controller *(since it didn't auto build it)* and right click it yet again it still said  `Factory not formed` 
i had even tried using Ender shard and killed a cow and attempt to right click with heart and controller it still wont work still having this  `Factory not formed` 
i had tried this on a singleplayer world and multiplayer world *(with and without spongeforge)*
i had read a lot of issues on here and couldn't get it too work and i had tried using youtube for help 
stilll couldn't get anything to work 

another issue is when i used a Stygian Iron Anvil and saw im JEI there this GUI that shows the recipe on which to make things on it 
i had place this anvil above a magma block and right click with a programed ender shard on the anvil and see that it's there on top of the anvil and right click with ya hammer still saying `no matching recipe`
i did this with and with the hammer and i dont even see this GUI that it shows in JEI

EDIT: here is also a few image of the T1 that i auto build and place down the heart and controller
https://gyazo.com/bab936106f29b2729f08d6419a8b6f10
https://gyazo.com/16ba6029c503214df16e1e8192ddccf6
https://gyazo.com/96ea6414096a42440ab5fd6a42305683
https://gyazo.com/c87c968f3ec60a6215e8f9fbf524e04d
https://gyazo.com/e155f1d0e9224fa2d045ac645db0d141

the outline in yellow it's vanilla chunk border that i did with `F3 + G`

**Comment by Ipsis** [comment]
The guide book is not clear on how this is supposed to work and I really need to get some pictures in to help people. I probably need to make the validation messages be a bit more helpful.

So for the factory:
* The remote blocks can sit up to 10 blocks below the heart. However they must be in a specific order with the cell at the top, importer in the middle and exporter at the bottom.
* The controller has to be created in the anvil. If you take one from JEI then it wont be programmed and the factory will not form. If you want to cheat one in for testing there is a command "/woot give <player name> <mob> <display name>" eg. "/woot give Player254 minecraft:zombie Zombie"

For the anvil there are two steps.
* Right-click with the shard to put it on the anvil.
* Drop the rest of the ingredients on the anvil.
* Hit the anvil with the hammer

There is no gui on the anvil the JEI just shows what to right-click on the anvil and what to drop on it.

**Comment by JoeSGT** [comment]
Ah! that make sense i was following the Wiki on github also xD there a lot of misleading information 
thanks for clearing it up <3

Thanks i got it

**Comment by Ipsis** [comment]
Not got round to updating the Wiki for 1.12.2 as lots has changed in this newer version. The guide book will be your best source of information for this version and hopefully I'll get the Wiki updated ... eventually :D

**Comment by JoeSGT** [comment]
but can you make the guide book more clearer ?

**Comment by Ipsis** [comment]
Yes - it is currently just an early draft so people would have some information.
The problem is of course, that it is obvious to me, but I wrote the mod .
So what I think is clear is really confusing to everyone else :D

If you can give me some idea of what part was confusing and I can change or add to the guide to help.

**Comment by JoeSGT** [comment]
oh never mind is that i didn't read the guide book well as i should have but thanks you
EDIT: possibly add pictures? xD it can help greatly!

**Comment by Ipsis** [comment]
Pictures are definitely on my list and should be simple to add to the book - I hope!
