### ISSUE TITLE
Looting Upgrade Produces No Loot

### ISSUE THREAD

**Issue by RussianSanity** [Ipsis/Woot#299]
Using Woot v**1.12.2-0.0.5**
On Multiplayer, I am using **Spongeforge-1.12.2-255-7.1.0-BETA-2831** currently
Note: _This works fine in Single Player._

I didn't know if I should report this to you or to SpongeForge, so I'll see what you think first.

So I made a tier 3 altar for enderman, provided it power, and the gui looked like this:
https://gyazo.com/a5a11e28ca3241e9d25e18c285f9aac0 

But when I put the Looting I upgrade on the altar, the drops stopped coming and the GUI shows no drops at all. In Single Player it doesn't do this:
https://gyazo.com/7de84fd19fa31fe6583b8f37050f8a30
The setup: https://gyazo.com/6b7e52f1a7b8f3ba2fc5f3ca5a160140

It appears the other upgrades are working though.
I'm going to be updating this mod and spongeforge in the next 24 hours or so. If any other changes happen I'll update this post. Just thought I'd report this to you in hopes for a fix or something.

**Comment by Ipsis** [comment]
It is a long standing issue with Woot and Sponge I'm afraid. The below Woot bugs contain more info and links to the bugs raised with Sponge
#288 #139

**Comment by RussianSanity** [comment]
Aww that sucks. Maybe one day they will finally smooth _all_ the bugs out. HA. Thanks anyways!
