### ISSUE TITLE
1.12.2-0.0.6 Crafting items containing enchantments. nvm got it working

### ISSUE THREAD

**Issue by SkippyMitch** [Ipsis/Woot#301]
![image](https://user-images.githubusercontent.com/27940256/34903813-deb12128-f7fe-11e7-952b-ab201471111e.png)

**Comment by SkippyMitch** [comment]
Working now, but apparently it's just Jei that doesn't recognize the book.

**Comment by Ipsis** [comment]
To handle the different types of enchanted book and the recipe json files, I had to add some custom recipe code. Unfortunately that doesn't seem to work nicely with JEI. As you discovered the recipes will actually work, just that JEI might not always show them.
