### ISSUE TITLE
I have a feature suggestion

### ISSUE THREAD

**Issue by JBSTheGamer** [Ipsis/Woot#302]
I wondering if you can make a guide book for woot. I think that thing will be a very good item to add to this mod. The book can tell you how to set up the mob factory and what each block does and everything else in this mod. If that’s a good feature then let me know and if it’s not then just close this.

**Comment by Ipsis** [comment]
If you install the Guide-API there is one :)
Once you've installed that mod, search for "woot" and you will see the book.
It is in an early stage just now but has some helpful information.

Although the book is provided by Woot, it is only available with the Guide-API.
