### ISSUE TITLE
Tier I Structure not forming [1.12.2-0.0.7]

### ISSUE THREAD

**Issue by jordan-moore** [Ipsis/Woot#303]
Followed Factory Layout Guide for structure...

Used:
- 2 Factory Tier I Caps
- 2 Factory Upgrade Bases
- 10 Factory Flesh Casing
- 14 Factory Bone Casing
- 1 Factory Heart
- 1 Factory Controller (Bound to vanilla zombie, states tier 1 in tooltip)

No right/left clicking (shift pressed and not pressed) with hands, Ya Hammer, or any other block/item is yielding any messages like in older versions. No structures form.

![image](https://user-images.githubusercontent.com/28622898/34919931-98bf792c-f938-11e7-9830-1ee06e3cc205.png)

**Comment by Ipsis** [comment]
If you right click the factory with a torch if will validate the factory for you and tell you what is wrong. (1 torch = tier I, 2 torches = tier II etc).

What you are missing is the remote structure that sits underneath the factory and consists of a power cell, importer and exporter. If you look at the guide book (you need Guide-API installed and search for "woot") it will tell you where it can got.

The remote structure is so you can power and have the output/input chests for the factory hidden underneath.

**Comment by jordan-moore** [comment]
Thank's for the hasty reply. Installed the guide. Got the blocks underneath, and the structure to form properly. 

If anyone else finds their way to this issue, picture for reference shown bellow.

![image](https://user-images.githubusercontent.com/28622898/34920533-4fee8648-f942-11e7-997b-e5e2cc7ea08c.png)

**Comment by Ipsis** [comment]
Until the Wiki is updated (or I find a good way to display the remote blocks with the layout block) I'm pretty much relying on the Guide Book.
I think I need an item in the main mod that in some way points to the guide book and the Guide-API.

So apologies and I'm glad you've got it all working now.
