### ISSUE TITLE
1.12.2 woot 0.0.7 - Max power input?

### ISSUE THREAD

**Issue by molander-dev** [Ipsis/Woot#304]
Does woot have a max power input to the heart?

I'm currently outputting 2.5Mrf/t and still it cant fill the woot internal buffer when its running at 3652RF/t, without hooking up to more sides of the heart, and running the mobs that require 60k ish rf/t i can just dream about then.

**Comment by molander-dev** [comment]
Seems to be around 3Krf/t

**Comment by molander-dev** [comment]
It is a Tier 4 factory but the setTier for power consumption seems to run at the tier 1 code.

**Comment by Ipsis** [comment]
I'll have to test that again as I thought I was running some very high rf/tick recipes with multiple connections to the power cell. (I never connect direct to the heart) 

Each power cell has a different max rf/tick and storage capacity. 

So just for replicating the issue, which power cell are you using? 

The settier code is the initial value. That value is then updated with another call to set the correct max/transfer from the block metadata - if it is working properly.

**Comment by molander-dev** [comment]
Havnt tried The woot powercells, tried cryoducts from cofh, tried fluxnetworks with ignore limit and tried rftools powercells with cobfig raised to allow up to 2,5Mrf/t per side

**Comment by Ipsis** [comment]
The power cells are part of the factory remote structure, along with the importer and exporter.
The tier of cell you have on that should determine the max stored and transfer rate.

**Comment by molander-dev** [comment]
Okey i tried crafting an Premium Power Cell, but I can't seem to get it to connect somewhere.

**Comment by Ipsis** [comment]
Replace the current cell in the remote with the premium one.

**Comment by molander-dev** [comment]
There is none in the remote, There is only importer and exporter. The cell wont connect.

**Comment by molander-dev** [comment]
Oh! nvm

**Comment by molander-dev** [comment]
Stupid me, thanks

**Comment by molander-dev** [comment]
Ye now it works properly.

**Comment by Ipsis** [comment]
Good, I'm glad that turned out not to be a bug :)
I'll try and make that clearer in the guide for people.
