### ISSUE TITLE
[Suggestion] Ore Generation, Stygian Iron, Spawn requirements

### ISSUE THREAD

**Issue by ilyahryapko** [Ipsis/Woot#305]
Hello. For example, I've already got world I'm playing in. So finding new ores is kinda bad. What if make a production multiblock, that transforms iron into stygian. Or I coud make CraftTweaker recipe, but I dont see oregen disabling option in config. And how about adding ingame changing option for spawn requirement? Just like Woot Control Center
Thank you

**Comment by Ipsis** [comment]
There is no oregen in the mod :)
You convert it iron ore into stygian iron ore via crafting.
https://github.com/Ipsis/Woot/blob/1_12/src/main/resources/assets/woot/recipes/stygianironore.json
People are free to add oregen if they want though and disable the crafting recipe. 

So what kind of spawn requirement changing ingame are you thinking of?
Is it just an alternative to changing the Json files or am I missing something.

**Comment by ilyahryapko** [comment]
Strange. I definitely saw, that there is no recipe for stygian iron.
Only oregen. I've just added it from Twitch to DW20 1.12. Am I doing something wrong? Can you please give me configs without oregen. Because I do not understand what to do. Today I have no time, maybe see it tommorow. But I definitely saw only oregen, not the craftable way in JEI. Very strange

Yeah, just block that can specify items needed for spawn for each mob

P.s. If I delete/clear json with spawn requirements will I spawn wither without any soulsand and skulls? Or I must keep some syntax?

**Comment by Ipsis** [comment]
I'll  check that recipe when I get home as I have no oregen in my mod.
As long as you clear the block for that mob and leave a valid Json you should be able to spawn without requirements.

**Comment by Ipsis** [comment]
Retested with DV20 1.12 + Woot 1.12.2-0.0.7
Hovering over Stygian Iron Ore in JEI and using 'R' to jump to the recipe, showed me the crafting recipe with "iron ore + netherrack  + soulsand + YAH Hammer" -> Stygian Iron Ore. No worldgen was shown for this.

Can you post a screenshot of your JEI screen for the stygian iron ore lookup?

**Comment by ilyahryapko** [comment]
Ipsis, I'm so sorry. I do not know what it was, but now everything is fine. I cann't realise why I thought that it was oregen. Sorry for wasting your time and thank you

**Comment by Ipsis** [comment]
No problem. I'm happy you have it working now.
