### ISSUE TITLE
NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting

### ISSUE THREAD

**Issue by 4rz0** [Ipsis/Woot#313]
Have a crash report from the following log:
https://hastebin.com/qonobovigo.sql

Client started up without any issues 2 days ago, today it crashes instead.

**Comment by Ipsis** [comment]
Cannot access that Web page for some reason.
Did the version of Woot change and do you use a Chinese locale?

**Comment by 4rz0** [comment]
No, I don't use a Chinese local.
And for some reason, I cannot access it now, either. Weird.

But worry not, it turned out Mojang changed the library.
I had to restart my launcher to update to the newer version.

I'll attach the crashlog later if you still need it.

**Comment by 4rz0** [comment]
Uploaded the crashlog to a different page.
https://pastebin.com/H8gqM85v
