### ISSUE TITLE
Server crash on rightclicking Factory Heart

### ISSUE THREAD

**Issue by Coding-Kiwi** [Ipsis/Woot#316]
woot version 0.0.9

crash report:
https://pastebin.com/ApaJ0kHD

**Comment by Ipsis** [comment]
I think I've tracked this one down to calling getTileEntity(x) where x is null.
It has however brought up a more interesting questions of me calling getTileEntity, isBlockLoaded with null.

So I'll fix the bug you reported and audit the other possibles instances of this.

**Comment by Ipsis** [comment]
Thanks for this bug report - it identified a mistake for the the multiblock logic I rewrote!

The reason you were seeing a crash, was that the remote part of the factory was no longer required for a valid factory, which is incorrect. I've updated that check.

I'll try to get a new release 0.0.10 out as soon as possible.

53dd226ac4950efe4837fcd7cc7bb8e680db05bb
