### ISSUE TITLE
[Question] Chaos Guardians and Woot factories

### ISSUE THREAD

**Issue by UncertifiedDevice** [Ipsis/Woot#317]
An update recently came out for All The Mods 3. A kitchen sink modpack that features some late game balancing. In this new update they added Woot and when I opened the woot guide I noticed a profile was setup for the chaos guardian so I went to try and capture one but it just wouldn't work. More details in issue AllTheMods/ATM-3#418.

TL;DR Chaos guardians cannot be captured, and even when they are whitelisted in the config you can't capture them. Is this hardcoded or is there some problem with the [configs](https://www.dropbox.com/s/157kir1qylvraty/woot.zip?dl=0) in the pack?

**Comment by Ipsis** [comment]
Chaos Guardian don't die in a way that Woot can learn the loot, a bit like the Ender Dragon.
I've added custom code for the Ender Dragon but not the Chaos one. 
To prevent any issues I've internally disabled all Draconic mob.

**Comment by UncertifiedDevice** [comment]
Is it possible for you to add an option somewhere in the config with a huge disclaimer to disable this block? Or maybe detect when custom drops are specified in the custom_drops.json file for a particular mob and disable the block?

**Comment by UncertifiedDevice** [comment]
Just noticed this was already discussed in #246, closing...

**Comment by Ipsis** [comment]
Just out of interest, because I'm trying to decide if I want to support these in code.

I've got the Ender Dragon dropping 30/40/50/60 Draconium Dust and 1 Dragon Heart when Draconic Evolution is installed.
What else does the Chaos Guardian compared to the Ender Dragon?

**Comment by UncertifiedDevice** [comment]
Other than what the Ender Dragon drops the Chaos Guardian also guards a Chaos crystal. When you kill the Chaos Guardian you go to break this crystal to get Chaos Shards. Here's exactly how drops are set up for the Chaos Guardian in ATM3: 

- Chaos Shard size [1, 1, 1, 1] chance [10, 20, 30, 40] 
- Dragon Heart size [1, 1, 1, 1] chance [10, 20, 33, 66]
- Draconium Dust size [50, 50, 50, 100] chance [10, 15, 20, 25]

This is the how ATM3 has custom drops set up so there's a good chance some of this is balanced for the pack, if you wanted to know what you get when you break the chaos crystal in the world it drops 5 chaos shards. Additionally There is one thing that the Chaos Guardian doesn't drop that the Ender Dragon does and that is the Dragon Egg. Other than that the dragon heart and draconium dust drops should be the same as the Ender Dragon by default.
