### ISSUE TITLE
Server crashes after completion of woot mobfactory tier I

### ISSUE THREAD

**Issue by webbit2010** [Ipsis/Woot#318]
Minecraft: 1.12.2
Forge: 14.23.2.2613
Woot: 1.12.2-0.0.9

Crash log: https://pastebin.com/3JfuPSG0

When placing the factory heart, the server crashes and is no longer startable.

Entity used in the controller: thermalfoundation:blizz.

**Comment by Tearlow** [comment]
Just had the same occur on my end. Pointless with another log since it's the same issue just different forge version (14.23.2.2611). Used a vanilla cow in mine.

**Comment by Tearlow** [comment]
I really should look over the pull requests before writing anything.  Fix for the NPE was pushed yesterday so theirs a new version you can download to solve it. 0.0.10, should close/delete this report.

**Comment by Ipsis** [comment]
I made a silly error in 0.0.9.
0.0.10 is on Curseforge, but please let me know if it doesn't fix your issue.

**Comment by webbit2010** [comment]
Thanks for the quick response. it looks like it's working correctly now.
