### ISSUE TITLE
Not getting any loot from ender dragon

### ISSUE THREAD

**Issue by jkroepke** [Ipsis/Woot#325]
Hi!

Currently, I have the problem that the ender dragon factory does generate any loot.

The Spawing bar goes up, but there is no loot in the chest at the factory exporter.

No idea whats wrong.

At the factory importer there is a ME Interface contains 4 end crystal for the ingredients.

No Sponge is installed on the server.

**Comment by wamc2017** [comment]
Hmm, have you tried putting a chest there instead of an interface? Have you installed mass upgrades? If so you'll need 4 crystals for every dragon which is spawned...

**Comment by Ipsis** [comment]
As wamc2017 says a chest would be a good test, unless you have successfully used an ME interface before. The output and input device has to implement a specific Forge Java interface to be valid.

**Comment by jkroepke** [comment]
I‘ll try it! But on the Wither farm the interfaces are working fine.

You may add some warnings to the GUI, if something is missing. At this time
it is super hard to debug whats going wrong.

Am 26.02.2018 um 02:29 schrieb wamc2017 <notifications@github.com>:

Hmm, have you tried putting a chest there instead of an interface? Have you
installed mass upgrades? If so you'll need 4 crystals for every dragon
which is spawned...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ipsis/Woot/issues/325#issuecomment-368365724>, or mute
the thread

**Comment by jkroepke** [comment]
The output this a Simple chest without any additional attachments.

Am 26.02.2018 um 08:09 schrieb Ipsis <notifications@github.com>:

As wamc2017 says a chest would be a good test, unless you have successfully
used an ME interface before. The output device has to implement a specific
Forge Java interface to be valid.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ipsis/Woot/issues/325#issuecomment-368409454>, or mute
the thread

**Comment by Ipsis** [comment]
What does the gui say are the drops for the Dragon with your setup? 
I've got some debug logs you can enable if you have op access.

**Comment by jkroepke** [comment]
The factory was create some days ago, but I do not see any items in the export chest.

![GUI](https://user-images.githubusercontent.com/1560587/36677889-a096d516-1b0f-11e8-82de-146f9bf98953.jpeg)

I have ops access. But for the usability the warning should be in the GUI.

**Comment by Ipsis** [comment]
I can maybe check when the gui is opened and pass across a good/bad ingredients marker. 
At present I only check the ingredients at spawn time. 
So other factories have the same setup but different mobs and work fine, but only the dragon is an issue? 


I'll get you the dev debug to enable when I get home from work. That should tell us if it is an input or output problem.

**Comment by jkroepke** [comment]
Hum, I have only a wither factory. Other factories doesn't need any ingredients.

> but only the dragon is an issue?

Yes.

**Comment by wamc2017** [comment]
Hmm, are you providing 4 or 12 crystals? You're spawning 3 dragons at a time according the screenshot, so 12 crystals should be needed at spawning time...

**Comment by jkroepke** [comment]
Nope. I did‘t know that is required.

I wounder why the factory is running use energy but has not enough items to
run successfully.

Am 26.02.2018 um 18:37 schrieb wamc2017 <notifications@github.com>:

Hmm, are you providing 4 or 12 crystals? You're spawning 3 dragons at a
time according the screenshot, so 12 crystals should be needed at spawning
time...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ipsis/Woot/issues/325#issuecomment-368584087>, or mute
the thread

**Comment by wamc2017** [comment]
Also had that problem some time ago, but every dragon needs the crystals to spawn (should be the same with the wither... :smile: )

@Ipsis, maybe the factory should stop working if the amount of ingredients isn't the amount which is needed to spawn the mobs...

**Comment by Ipsis** [comment]
What I want to avoid is the overhead of checking the connected inventories to see if the items are available, as it can be quite expensive - relatively speaking.
What I'll do is change the gui, such that when it is opened it
* checks for valid input and output inventories/tanks and displays that information
* checks for the ingredients and indicate on the gui if the spawn will succeed

That may be the best way to give the information, but not cause constant checking.

**Comment by jkroepke** [comment]
Finally. I test it with 12 crystals with me interface and it work fine.

But I think its still an issue that the factory is not telling whats wrong.

Just an idea:

Instead check attached storage at the factory importer, add a inventory to the factory. (for example an input and a output inventory like the farm from forestry.

Why?

In the minecraft universe, all machine works fine with pipe or buses. Most of users try to push items in to block. But in the world of woot, you have to add a chest sided from the factory importer. Thats one of some points, why this mods feels so complicated. But it's just my opinion.

**Comment by wamc2017** [comment]
Hmm, I don't think the factory needs an extra inventory, the importer works like an importer from another mod and it's easier with vanilla methods to indicate how full an external inventory is. How the importer and exporter are handled are good documented in the ingame guide...

Maybe the mass upgrade in the guide needs some mentioning that the amount of ingredients is increased for mobs like the ender dragon/wither/chaos guardian? :smile:

**Comment by Ipsis** [comment]
The reason why I don't use internal inventories is that would have forced a gui which I was avoiding at the start. The gui I did eventually add is info only which I'm okay with.
So I will do something to help with indicating lack of ingredients but it won't be internal inventories and internal tanks. 
I thought the manual mentioned somewhere about ingredients per mob but I could well be wrong.

**Comment by jkroepke** [comment]
>  the importer works like an importer from another mod 

Not correct. The ME Interface works like a vanilla Chest.

Users ask me how I get items into the factory because Pipes didn't attach. (And nobody read books ;))

**Comment by wamc2017** [comment]
> Not correct. The ME **Interface** works like a vanilla Chest.

I talked about importers not interfaces... :smile:

> (And nobody read books ;))

... (rtfm?) :smile:
But seriously, modded minecraft always needed some information gathering, if people don't use the tools like wikis or ingame guides, it is not the authors fault...

**Comment by jkroepke** [comment]
RTFM. Yeah. I do it. But is isn‘t probably the real world. :-( I want to
try to push the usability of woot.

I mean this mod has huge potential. It does some stuff which is essential
for playijg minecraft and resolve it in a very server friendly way.

Anyway. This discussion is maybe unrelated to the initial issue and should
splitt into a separate topic/issue.


Am 27.02.2018 um 09:54 schrieb wamc2017 <notifications@github.com>:

Not correct. The ME *Interface* works like a vanilla Chest.

I talked about importers not interfaces... 😄

(And nobody read books ;))

... (rftm?) 😄

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ipsis/Woot/issues/325#issuecomment-368792134>, or mute
the thread

**Comment by Ipsis** [comment]
I've created a new bug #326 to handle my changes for missing ingredients notifications to the user. 

So the resolution of this issue for future reference was that multiple mobs where being spawned and not enough ingredients had been provided for all the mobs. Therefore no drops where generated.
