### ISSUE TITLE
XP Shard Stack consumption while Sneaking wont Work

### ISSUE THREAD

**Issue by Thalaan** [Ipsis/Woot#329]
Hello,
The tooltip of XP Shard says consumption while sneaking the entire stack at once.
But it does not.

**Comment by Ipsis** [comment]
That should work. It seems I've not added any code to implement it for 1.12 :(
I'll get that fixed up for the next release.

Just for my reference - this was in 1.10, but somehow the code has vanished for all other release.
https://github.com/Ipsis/Woot/commit/599dd49ea0cc0b76388c8004971944d9db7144e8
Port the code over into 1.12.

**Comment by Ipsis** [comment]
Fixed - thanks for reporting that.

**Comment by brisingraerowing** [comment]
I just noticed this myself. At least it's fixed. It's a bit annoying when you've accidentally left a factory running for a few hours and got around 60,000 XP Shards and want to turn them into Fluid XP.
