### ISSUE TITLE
How to build a Tier 5 Factory

### ISSUE THREAD

**Issue by Bajanxd** [Ipsis/Woot#330]
Please show how it is built and how to enable stuff

**Comment by Ipsis** [comment]
Tier 5 is a proposed tier for future development.
It is not currently available in any public release. 
Please see #285

**Comment by Bajanxd** [comment]
Thanks cuz got any ideas on when it could be released?

**Comment by Ipsis** [comment]
Tier V is a bit of a low priority just now, so it will not be for a while.
Is there something you want Tier V for?
It doesn't bring in any new functionality that cannot be done with the current configs.
