### ISSUE TITLE
Evilcraft Support?

### ISSUE THREAD

**Issue by Zenzar84** [Ipsis/Woot#333]
Hello there, is there any thought's on adding Evilcraft support, like upgrades for woot? would be neat to see upgrades so it makes Blood instead of XP in the farms =)

**Comment by Ipsis** [comment]
It is something I'm considering along with BloodMagic support. I just need to learn a bit about EvilCraft to see how useful the addition would be.

**Comment by Ipsis** [comment]
So the upgrade will produce Blood directly into export tanks and the HP will depend on the mob that you have in the factory.

EvilCraft Blood Tank I Upgrade = 20mb per HP
EvilCraft Blood Tank II Upgrade = 40mb per HP
EvilCraft Blood Tank III Upgrade = 60mb per HP

**Comment by Zenzar84** [comment]
That is awesome news mate :D, Well done on your work on Woot , love it :)

**Comment by Ipsis** [comment]
44aa5cce54d47487f37a9f4542b7d717f50bb0ca
