### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by MelanX** [Ipsis/Woot#334]
I downloaded Guide API here: https://minecraft.curseforge.com/projects/guide-api/files/2466858
But I cannot craft the guide and cannot open the Guide. I don't know why. Do you have any idea? 

Woot: 1.0.0
Guide API: 2.1.4-57
Forge: 14.23.1.2601

**Comment by Ipsis** [comment]
The guide is provided under the Guide-API mod in jei.
If you search for "Woot Guide" then you should see the correct recipe of book and zombie flesh.

**Comment by MelanX** [comment]
Thank you! I tought the "Readme" will turn into Woot Guide when Guide API is added.
Maybe you should add this information to curse description. Unless I'm the only stupid guy :D Thank you very much :)
