### ISSUE TITLE
[1.12.2] woot cannot load factory loot form loot.json on existing server world

### ISSUE THREAD

**Issue by Morpheus1101** [Ipsis/Woot#336]
Going through the log for the server, it had an error saying that it was unable to load load factory loot form the loot.json file .. Since this is a long standing world used for quite a while, i found this odd and not entirely sure if its just some random thing to ignore or a bug.

Brief snippet of the log @ https://gist.github.com/Morpheus1101/a1650d106e104d53eb2fd545d0b87cfc

Entire log is 4k+ lines, but can provide if needed

**Comment by Ipsis** [comment]
Going from the log is doesn't seem to have a problem with the file contents, more that is cannot find it.

 C:\Users\Morpheus1101\Downloads\Servers\MMD-Public-UpdateTest\woot\loot.json
(The system cannot find the path specified)

The only time I've ever seen that was when I created a new instance and then it would generate one for me. But if you have been running for a while that wont be the case.

Could you look at the file to see what the contents are?
It would interesting to see if it looks "new" and not have the same amount of information that you would expect for a long term world.

**Comment by Morpheus1101** [comment]
The contents look quite odd tome at least, below is all it contains.

Forge *.2631
Woot v1.0.1

{"version":1,"mobs":[{"mobName":"minecraft:chicken","samples":[0,0,0,9]}],"drops":[{"drop":{"item":"minecraft:feather"},"mobs":[{"mobName":"minecraft:chicken","sizes":[{"count":1,"looting":3,"samples":2},{"count":2,"looting":3,"samples":3},{"count":3,"looting":3,"samples":4}]}]},{"drop":{"item":"minecraft:chicken"},"mobs":[{"mobName":"minecraft:chicken","sizes":[{"count":1,"looting":3,"samples":1},{"count":2,"looting":3,"samples":2},{"count":3,"looting":3,"samples":4},{"count":4,"looting":3,"samples":2}]}]},{"drop":{"item":"actuallyadditions:item_solidified_experience"},"mobs":[{"mobName":"minecraft:chicken","sizes":[{"count":1,"looting":3,"samples":2},{"count":3,"looting":3,"samples":1},{"count":4,"looting":3,"samples":1}]}]},{"drop":{"item":"mysticalagriculture:crafting","data":0},"mobs":[{"mobName":"minecraft:chicken","sizes":[{"count":1,"looting":3,"samples":4}]}]}]}

**Comment by Ipsis** [comment]
That looks a lot like the original loot.json was lost/corrupt/failed to save etc and the code could not find it, hence the file not found.
Now you have a blank one and so far the only farms on your server that are running are for chickens. 
It will relearn the other drops as people run their other mob farms. 

How the original file was lost, I'm not sure. If it failed to write when the server was stopped then it would be in an older log file. Granted that is my best guess at present.

**Comment by Morpheus1101** [comment]
Not a big deal in that case.  Would it occur if running factories with mobs from a mod that had been removed ?

**Comment by Ipsis** [comment]
I don't think so as the items would just be ignored on boot when the file was read. I run with different mods installed during development and that seems to be fine.

So I'm not sure what has happened here. But hopefully it is a one-off and you don't see it again. 
I might see if there is any way to make the save a bit safer.
