### ISSUE TITLE
Factory is working but doesnt produce. 

### ISSUE THREAD

**Issue by Henrick866** [Ipsis/Woot#342]
I have built the factory a few days ago but it wont produce anything since then.
i play on the "Forever Stranded" modpack on minecraft 1.10.2, i built the factory (Tier 3, Endermen) as the layout block told me to, the factory formed, the learning process is completed but it wont produce anything at all, it doesnt even consume RF.  i made sure it was on one chunk (maybe that wont affect anything), there was nothing blocking at y=251 to y=255. i built it at y=68. i used an extension and a proxy to input RF and output items. everything is supposed to be working but it doesnt.

**Comment by Henrick866** [comment]
screenshots i took

overview
![2018-04-11_21 46 31](https://user-images.githubusercontent.com/32077188/38652096-7448ea04-3dd2-11e8-87fc-7d42907e2b41.png)

input/output
![2018-04-11_21 46 57](https://user-images.githubusercontent.com/32077188/38652097-7468c4b4-3dd2-11e8-98a2-62f5fcd0cebb.png)

the waila tooltip unsneaked
![2018-04-11_21 47 24](https://user-images.githubusercontent.com/32077188/38652098-7480c866-3dd2-11e8-95a0-8066fe7b4a04.png)

Waila tooltip sneaked
![2018-04-11_21 51 39](https://user-images.githubusercontent.com/32077188/38652150-9e8da49e-3dd2-11e8-923b-39b5a5399f1e.png)

**Comment by Ipsis** [comment]
As a quick test try putting a vanilla chest directly in front of the faced, main factory block.
The reason I say this is that you can only input/output from blocks that implement a specific Java interface, which things like the transfer node may not do. So a vanilla chest is the easy way to confirm that.

**Comment by Henrick866** [comment]
It's working, its slow (slower than i expected but its because i dont know how much long 420 ticks were), but its working! now ill hook the item conduits to the chest, but how about possible fluids? does EnderIO fluid conducts works?

**Comment by Ipsis** [comment]
Normally it has to be some sort of tank so it provides the correct interface in the code, do I would go with an ender IO tank or something similar. 
20 ticks = 1 second

**Comment by Henrick866** [comment]
Thank you. Its a great mod btw, i really like the non spawning mechanic
