### ISSUE TITLE
More Chaos Dragon Issues (Not Spawning)

### ISSUE THREAD

**Issue by FallenEagle1** [Ipsis/Woot#343]
New issue with the chaos dragon and getting it to spawn. More apt, the spawning system seems to just stop.

Modpack: ATM3 5.9.3
Forge: 14.23.2.2654
Woot: 1.0.1

This issue seems to be present in the ATM3 pack, but not when tested with just Draconic (and dependencies) and Woot.

When trying to spawn the chaos dragon with the farm, everything seems to be normal until the progress bar reaches 100%. It will reset to 0% but will stop there without continuing. Along with this, no items or fluids are consumed, and no drops are produced. This behavior is only with the chaos dragon, no other mobs seem to have issues. Also tested with a variety of upgrades, and no change. Currently nothing appears in the logs as the spawner is running. Not sure if it is something with the configs, so attaching them as well.

[WootConfig.zip](https://github.com/Ipsis/Woot/files/1922389/WootConfig.zip)

I was planning on testing with the exact same configs with just DE, Woot, Thermal Expansion (for the liquids) and ATM tweaks (for growth essence) but running out of time tonight. If you want me to test that, just let me know, would be happy to help.

**Comment by Ipsis** [comment]
Think this is related to the issue of very high power requirements, which I've fixed and will be in the next release. I'll retest with your config file. 
Next release will be out in the next few days. 
#335

**Comment by Ipsis** [comment]
Just retested with your config files and they seem to be fine with the changes I've made.

**Comment by Ipsis** [comment]
1.1.0 release has bee made.
Should be available on CurseForge once they approve it.
