### ISSUE TITLE
[Question] Woot Folder in Main Modpack Folder

### ISSUE THREAD

**Issue by KAfable** [Ipsis/Woot#344]
I browsed through the Wiki and didn't see anything relating to the woot folder in the main modpack directory. Mind if I ask what it's for / why is it separate from the configs folder? 

I'm mostly asking out of curiosity because I'm working on a modpack with others and on the initial commit, I was only going to send out the confgs/mods/resources/scripts folders, and needed to know if this folder was vital or not.

**Comment by Ipsis** [comment]
The woot folder outside of config is where I store the learned drops.
So it is not part of the configuration, but generated as the game is played.

**Comment by KAfable** [comment]
Thank you!
