### ISSUE TITLE
[1.12.2] Decapitate Upgrades not registering

### ISSUE THREAD

**Issue by Drethic** [Ipsis/Woot#345]
Version: 1.12.2-1.1.0
Forge: 14.23.3.2669
Crash Log: N/A

I built a Tier I skeleton grinder and when I added the Decapitate I upgrade the head percentage did not change from 3%.  To test further, I upgrade to Tier II, Tier III, and Tier IV and even added the Decapitate II and Decapitate III upgrades on top.  At the highest tier with all 3 upgrades it still only shows a 3% head drop rate.  I'm not sure if this is a UI or Backend issue.

Here are screenshots of the setup:
https://imgur.com/a/lqOicyh

Please let me know if you need any other details.

**Comment by Ipsis** [comment]
The display in the gui is the learned drop rate and I don't update it when decapitate upgrades are in place.
So the decapitate upgrade is changing the drop rate,  but the gui won't show it. 

I'll look at getting the gui value updated as well.

**Comment by Ipsis** [comment]
No Decapitate
![2018-05-02_14 10 11](https://user-images.githubusercontent.com/5602759/39525004-b014cc38-4e12-11e8-9fcb-9d2259086d43.png)

Decapitate I
![2018-05-02_14 10 18](https://user-images.githubusercontent.com/5602759/39525008-b22e048a-4e12-11e8-8c50-ea47801eac01.png)

Decapitate II
![2018-05-02_14 10 25](https://user-images.githubusercontent.com/5602759/39525011-b425d92a-4e12-11e8-936f-ea84414fda95.png)

Decapitate III
![2018-05-02_14 10 32](https://user-images.githubusercontent.com/5602759/39525014-b62bfd58-4e12-11e8-99f2-b6fa51a36bbf.png)
