### ISSUE TITLE
Crash with latest update to Woot. Blood Magic Ritual?

### ISSUE THREAD

**Issue by RussianSanity** [Ipsis/Woot#350]
https://pastebin.com/0aYEt4kN
It says something about Blood Magic in the crashlog, but we do not have that mod on our modpack.
If you need more than that posted in the pastebin, please let me know.
We are running sponge on this server.

**Comment by forestbat** [comment]
https://gist.github.com/forestbat/1f8d89e052460debabda5c55ae9106f4
I also met the problem。

**Comment by Ipsis** [comment]
For some reason it is still trying to pull in some BloodMagic code, when it is not installed.
I can replicate this and I'll try to work out what I've done wrong.

**Comment by Ipsis** [comment]
6f6168ac5bdc0b7a32d0dce038ea154273a3f92a
I've released 1.12.2-1.2.1 which includes this fix, which I test with and without BloodMagic.
So fingers crossed this fixes it for you.
