### ISSUE TITLE
Please add a way that XPshard can be turned into the XPFluid in Thermal Foundation

### ISSUE THREAD

**Issue by Uptobillion** [Ipsis/Woot#351]
![2018-05-03_20 36 42](https://user-images.githubusercontent.com/28522459/39576893-4c58966a-4f12-11e8-9440-5cd96d960e33.png)

**Comment by Ipsis** [comment]
I've added an EnderIO shard->Xp Juice recipe for the Vat.
I'm investigation Thermal to find out have to do the same for the Xp fluid that is supports.

**Comment by Ipsis** [comment]
Crucible recipe for XpShard -> Thermal XP fluid

![2018-05-03_21 20 37](https://user-images.githubusercontent.com/5602759/39600907-21c1cc9a-4f18-11e8-820d-f24b85ec072d.png)

**Comment by Ipsis** [comment]
e2d1ea1258d554997468f53f3eb171f4cfb040b0
