### ISSUE TITLE
Endermen not dropping heads with EnderIO installed

### ISSUE THREAD

**Issue by UntoldForce** [Ipsis/Woot#357]
Hey all, I'm running Minecraft 1.12.2 with Woot 1.2.1 and EnderIO 5.0.24. I have a tier 4 altar with the decapitation I, II, and III upgrades. I let it run all night and there were no endermen heads. I managed to get 300k ender pearls so I know it's working properly, but I believe there is something wrong with the endermen head drop. If I look at the factory and hold shift JEI doesn't show the head as a possible drop either.

Here's the full mod list with versions. There could be some issue with other mod interactions?

Mod Name | Current Version
-- | --
/dank/null by TheRealp455w0rd - Granted | 1.4.33
Actually Additions | r134
Actually Baubles by Jacky1356400 - Granted | 1.1
Advanced Chimneys | 3.2.1.2-build0079
Advanced Hook Launchers | 3.1.2.1-build0071
Advanced Rocketry by zmaster587 - Granted | 1.4.0-80
AE2 Stuff by bdew | 0.7.0.4
Agricraft | 2.12.0-a4
Akashic Tome by Vazkii | 1.2-10
AppleSkin by squeek502 | 1.0.9
Applied Energistics by AlgorithmX2 | rv-5-stable-11
ArchitectureCraft by Greg Ewing | 2.68
Aroma1997Core by Aroma1997 - Granted | 1.3.0.2
Aroma1997s Dimensional World by Aroma1997 | 1.3.0.2
Astral Sorcery by HellFirePvP, Redcreeper63502 | 1.8.10
AutoRegLib by Vazkii | 1.3-17
B.A.S.E by SkySom | 3.7.1
Bad Wither No Cookie - Reloaded by Kreezxil | 2.12
Baubles by Azanor | 1.52
Bdlib by bdew | 1.14.3.12
Bed Patch by Mordenkainen3141 - Granted | 2.2
Better Advancements by Way2muchnoise | 0.0.5.17
Better Builder's Wands by portablejim | 0.11.1.245
BiblioCraft by Nuchaz | 2.4.3
Binnie's Mods by Binnie | 2.5.0.165
Biomes O Plenty | 7.0.1.2387
Blockcraftery by elucent - Granted | 0.1.3
Blood Magic | 2.2.12-97
Bookshelf by Epoxide | 2.3.544
Botania by Vazkii | r1.10-354
Brandon's Core by brandon3055 | 2.4.2.157
Career Bees by RWTema - Granted | 0.4.0
Ceramics | 1.3.4
Chameleon by jaquadro | 4.1.3
Chest Transporter by CubeX2 | 2.8.8
Chisel 2 by warlordjones, tterrag1098, TheCricket26, Drullkus | 0.2.0.31
Chisels and Bits by AlgorithmX2 | 14.16
Clumps by jaredlll08 | 3.0.0
CodeChickenLib by Chickenbones | 3.1.8.341
CoFH Core by TeamCoFH | 4.4.1.12
CoFH World by TeamCoFH | 1.1.1.12
Colored Lights by Razzokk | 1.1.1
Comforts by TheIllusiveC4 - Granted | 1.1.1
Compact Solars by cpw, progwml6 | 5.0.17.340
Compacter by bdew | 1.3.0.3
CompactMachines by Davenonymous | 3.0.11-b207
ConnectedTexturesMod by tterrag1098, Minecreatr | 0.2.3.12
Controlling by jaredlll08 | 3.0.6
Cooking for Blockheads by BlayTheNinth | 6.3.26
Cosmetic Armor Reworked | 1.12.2-v1
CraftTweaker by jaredlll08 | 4.1.8
Custom Main Menu by Lumien | 2.0.8
Dark Utilities by Darkhax | 1.8.208
DecoCraft2 | 2.6.0
Deep Resonance by McJty | 1.6.0
Default Options by Blay the Ninth | 9.2.7
Diet Hoppers by RWTema - Granted | 1.1
Dirt2Path by marwat208 - Granted | 1.7.0
Draconic Evolution by brandon3055 | 2.3.11.290
Dynamic Trees | 0.7.7c
Dynamic Trees BOP | 1.1b
ElecCore \| DimensionAPI by Elec332 | 1.8.434
EluLib by elucent - Granted | 0.1.12
Embers by elucent | 0.230
Ender Compass | 1.2.6.1
Ender Core | 0.5.22
Ender Zoo | 1.4.0.49
EnderIO | 5.0.24
EnderStorage by Chickenbones | 2.4.2.126
Engineers Workshop by EwyBoy, JorVa | 1.0.6.31
Enviromental Tech by ValkyrieofNight | 2.0.9c
ET Lunar by ValkyrieofNight | 2.0.9a
Exchangers by Jacky1356400 | 2.7.2
Extra Bit Manipulation | 3.2.1
Extra Cells by Leonelf | 2.5.13
Extra Utilities by RWTema | 1.7.6
Extreme Reactors by ZeroNoRyouki | 0.4.5.48
Fairy Lights | 2.1.2
Farming for Blockheads | 3.1.12
Fence Jumper by TheRealp455w0rd - Granted | 1.0.3
Flat Colored Blocks by AlgorithmX2 | 6.6
Flux Networks by Ollie_Lansdell | 3.0.8
FoamFix by asiekierka | 0.9.9.1 Anarchy
Forestry by SirSengir | 5.8.0.285
Forge Endertech | 1-4.3.2.0-build.0088
FTBLib | 5.0.2.11
FTBUtilities | 5.0.2.11
Gadgetry: Core by elucent - Granted | 0.2.0
Gadgetry: Machines by elucent - Granted | 0.2.1
Gendustry by bdew | 1.6.5.8
GraveStone Mod by EuhDawson | 1.10.1
Guide-API by TehNut, Tombenpotter | 2.1.5-60
Hammer Core | 1.9.9.5.9
HarvestCraft by MatrexsVigil, Rhodox | 1.12.2t
Immersive Engineering by BluSunrize | 0.12 - 82
Immersive Petroleum by Flaxbeard | 1.1.9
Industrial Foregoing by Buuz135 | 1.9.0-163
IndustrialCraft 2 by IC2 Dev Team | 2.8.76-ex112
InfinityLib | 1.12.0
Inventory Pets | 1.4.9.9b
Inventory Tweaks by Kobata | 1.63
Iron Backpacks by gr8pefish | 3.0.7-10
IronChests by cpw, progwml6 | 7.0.42.827
IVtoolkit | 1.3.3
JEI Bees by bdew | 0.9.0.5
JEI Integration by SnowShock35 - Granted |  
JourneyMap by techbrew | 5.5.2
Just Enough HarvestCraft by mrAppleXZ - Granted | 1.5.1
Just Enough Items (JEI) by Mezz | 4.9.1.175
Just Enough Resources (JER) by Way2muchnoise | 0.8.5.27
KleeSlabs by BlayTheNinth | 5.4.9
LibVulpes by zmaster587 - Granted | 0.2.8-31-UNSTABLE
Light Level Overlay by oldjunyi | 1.1.4
Long Fall Boots by NanoHeart, Xbony2 - Granted | 1.2.1a
Magic Bees by MysteriousAges | 3.1.9
Malisis Core by Ordinastie | 6.4.0
Malisis Doors by Ordinastie | 7.3.0
Mantle by mDiyo, progwml6 | 1.3.2.24
McJtyLib by McJty | 2.6.7
MCMultiPart by amadornes | 2.5.1
MineTogether by Creeperhost, CloudyPSP - Granted | 1.8.7
Mob Grinding Utils by Vadis365, Darkosto, TheCyberBrick - Granted | 0.3.6
Mod Name Tooltip by Mezz | 1.10.0
Modern Lights by acnessdev | 1.0.3
ModTweaker by jaredlll08, joshie, SpitefulFox | 4.0.12
Morph-o-Tool by Vazkii | 1.2-16
Morpheus by quetzi | 3.3.2
Mouse Tweaks by YaLTeR97 | 2.8
MTLib by jaredlll08 | 3.0.4
Natura by mDiyo | 4.3.2.49
Nature's Compass by ChaosTheDude | 1.5.1
Nether Portal Fix by BlayTheNinth | 5.3.13
Not Enough Wands by romelo333 | 1.6.1
NotEnoughIDs by fewizz | 1.5.4.2
NuclearCraft by Grim3212, nosedive42 | 2.10m
OMLib | 3.0.0-143
Open Modular Turrets | 3.0.0-247
OpenBlocks Elevator by VsnGamer | 1.3.6
OpenComputers by Sangar | 1.7.2.67
Optifine | HD_U_D1
P455w0rds Library by TheRealp455w0rd | 2.0.29
Placeable Items | 3.3
Placebo by ShadowsOfFire - Granted | 1.3.4
Platforms by ShetiPhian | 1.4.5
Psi | r1.1-59
PTRlib | 1.0.2
Quark by Vazkii | r1.4-123
Quick Leaf Decay by Lumien | 1.2.4
Ranged Pumps by raoulvdberge | 0.5
ReAuth by TechnicianLP | 3.5.2
Reborn Core by Gigabit1011, modmuss50 | 3.8.1.271
Recurrent Complex | 1.4.7
Redstone Arsenal by CoFH team | 2.4.2.9
Redstone Flux by TeamCoFH | 2.0.1.2
Reliquary by TrainerGuy22, x3n0ph0b3 | 1.3.4.760
Resource Loader by Lumien | 1.5.3
RFTools by McJty | 7.33
RFTools Control by McJty | 1.8.1
RFTools Dimensions | 5.53
Roots by elucent | 0.104
Rustic by Thatguy3039 | 1.0.4
Scannable | 1.6.3.17
Secret Rooms by AbrarSyed | 5.6.3
Shadowfacts' Forgelin by Shadowfacts | 1.6.0
Shetiphian Core by ShetiPhian | 3.5.6
Signals by MineMaarten - Granted | 1.3.2-11
Simple Void World by modmuss50 | 1.2.0.9
Simply Jetpacks 2 | 2.2.4.34
Snad by TheRoBrit | 1.7.09.16a
Solar Flux Reborn | 3.50r
SonarCore by Ollie_Lansdell | 5.0.9
Soul Shards: The Old Ways by SgtPunishment | 2.7.6-56
Steve's Carts 2 by Vswe | 2.4.18.92
Storage Drawers by jaquadro | 5.3.6
Storage Drawers: Misc Pack by jaquadro | 3.1.0
Tesla Core Lib by Face_of_Cat | 1.0.14.10
Thaumcraft | 6.1BETA13
The Lost Cities by McJty - Granted | 2.0.7
The One Probe by McJty | 1.4.22
Thermal Cultivation by TeamCoFH | 0.2.0.6
Thermal Dynamics by TeamCoFH | 2.4.1.10
Thermal Expansion by TeamCoFH | 5.4.2.27
Thermal Foundation by TeamCoFH | 2.4.1.15
Thut's Elevators by patnevis | 6.0.16
ThutCore by patnevis | 5.16.3
Tick Profiler | 0.0.4
Tinker I/O | 2.6.1
Tinker's Construct by boni, mDiyo | 2.9.1.65
Tinkers' Tool Leveling by boni | 1.0.4
TipTheScales by jaredlll08 - Granted | 1.0.1
TOP Addons by DrMathiasDJ | 1.6.0
TorchMaster by xalcon | 1.6.3.58
Traverse by ProfessorProspector - Granted | 1.5.3
Twilight Forest | 3.6.345
UniDict by WanionCane | 2.5b
ValkyrieLib by ValkyrieofNight | 2.0.9b
WanionLib by WanionCane | 1.5
Waystones by BlayTheNinth | 4.0.43
Whoosh | 0.1.10.1
Wireless Crafting Terminal by TheRealp455w0rd | 3.9.64
Woot | 1.2.1
XNet by McJty | 1.6.9
xNICEx by McJty, xVipstarx - Granted | 0.2.0
Xtones by TehNut, Original_Dutch | 1.0.8-11
YABBA by LatvianModder | 1.1.2.6
Zero CORE by ZeroNoRyouki | 0.1.2.1

**Comment by Ipsis** [comment]
I'm probably not adding the correct EnderIO skull item from when I ported from 1.11->1.12.

Item i = Item.getByNameOrId("EnderIO:blockEndermanSkull");

That should probably be "enderio:blockEndermanSkull"

(You get a +1 for the nicely formatted modlist!)

**Comment by Ipsis** [comment]
7c430301a1d95cfe0af2a7c63cc1e01f1a9f5d41

![2018-05-12_12 09 50](https://user-images.githubusercontent.com/5602759/39956723-05355908-55de-11e8-84f8-06f50f566d85.png)
