### ISSUE TITLE
Minecraft 1.12.2 Factory Heart power bug

### ISSUE THREAD

**Issue by Realever** [Ipsis/Woot#362]
Hi,
i have a "bug" with the factory heart.After the server restart the factory heart is not conecting to the power cable and i must replace it new.i have test it with the energy conduit from ender io and from flux networks.

Mod version: woot-1.12.2-1.2.1
forge version: 1.12.2-forge1.12.2-14.23.3.2698

**Comment by Ipsis** [comment]
It think this is an issue that has come up before.
Although the power cables will connect directly to the factory heart they are not supposed to, it was a bug. But people are using it that way, so I'm having to leave it in.

The cables are supposed to connect to the power cell under the factory and can be connected to multiple sides of the cell.
Those connections should be refreshed on server start, whereas the ones connected to the heart are not refreshed.

Could you try connecting directly to the power cell and see if that fixes your issue?

**Comment by Realever** [comment]
i have a stupid question.How can i connect direct to the power cell when there are factory flash casting all around is and under the power cell factory importer is? this is my first time i used your mod sorry for the newbie question 

edit: oh i can with with one block diference place the other 3 blocks.i was thinking that i place the power cell directly to the factory heart

edit 2: no it doesn´t work.after the server start the power cell is direct to 0 fe. i have connect the flux point from flux networks

**Comment by Ipsis** [comment]
The factory comes in two parts.
The first is the big structure with the heart.
The second is the column containing the importer, exporter and power cell. This structure has to be located underneath the heart block but can be up to 10(?) blocks underneath it. There is more informaton in the Woot manual regarding the specifics.

When you use the power cell connections, do you have the problem with both EnderIO and Flux Network connections?

**Comment by Realever** [comment]
After you say that with  with the underneath i have read the book again and then i have see it there too ^^.When i direct connect the flux plug to the power cell and restart the server the power cell is empty.But when i conncet a ender io cable to the power cell and restart the server then have that power.

thanks for the help
