### ISSUE TITLE
1.12.2 Texture Visibility 

### ISSUE THREAD

**Issue by DarkestDreams24** [Ipsis/Woot#363]
Not sure if im the only one... But I can't for the life of me put the new multiblock together. Even tried to in creative mode. With something that complicated either the blocks have to be more distinct looking (points at blood magic) or have an assembler tool that does it for you (Environmental Tech)The blocks are too similar looking and dont give any indication of being in the right place. The old multiblock structure was much easier put together. Its honestly bad for my server since everyone is instead now having to use Soul Shard spawners causing server lag.

**Comment by Ipsis** [comment]
I've added a build tool (The Intern) that will build the factory for you, which will be in the new version.
This acts in the same way as the ritual diviner from Blood Magic and will allow building from scratch and upgrading existing factories. #352 

There have been a few comments regarding the texture color, which I don't see but I do appreciate that others have issues. I might try and revisit these to see if I can add some extra differentiation there as well.

**Comment by DarkestDreams24** [comment]
Thankyou, it is very much helpful. Its just each time I would try to build it I would end up with 2 or 3 of each block type and have no clue where they would go considering I would turn off the preview and still not have any idea where the missing block would be. Tried both building from t1-4 and from working from the outside to no avail. As for whats causing the issue per person im not sure.
