### ISSUE TITLE
1.12.2 no drops for the Chaos Guardian

### ISSUE THREAD

**Issue by jusitnboggs** [Ipsis/Woot#364]
I'm not getting any drops for this mob all the other mobs I have used get drops just fine.

**Comment by Ipsis** [comment]
Both the Chaos Guardian and the Ender Dragon  require you to feed the factory with specific items.
If you open up the gui you should see a list showing what you need.
I think, by default, it requires an Awakened Core, per Chaos Guardian.

If you are playing a modpack, then the author may have changed those ingredients, but those changes are shown in the gui.

**Comment by jusitnboggs** [comment]
the gui shows nothing for the Chaos Guardian for needed items either

**Comment by Ipsis** [comment]
Which mod pack are your using?
Can you show me the contents of the file "config/woot/factory_ingredients.json"
A screenshot of the gui would also help, just to see if I spot anything wrong there.

**Comment by jusitnboggs** [comment]
I am also using version 1.12.2-1.2.1
![2018-05-27_20 28 56](https://user-images.githubusercontent.com/2986451/40595965-bb6c9ab4-61ec-11e8-9de1-b204d9fad821.png)


`{
  "version": 1,
  "ingredients": [
    {
      "mobName": "minecraft:wither",
      "items": [
        {
          "item": "minecraft:soul_sand",
          "count": 4
        },
        {
          "item": "minecraft:skull",
          "data": 1,
          "count": 3
        }
      ],
      "fluids": []
    },
    {
      "mobName": "minecraft:ender_dragon",
      "items": [
        {
          "item": "minecraft:end_crystal",
          "count": 4
        }
      ],
      "fluids": []
    }
  ]
}`

**Comment by Ipsis** [comment]
The ingredients have been removed from that file, but that is fine.
The gui should show the hardcoded drops in the drops section, but it doesn't. 
That suggests a modification to custom_drops.json has caused it to fail to load.

Best way to confirm this is to show me the config/woot/custom_drops.json.
Basically syntax errors in the config files can really screw things up as the file will stop processing. 
It might be worth putting your log file on pastebin and I'll check if you have any errors there that could this or any other issues.

**Comment by jusitnboggs** [comment]
custom_drops
https://pastebin.com/F0fKLY4c

[latest.txt](https://github.com/Ipsis/Woot/files/2044053/latest.txt)
[debug.txt](https://github.com/Ipsis/Woot/files/2044054/debug.txt)

the log files were too big for pastebin so I uploaded the files.

I don't think I have edit custom_drops.json

should I del the configs and let them regen?

**Comment by Ipsis** [comment]
The answer is easy. The custom_drops.json does not have the Chaos Guardian drops.
The question would be why. 
If this is someone else's mod pack then they might have removed them for the Chaos Guardian. 

Woot ships by default 1.12.2-1.2.1 with it filled in.

You could delete the file and reload, that should regen it.

**Comment by jusitnboggs** [comment]
ok I build the pack so idk why it isn't in there lol

**Comment by jusitnboggs** [comment]
it seems to be working now thanks
