### ISSUE TITLE
Adding Meta Information to Custom Drops... How to?

### ISSUE THREAD

**Issue by PegasusRider** [Ipsis/Woot#367]
I'm using Silent's Gems (unggghhh) and Mystical Agradditions, both of which add unique drops to the Ender Dragon. Because that particular mob is pre-programed, getting the drops on the farm has become a question for me... They both use a single item name for drops across a bevy of situations, and alter the Meta data to narrow down which item they actually intend. /sigh

So, the examples you give are great as far as they go, but can you enlighten me on the "Meta" portion? These drops are picked up fine on learned mobs, so its not an NBT issue (like Silent's Gems weapons, gah what a mess!)

Thanks!

Edit: I was mistaken, the Silent's Gems drops are NBT based, yet they are nabbed on learned mobs. I'm confused. Ah well. The others are still related to Metadata values. LOL

**Comment by wamc2017** [comment]
Hmm, I guess you have to define the data tag...

Haven't tested it myself, but it should look like this (in this example the mob should drop a red tulip...)

```
	{
          "drop": {
            "item": "minecraft:red_flower",
	    "data": 4
          },
          "sizes": [ 1, 1, 1, 1 ],
          "chances": [ 1, 1, 1, 1 ]
        },
```

**Comment by PegasusRider** [comment]
Well, alrighty then. In my favorite saying's style...

"That was easy!"

Thanks @wamc2017!
