### ISSUE TITLE
[1.12.2] [1.3.0] Crash with newest Blood Magic version

### ISSUE THREAD

**Issue by wamc2017** [Ipsis/Woot#369]
Hi,

the newest Blood Magic version (1.12.2-2.3.0-98) made some changes to register rituals.

Crash report, in case you need it: https://gist.github.com/wamc2017/6bc44b942c2091f2d54d9bf79f8d82f6

I guess that's the commit, with the changes made in Blood Magic: https://github.com/WayofTime/BloodMagic/commit/42c69eb5571b1b7c0f8e222bcee87f4b41c32257

Thanks for looking into it.

Kind regards,
wamc

**Comment by Pythonic-Rainbow** [comment]
confirmed

**Comment by ghost** [comment]
Just ran into this aswell

**Comment by Ipsis** [comment]
I got away with no changes in BloodMagic this for quite some time :)
I'll update and roll a new version out in a few days.

**Comment by Pythonic-Rainbow** [comment]
Well I guess https://github.com/Ipsis/Woot/commit/fde95586ee228ba48271b0d3811229127952ae63 solves this issue?

**Comment by Ipsis** [comment]
Yes and no.
The commit was enough for me to run and see that the rituals were selectable via the divining rod. However I still need to ensure that each ritual performs correctly.

One thing that will be missing - and I don't know if anyone used it - will be the ability to disable any of the three rituals.

**Comment by Ipsis** [comment]
- [x] Test altar ritual
- [x] Test tank ritual
- [x] Test crystal growth ritual

1.12.2-1.4.0 uploaded to Curse and awaiting their approval.
Hopefully nothing broke - even though I tested it :)

**Comment by TehNut** [comment]
>One thing that will be missing - and I don't know if anyone used it - will be the ability to disable any of the three rituals.

@Ipsis Ritual configs are handled in-house now and can be found in `rituals.cfg` or in the rituals category of the in-game config.

**Comment by Ipsis** [comment]
@TehNut Thanks for that. I'll stop trying to work it out now :)
