### ISSUE TITLE
[1.12.2] Game crash when initizlizing game due to Blood Magic update.

### ISSUE THREAD

**Issue by RyanP1991** [Ipsis/Woot#370]
Hello, so just updated to the latest version of Blood Magic - Version 1.12.2 - 2.3.0-98 and when launching the game it crashes due to an exception from Woot, Caused by: java.lang.NoClassDefFoundError: WayofTime/bloodmagic/ritual/RitualRegistry . 

Attachted is a copy of the crash log:

https://pastebin.com/yWWBYghq

**Comment by Ipsis** [comment]
https://github.com/Ipsis/Woot/issues/369
Just closed it about 3 minutes ago :)
I'm building the new release now so should be available within the next day.
It will be fixed in version 1.12.2-1.4.0 (waiting for Curse to approve it)

**Comment by RyanP1991** [comment]
Damn Ipsis, you work fast :)

**Comment by Ipsis** [comment]
I aim to please - if it is an easy fix :)
Just let me know if you run into any problems with it.
