### ISSUE TITLE
1.10.2 Tier 4 mob factory causing massive lag in SSP

### ISSUE THREAD

**Issue by inviktus** [Ipsis/Woot#374]
So I just got my tier 4 mob factory up and running, immediately noticing significant lag after powering it up. I get a notification at the top of the screen that says "waiting for server" and any action that happens during this time will rubber band, IE if I move to a different spot, move items around in my inventory, take something out of an inventory.

The FTB console shows this:
[16:56:32] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 11273ms behind, skipping 225 tick(s)
over and over and over.

Likely this has already been patched, I'm stuck on 1.10.2 due to my choice of modpack. Perhaps there's a later release of woot for 1.10.2 that resolves this?

My game runs smooth as butter right up till I switch on ther spawner.
Specs:

i7 7700k
GTX 1080
32gB ram
m.2 SSD

**Comment by Ipsis** [comment]
Not a problem I've seen before, so alas no recent version for 1.10.2 will fix it.
Which modpack are you running?

**Comment by inviktus** [comment]
FTB Beyond would be the modpack.

**Comment by inviktus** [comment]
It's an ender dragon farm, if that helps.

**Comment by Ipsis** [comment]
EnderDragon shouldn't be an issue as people really abused that in FTB Beyond.
Do you have any other farms running successfully that are not EnderDragon?
If you swap out the EnderDragon controller for something else does it work correctly?
(I'm just trying to work out how to replicate this).

**Comment by inviktus** [comment]
Only other woot spawner I have is a blaze spawner. I'll pop the controller from that into the tier 4 one and see what happens.
...
Ok so that didn't cause lag, console isn't spitting out those can't keep up errors.
I popped the ender spawner back in and that seems to have stopped with the lag too?
I'll let you know if it comes back I guess.

The difference now is that I've just started the game to test this out and before I had been toiling away for far longer than anyone should spend in a single minecraft session. Perhaps after running for some time, it'll lag the client? I'll let you know how it goes.

**Comment by Ipsis** [comment]
It is completely possible that there is a corner case that you have come across or you have just been really unlucky and the ender dragon has triggered some long standing issue somewhere in your system.

These kind of issues are really hard to fix, especially if they are not reproducible mainly because the number of possible reasons are so vast.

Hopefully it wont come back ... fingers crossed :)

**Comment by inviktus** [comment]
It has been behaving itself since I posted, so as you said fingers crossed it stays that way.
Thanks for the reply :)

**Comment by inviktus** [comment]
Have not seen a repeat of that initial lag while using the ender dragon farm. closing this issue.
