### ISSUE TITLE
[1.12.2] [1.4.2] 2 little issues with Blood Magic compatibility

### ISSUE THREAD

**Issue by wamc2017** [Ipsis/Woot#377]
Hi,

i found two little issues with the Blood Magic compatibility:
1) There seems to be no recipe for the crystal upgrades, at least JEI doesn't show any
2) In the book the altar ritual is called "Ritual of the Mechanical Urn", but the name of the ritual is "Ritual of the Mechanical Altar"

Thanks for looking into it.

Best regards,
wamc

**Comment by Ipsis** [comment]
1. (I cannot find an ashamed emoji) It would appear that I put all the effort into making sure the crystal upgrades worked - but may have forgot to add a recipe! I was convinced that I had added some sort of recipe somewhere. I'll come up with some recipes and get that added.

2. The book is wrong. I was playing about with names and it looks like they have went out of sync.

Looks like a new release of Woot will be needed.
I'll try and push it out at the weekend.

**Comment by Ipsis** [comment]
bf04985d7193878157bdf9f5b93113f97c9f5386 manual text

**Comment by Ipsis** [comment]
108d6ba7e99879cba147526588b77745dde50caa recipes

**Comment by Ipsis** [comment]
Fixed in 1.12.2-1.4.3 which is on CurseForge
