### ISSUE TITLE
Disable RF cost by tier.

### ISSUE THREAD

**Issue by Yamza** [Ipsis/Woot#379]
I am trying to balance Woot against a typical mob farm. 

Ideally low tier mobs should be RF free, since say a resturbed mob spawner costs no power, and spews out ~5 mobs every minute or so with just some GP. Building a structure for the farm is fairly negligible (stone, vector plates). Killing the mobs Is also fairly simple and quick using a Mechanical User with a Tinkers Scythe.

I want Woot to compete with this so that people will prefer to use the less demanding farm. I have been messing with the configs to attempt to reach this, however if the RF cost is set to 0 then Woot does mob kills every tick, even if the tick rate is 160. The best I've come up with is making the RF cost as minimal as possible (320rf/t for enderman), but would prefer it to be able to work with no RF for T1-3 mobs.

I do like that it can farm bosses, and I am trying to set it such that it requires a certain power upkeep for a duration of time (30 minutes for a dragon, 2 hours for chaos). I was able to get this to work to my satisfaction.

**Comment by Ipsis** [comment]
I'm trying to see how I can do this with the current code.
The problem is mainly that Woot is based off power usage, so have 0 power basically tells the code that the recipe finishes immediately.

So one option would be for me to add something to say :
if it is a power free tier, then the recipe still says you need 10KRF and 100RF/tick, but I would just magic up some create RF/tick and not used it from the stored power.

There are two issue here:
1 - the top and gui will still show power required, so they would have to be modified
2 - you would get free usage of the upgrades as well, including the mass and rate upgrades

So it would be possible, but it might not be very neat.

**Comment by Yamza** [comment]
Would it at least be possible to set them to 1RF/t or something close to insignificant if it's not possible to completely disable them?

**Comment by Ipsis** [comment]
So I think what I can do the makes the most sense and doesn't break the code, is when I calculate the final power recipe, I can set the total power = spawn time, which will cause the power per tick to always be 1RF/tick when the tier specific config value is set.

eg. (made up values)
Enderman - no upgrades 320 ticks 320 RF @ 1RF/tick
Enderman - rate I upgrade 160 ticks 160 RF @ 1RF/tick
Enderman - mass III + rate I  160 ticks 160 RF @ 1RF/tick

So the factory always costs 1RF/tick at your chosen tiers, regardless of what upgrades you have.

**Comment by Yamza** [comment]
That sounds perfect.

**Comment by Ipsis** [comment]
New config options added which all default to false.


```
    # Limit the power requirements of Tier I to be 1 RF/tick
    B:tier1lowpower=false

    # Limit the power requirements of Tier II to be 1 RF/tick
    B:tier2lowpower=false

    # Limit the power requirements of Tier III to be 1 RF/tick
    B:tier3lowpower=false

    # Limit the power requirements of Tier IV to be 1 RF/tick
    B:tier4lowpower=false
```

**Comment by Ipsis** [comment]
![2018-08-25_08 31 25](https://user-images.githubusercontent.com/5602759/44616077-4e9c3200-a841-11e8-8bcf-8a7559fb8809.png)

**Comment by Ipsis** [comment]
d8793529aa959eb2893956c4b9f9c3fc717b2607

**Comment by Ipsis** [comment]
1.4.4 should be on Curse soon, once it has been approved.
Let me know if it is working the way that you had hoped.
