### ISSUE TITLE
Air block loot

### ISSUE THREAD

**Issue by tombomb** [Ipsis/Woot#383]
Hellp im playing the current release of stoneblock, checked the pack and im on the latest release of Woot. saw in another bug report for this issue that you wanted a loot.json.  I can confirm that the airblocks are in it, but here is the file anyways =p
[loot.json.txt](https://github.com/Ipsis/Woot/files/2420247/loot.json.txt)

**Comment by tombomb** [comment]
Restarting clears out the airlocks out of the list, but they are still generated over time

**Comment by Ipsis** [comment]
They will be cleared out on restart as they wont be loaded in from the loot file, I'll just quietly ignore them.
I'll need to try and find out what items they were originally since they are probably coming from another mod.

**Comment by Ipsis** [comment]
I've managed to replicate this, which isn't really a surprise.
Running with the debug turned on shows that while learning the loot dropped, I'm sometimes getting an invalid item - which is resolving to the AIR item.
So I'll need to add something to the code to watch for invalid EntityItems and ignore them.

**Comment by Ipsis** [comment]
I've pushed a new release (1.12.2-1.4.5) that fixes this issue.
Thanks for reporting this.
