### ISSUE TITLE
1.12.2 sponge    woot doesnt work with lycanites

### ISSUE THREAD

**Issue by HumanNugget** [Ipsis/Woot#388]
While playing on a sever woot doesnt scan loot which is wierd cause with the same config in single player it works fine.
![2018-10-06_23 23 52](https://user-images.githubusercontent.com/42466182/46575025-8230b700-c9be-11e8-9a7d-99bb3ead1cd5.png)

**Comment by Ipsis** [comment]
I'm taking it that you are using Sponge on the server going by the title.

Woot and Sponge don't play nice together unfortunately.
Sponge stops Woot from learning the loot drops as the events that it relies on are not issued, which is the problem that you are seeing. There was some work in Sponge, but I'm not sure what the outcome was - I don't use Sponge myself.

Out of interest, is it only the Lycanite mobs that are causing the issue? 
Do other mobs work correctly on the server?

**Comment by HumanNugget** [comment]
yea , i have witherseketon farm with witherskeletontweaks installed and its giving me modded loot .

**Comment by Ipsis** [comment]
In that case some of the Sponge issues must have been fixed. 

Assuming that you have op permissions on the server there is debug that you can turn on that will show if the events are being received.

eg.
To turn on
/woot dev debug event
/woot dev debug tartarus
To turn off
/woot dev debug !event
/woot dev debug !tartarus

This will write the debug for the onLivingDropsEvent assuming that the specific Lycanite mob is still being learned by Woot. You can check the learning status and restart a specific mobs one with
/woot dump learning
/woot flush <mobname>
