### ISSUE TITLE
Loss of items

### ISSUE THREAD

**Issue by Fingrad** [Ipsis/Woot#389]
Breaking an Stygian Anvil with a Die or an item on it doesn't drop the item..
![2018-10-07_16 42 22](https://user-images.githubusercontent.com/39800909/46582997-08e1a480-ca50-11e8-83cd-7657a44a6d44.png)
![2018-10-07_16 42 30](https://user-images.githubusercontent.com/39800909/46582998-0bdc9500-ca50-11e8-9bfd-556119533361.png)

**Comment by Ipsis** [comment]
I've never actually considered that, but it actually make complete sense.
There is currently no code to handle the block break and drop the associated dye.
I'll add that in for the next release.
Sorry about that.

Note to me: Need to override getDrops in BlockWootAnvil.java.

**Comment by Ipsis** [comment]
Fixed in 1.12.2-1.4.6
