### ISSUE TITLE
Missing Recipe for Efficiency Upgrades

### ISSUE THREAD

**Issue by tommyTT** [Ipsis/Woot#39]
The efficiency upgrades for the factory have no crafting recipes.

Versions:
Minecraft 1.9.4
Forge 12.17.0.1937
Woot 1.9.4-0.1.0-beta

**Comment by Ipsis** [comment]
Cannot believe I did that again. I'll roll a new version in the next couple of days to fix that. Sorry :(

**Comment by tommyTT** [comment]
No problem. I inserted my own recipe in my modpack. Another tweak that I made and might be of interest to you: I'm using the ore dictionary name itemSkull for the the mass upgrade recipe so I can use the enderman skulls from EnderIO as well.

**Comment by Ipsis** [comment]
Fix the missing recipe. Added the itemSkull option as a new enhancement issue, mainly because it seems a sensible thing to add to the recipes.
