### ISSUE TITLE
Woot Farm Refuses To Form

### ISSUE THREAD

**Issue by ghost** [Ipsis/Woot#397]
I've tried this using the intern (to make sure I'm not getting the structure wrong), multiple dimensions (including the overworld), and within a single chunk. In all cases, the farm (even just tier 1) refuses to form:
![2018-11-17_12 14 03](https://user-images.githubusercontent.com/24266948/48654613-8989bc80-ea62-11e8-87be-648127fa4303.png)

I'm playing on a modified version of All The Mods 3. The mods I added to the original pack are as follows:
- Sound Filters
- Extend Polyphony Limit
- Tiny Progressions
- Avaritia
- Refined Avaritia
- Avaritia Tweaks
- WorldEdit Forge
- FastAsyncVoxelSniper
- Refined Exchange
- ProjectE
- Reborn Storage

Anyways, not sure what's going on here. I've done some research and I'm aware All The Mods is set up so Woot farms require certain items, however I didn't think this was for formation, only operation.

The mod version is 1.12.2-1.4.6 (I assume this gives you the game version too :P).

**Comment by Ipsis** [comment]
So the item requirement doesn't impact the forming, it just stops anything being produced if you don't have the correct ingredients, So you end up wasting power :)

Can you try the following on a tier I factory.

Get the Ya Hammer and sneak right click until it says "Validate Tier I". Then right-click the factory heart and see if it tells you about any errors. That should cover things like a blacklisted mob, or a mob requiring a higher tier factory.

**Comment by ghost** [comment]
Interesting.. with the factory controller present it says the controller needs a higher tier of factory. With the controller removed it says it says expecting a controller at the exact coordinates I just had it at.

It recognizes the power cell, import and export modules, just not the controller.

EDIT: Validating a Tier IV structure returns nothing missing at all.. but it still isn't formed.

**Comment by Ipsis** [comment]
Which mob is the controller programmed for?

**Comment by ghost** [comment]
Wait - is programming required beforehand?

**Comment by Ipsis** [comment]
You need to create a programmed controller by combining a programmed ender shard and controller core on the anvil. (There should be no recipe for the controller)

If you want to use it in creative mode you need to use:
/woot give <player> <mob> <display name>
eg.
/woot give Ipsis minecraft:creeper Creeper

You can tab out the mob.

**Comment by ghost** [comment]
One moment - I'll test if using a programmed controller fixes this.

**Comment by ghost** [comment]
Well.. that can't be good. I can't even combine a programmed shard with a controller on the anvil, in survival or creative.

**Comment by ghost** [comment]
..and despite being opped I "don't have permission" to use the woot commands:
![image](https://user-images.githubusercontent.com/24266948/48666055-7502fe00-eb0e-11e8-8dce-037282b0220e.png)

EDIT: Never realised Woot had it's own anvil. I can place the shard on there, but still no idea how I go from there. I cannot find _any_ documentation on how to program a controller (I don't have the API required for your in-game guidebook currently).

EDIT 2: Even now knowing how it's supposed to be done, it doesn't work (there's a programmed shard on that anvil):
![image](https://user-images.githubusercontent.com/24266948/48666111-55200a00-eb0f-11e8-966b-c2ae5b15477a.png)

EDIT 3: Apparently the server console doesn't even have permission to use the woot give command:
![image](https://user-images.githubusercontent.com/24266948/48666141-d4add900-eb0f-11e8-9715-5a93519561da.png)

**Comment by ghost** [comment]
It does seem that unfortunately a form of #392 still exists, however possibly in a different way. The server OP permission level was already 4 when I tried those commands and was denied on the basis of permission.

**Comment by Ipsis** [comment]
Rather than me try to explain badly, you might want to try https://www.youtube.com/watch?v=DtDSuHE0L9o&t=1s and skip to 2m50s and RG_sha explains how to use the anvil for controller creation.

Not sure about the server console one. I tested on my own setup here and it was fine, so I'll have to go back and test that again. Unfortunately I never found out if the fix worked from the bug reporter.

**Comment by ghost** [comment]
Thanks, I'll check out that video. Would you like a helping hand testing different things to see if you can get the commands working?

**Comment by Ipsis** [comment]
Thanks for the offer, but I'll need to start off by setting up the same server as you, as this will allow me to load dev versions of the mod to find out what is going on.

Which version of ATM3 are you using and which server files?

**Comment by ghost** [comment]
ATM 5.11.1 (and its corresponding server pack), plus the mods that I added:
- Sound Filters
- Extend Polyphony Limit
- Tiny Progressions
- Avaritia
- Refined Avaritia
- Avaritia Tweaks
- WorldEdit Forge
- FastAsyncVoxelSniper
- Refined Exchange
- ProjectE
- Reborn Storage

I think its very interesting to note that even the server - the highest permission level I can think of - was denied from the give command. I could be wrong but that strikes me as an issue that differs from the command only being callable by the server and not players.

**Comment by Ipsis** [comment]
I've been working on the command issue in #398 as someone else was reporting that specific issue and I managed to replicate it in Stoneblock modpack.

**Comment by ghost** [comment]
Oh, fantastic! I hope that release will work for us. :)

**Comment by Ipsis** [comment]
Uploaded 1.12.2-1.4.8 to Curse, so should be available soon.
Retest on the StoneBlock map and I have access to give and flush.

**Comment by ghost** [comment]
Absolutely fantastic, I'll let you know if it fixes things on my end too :)
