### ISSUE TITLE
Can't flush loot table

### ISSUE THREAD

**Issue by raindropworks** [Ipsis/Woot#398]
Minecraft 1.12.2
Forge 14.23.4.2768
Woot 1.4.7

I just added quark to my server, which adds new drops for the wither skeleton. Per the wiki, running `/woot flush wither` should flush the loot tables in my currently running generator, but when I try I get a console error of `You do not have permission to use this command`.  Even trying it from the server console (since it's my server) gives the same error.  Also, attempting `/woot loot wither` gave a different error: `Invalid subcommand 'loot'! Available subcommands: dev and dump`

Am i just doing something stupid, or is there a documentation/wiki bug?

**Comment by Ipsis** [comment]
I had fixed up the commands to use permission level 2, which is the equivalent of using the gamemode, gamerule commands. However I'm getting a few reports that this is not working properly.

So the first question is are you running a modpack and if so which one?
(I'm trying to work out if the issue is coming from something else, or I've just made a big mistake somewhere).

Had you every used the woot command before without issue?
Can you use the standard gamemode,  give commands without issue?

The wiki pages are still referring to the older 1.10/1.11 commands. I'm terrible at updating documentation.

You should have access to 
/woot dev
/woot dump
/woot flush
/woot give

eg.
/woot dump learning
/woot flush all
/woot flush minecraft:creeper
When you flush a mob, it wont start learning again until you have a mob factory of that type.

At the moment there is no "/woot dump loot" command.

**Comment by raindropworks** [comment]
Lot of stuff asked for, but I'll try to go through stuff for you

Modpack: Yes, but it's a custom one that I've made.  The full list is at https://puddle.zone/minecraft/terranovalegal.html (it's the list for my own server)

`/woot dump learning` does give info, matches to the generators i've made
`[12:40:28] [main/INFO] [minecraft/GuiNewChat]: [CHAT] minecraft:sheep-500/0/0/0
[12:40:28] [main/INFO] [minecraft/GuiNewChat]: [CHAT] minecraft:rabbit-500/0/0/0
[12:40:28] [main/INFO] [minecraft/GuiNewChat]: [CHAT] minecraft:guardian-500/0/0/0
[12:40:28] [main/INFO] [minecraft/GuiNewChat]: [CHAT] minecraft:pig-500/0/0/0
[12:40:28] [main/INFO] [minecraft/GuiNewChat]: [CHAT] minecraft:wither_skeleton-500/0/0/0
[12:40:28] [main/INFO] [minecraft/GuiNewChat]: [CHAT] minecraft:cow-500/0/0/0
[12:40:28] [main/INFO] [minecraft/GuiNewChat]: [CHAT] minecraft:chicken-500/0/0/0
[12:40:28] [main/INFO] [minecraft/GuiNewChat]: [CHAT] minecraft:wither-500/0/0/0`

/woot flush all, however, errors
`[12:44:41] [main/INFO] [minecraft/GuiNewChat]: [CHAT] You do not have permission to use this command`

Same holds true if I try it from the server console
`[12:45:22] [Server thread/INFO] [minecraft/DedicatedServer]: You do not have permission to use this command`

and since I opped myself on the server, `/give meido_sera minecraft:stick` does indeed give me a stick, if that's what you were asking about before?

Here's to hoping something in there helps.  I also added my (sanitized) server.properties to show that I should have op-level 4, way above the 2 you set the commands to use.  Anything else I'm more than happy to try to help with
[server.properties.txt](https://github.com/Ipsis/Woot/files/2597012/server.properties.txt)

**Comment by Ipsis** [comment]
That was a quick response!
So basically the "/woot dump" command has the same permission as the "/woot flush" command so they should both work. Both of these work for me running a standalone server and client in my dev environment,
The fact that vanilla "/give" works is strange as it has the exact same permission level.

This is a little baffling.
The only difference between "/woot dump learning" and "/woot flush" is that the dump command has sub-commands, but I cannot see why that makes any difference.

The good news - if you can call it that - is that I've got a StoneBlock single player game with the exact same issue. "/woot dump learning" works, but "/woot flush minecraft:creeper" fails with the permission error, even though they have the same level, as does "/woot give <user> minecraft:creeper Creeper".

So I'll investigate it on my setup and see if I can get to the bottom of what is happening.

**Comment by raindropworks** [comment]
Not a problem.  Anything I can do to help I'm fine with!  I was only so fast because I happened to be in world and had github up when you posted

**Comment by Ipsis** [comment]
So ... I think I fixed it.

1.4.7 - both /woot give and /woot flush fail with "You do not have permission".
1.4.8_dev - both /woot give and /woot flush work correctly.

I still don't understand why it works, but I did make a change.
Basically CommandFlush and CommandGive were subclasses of CommandBaseTree, but they don't have subcommands. So I changed them to be subclasses of CommandBase and it all works.
There will be some subtle logic as to why that breaks stuff but only outside a dev environment.

It is working for me in Stoneblock which had the same error that you saw, but in single player.
So what I'll do is sit on it and probably do a release tomorrow with the fix in it.
So hopefully when 1.4.8 comes out it should work for you.

**Comment by raindropworks** [comment]
Here's to hoping!  I've purposely held off making upgrades to my farms so they don't autogenerate new loot tables by accident

**Comment by Ipsis** [comment]
Uploaded 1.12.2-1.4.8 to Curse, so should be available soon.
Retest on the StoneBlock map and I have access to give and flush.

**Comment by raindropworks** [comment]
Confirmed worked for me.  Had to do it twice because I did it against the wrong wither (boss instead of skeleton)
