### ISSUE TITLE
Mob capturing mechanics

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#4]
The current mob capturing mechanics need looked at. Currently it just involves hitting the relevant mob, so need to decide if that is too simplistic.

**Comment by ShadowDrakken** [comment]
My only comment is that I'd prefer this to be a right-click rather than an attack, since you're performing an action with the prism, this would bring it in line with vanilla mechanics.

**Comment by Ipsis** [comment]
The attack was basically used as it meant you couldn't just sneak up to a mob, learn it and then run away. You would anger the Zombie Pigman or have to deal with the Wither Boss :)

Unfortunately it does mean you have to be unkind to your cows :P

**Comment by ShadowDrakken** [comment]
Hrm, that makes sense. Guess I'll have to learn how to brew splash potions is all there is to it :)

**Comment by ShadowDrakken** [comment]
Had a thought on this; I haven't tried doing damage/attacks in Forge, but in Bukkit you could cause damage and set the damage source programatically. Switching this to right-click, but causing a zero damage attack with the user as the source should cause the aggro as normal :) Assuming Forge doesn't just treat a zero damage attack as not even happening in the first place.

Eh, I know I'm overthinking this, lol.

**Comment by 2000game** [comment]
Some sound would be nice or that you need to hit it more times.

**Comment by Ipsis** [comment]
I'll try again to find an appropriate success/failure sound.

**Comment by imepic86** [comment]
Right click with prism to drain 50% of mobs total health, shift right click to drain 100%.

if 100% capture instantly, if 50% first drains life, 2nd right click captures.

Just an idea!

**Comment by ShaCraft** [comment]
Just a note for Imepic86. there is a config to change how many mobs you need to kill to charge the shard. by default it is set to 1. you can adjust that for packs to make it harder. /cheers

**Comment by imepic86** [comment]
@ShaCraft Appreciated. But i was referring to Ipsis comment at the top on how to capture mobs. I didnt realise this was already something you could change as i usually leave configs default(except extreme reactors)

....and i JUST realised it says 2016 .... oops. Okay now i feel stupid lol.

**Comment by Ipsis** [comment]
@imepic86 I should really have closed this bug when I implemented the new mechanics. Think I've got some housekeeping to do :)
