### ISSUE TITLE
prism dyes

### ISSUE THREAD

**Issue by foofookiller** [Ipsis/Woot#405]
is it possible to use other mod's dyes for this? or does it have to be the default minecraft ones?

**Comment by Ipsis** [comment]
The recipe is only set for minecraft dyes.
I'll see about putting an ore dictionary entry in next time I make a build, since it really should support them.

**Comment by foofookiller** [comment]
thanks.

**Comment by Ipsis** [comment]
Fixed in next release 1.12.2-1.4.10
