### ISSUE TITLE
[1.12][Suggestion]Quark Interaction

### ISSUE THREAD

**Issue by kjj194** [Ipsis/Woot#406]
Quark adds a drop to the ender dragon that is used to create elytras. While it is currently possible to add to the config manually I was wondering if it would be possible to add it by default similarly to the dragon heart from draconic evolution.

**Comment by Ipsis** [comment]
Possibly - could you give me a pointer to what the drop is.
My only reluctance is that people can easily add it to the configs if they feel that it should be there and modpacks will have already added the Quark drop or deliberately left it out. So if I add it to the default then that could be a bit of a surprise for them!

So is there any strong justification for having it added to the default or is it simply for convenience which is a perfectly acceptable answer.

**Comment by kjj194** [comment]
Sorry for the delay in reply it adds a scale from the ender dragon that can be used for making an elytra. Mostly its useful for mod packs that contain extrautils 2 in that their opinium cores require quite a few elytras which can be difficult to get especially on servers. As for modpacks being able to add it if they like you're totally correct I just think its also just as easy to remove it if they would like and would save players from servers who just slap a pack onto it without knowing / caring about configs.

**Comment by Ipsis** [comment]
After some thought, I'm just going to add the dragon scale to the default configs.
It will be a 100% drop of 1 per Dragon, regardless of looting level.

Any modpacks can remove or override (some already scale drop change based on looting).
