### ISSUE TITLE
Suggestion: Config to disable ender shards

### ISSUE THREAD

**Issue by focamacho** [Ipsis/Woot#415]
Would be cool have a option in the configs to disable the ender shard from some mobs

Example: I do not want players to be able to capture the ender dragon on shard, so I'd like to disable this. With this, I could create a custom craft for the woot of ender dragon.
Like this:
![image](https://user-images.githubusercontent.com/48870573/57086366-5bc4c700-6cd4-11e9-8d8e-e7e4abbcd2b3.png)

**Comment by Ipsis** [comment]
I'll take a look to see how easy this is to support. 
Currently the blacklists cover the capturing and the ability for the factory form, so I'll need to ensure that current configurations don't break. It should be possible to support this.

**Comment by Ipsis** [comment]
Now that I've had a look at this, I think I've got it added correctly.
I'm going to add a new entry to factory_config.json.
`"entitygenerateonlylist": []`

You will not be able to capture anything in that list, but you will be able to generate loot from it, if you have a controller.

I need to do some testing, but it look "okay" so far.
