### ISSUE TITLE
Sky Odyssey Wither Farm Missing Loot

### ISSUE THREAD

**Issue by StarDusGamer** [Ipsis/Woot#416]
When building a TierIV Wither Woot farm in Sky Odyssey, I am supposed to recieve a chance for a Game Over crate and Others, but they casualy disappear, and the Game Over Crates never show.
If anybody could please help me that would be great.

![WitherIV](https://user-images.githubusercontent.com/24214142/59208508-0e9f0500-8b5e-11e9-8c65-5cce795c9cd3.PNG)

**Comment by Ipsis** [comment]
The Game Over crates drop at such a low rate, that there is a good chance that Woot will not learn the drop within 500 simulated drops that it learns from. Some people will be lucky enough to learn one and other wont, which is how I believe the FTB team wanted this to work.

I believe there were posts made on Reddit(?) that showed ways that people had updated the Woot learned drop information to include the Game Over crates. (https://www.reddit.com/r/feedthebeast/comments/b4m71v/sko_game_over_loot_bags/)

You can use the "/woot flush all" command to restart the learning process and you may be lucky enough to get a crate.

**Comment by StarDusGamer** [comment]
Thank You for Your Help

**Comment by smmailik** [comment]
May b it's a late question but .. I've downloaded the Json file .. I've put it in the config folder for Woot but it doesn't take any effect and there wasn't from the beginning any file named "Loot" .. pls help ..
I've flushed the Loot tables may b 20  time and no luck .. I've also changed in the config the number of learn simulations to 4000 from 500 also no effect .. I'm desperate ..

**Comment by ghost** [comment]
@smmailik The learning process takes time (usually a few minutes for the full table to be populated). You can track how much learning has been completed by using the "/woot dump learning" command. It will tell you the number processed by the first number attached to the mob.
e.g. minecraft:wither-152/0/0/0 means my woot has processed 152 kills worth of drops.
I found that it only took a few full runs (I set it off to go, and then did something else until it was done) for the crate to show up.

Hopefully that clarifies why you might be having issues.

Edit: I just learnt this so I thought I'd add a bit more information, the following numbers refer to each of the tiers of looting.

i.e. base mob/looting I/ looting II/ looting III
