### ISSUE TITLE
[Suggestion] Change Core Die recipe to allow for single anvil automation

### ISSUE THREAD

**Issue by Zetsukaze** [Ipsis/Woot#417]
Playing FTB Revelation, I have managed to automate the entire anvil crafting with AE2 and various other mods in a compact setup requiring only one anvil, except for the Core Die as the Tier 1 Upgrade Core shares a common component, redstone.

The Core Die recipe requires the redstone to be placed on the anvil, while the Tier 1 Upgrade core requires the redstone to be dropped on top of the anvil, which causes a routing issue.

Might I suggest lapis to be used instead for the Core Die recipe? I tried to use CraftTweaker but the Core Die had no recipe detected.

**Comment by Ipsis** [comment]
Unfortunately the recipes are internal to the mod as they are not standard crafting and are therefore not accessible via crafttweaker.

As the mod is already out, I can maybe(?) add a second recipe for the Core Die that uses Lapis, but I cannot remove the redstone based one, as it would break for other people.

One question I have is why you need to create more than one Core Die, as the dies are not consumed in the recipes, but are returned at the end of the crafting sequence. I am perhaps misunderstanding the problem that you are having.
