### ISSUE TITLE
PO3: Tartarus filling up with entities?

### ISSUE THREAD

**Issue by Anaerin** [Ipsis/Woot#419]
Had an interesting issue - Server was slowing down pretty hard, and /tps was reporting ~2000+ entities in tartarus.

I used /tpx to teleport into tartarus, which put me WAY away from 0,0. Moving to 0,0 I found all the cages, which were empty, confirmed by a second check of /tps. So it seems that some things are getting spawned and not killed in tartarus (in this pack). Possibly to do with wither minions.

Latest Project Ozone 3 (in Kappa mode), running 1.12.2-1.4.11

**Comment by Ipsis** [comment]
There are some mobs that when they die spawn other mobs.
I normally blacklist those internally to stop this from happening or you can blacklist them in the configs.

The trick will be identifying which mob is causing them.
Do you have a dump of the loot.json file that is generated, that might narrow down which mobs people were trying to farm.

**Comment by Anaerin** [comment]
loot.json currently reads:
```
{"version":1,"mobs":[],"drops":[]}
```
Which isn't helpful at all.

**Comment by Ipsis** [comment]
So ProgressiveBosses is open source and they act on both Dragon deaths (which I don't simulate) and Withers (which I do simulate)
It spawns a number of Wither Skeletons which is possibly getting to happen between me spawning the Wither and killing it.

Normally I would say blacklist the mob that is causing this issue, but in this case that would be blacklisting the Wither :(
One option would be to disable the Wither Skeleton spawning from the Wither, as I can see some config option for "difficultToSpawn" which if you put it up to 65000 might stop the skeleton spawning.

The other option, but not something I can do quickly, is it add some sort of purge mechanic during simulation, which
* spawn and kill mob
* sweep up drops
* kill everything in the specific cage

**Comment by Ipsis** [comment]
Fixed in 1.15/1.16 series.
