### ISSUE TITLE
Config Custom Mob Drops NBT

### ISSUE THREAD

**Issue by EvanHammerstein** [Ipsis/Woot#420]
Hi, I'm trying to make Landlords from land core/landcraft drop the various ingots. However, I'm not sure how to put in the config the custom mob drops due to it using ids such as 1032/1, 1032/2 etc, and the word form for all of them is landcore:item_ingot. Any idea on how to put things such as the /1 or :1 into the config? Thanks

**Comment by Ipsis** [comment]
`
      "drops": [
        {
          "drop": {
            "item": "draconicevolution:chaos_shard",
            "data": 0
          },
          "sizes": [ 1, 1, 1, 1 ],
          "chances": [ 10, 20, 30, 40 ]
        },
`

The above shows an example of the id being specified as the "data" entry.
This is how I drop chaos shards from DE, so yours will follow the same pattern.
Hope that  helps.
