### ISSUE TITLE
About the loot the factory learns

### ISSUE THREAD

**Issue by ThunderLion1069** [Ipsis/Woot#421]
Hi, I was wondering about the method of how woot learn the loot of the target mob. I'm now playing FTB sky odyssey, which there's a small chance to get game over crates from wither bosses. I look upon the internet and it said if the crate doesn't appear on the loot section it'll never produce it. But to me, it sometimes appears and sometimes does not (which it sometimes produces and sometimes doesn't).

**Comment by Ipsis** [comment]
Woot only samples a certain number of kills to learn the drops for a specific entity. IIRC the drop rate of the game over crates is less than 1%. This means that after the sampling process then some players will have learned the game over crate drop and other wont.
However if does appear in the factory drop tables then  the tooltip should show you the drop the chance.  If that drop chance is less than 100% then you will not get the drop for every factory kill.
