### ISSUE TITLE
Factory Heart Bug

### ISSUE THREAD

**Issue by Azuneer** [Ipsis/Woot#422]
When in click on the factory heart of my factory, nothing happens, like i don"t have any menu showing up, need help plz

**Comment by Azuneer** [comment]
Oh and just a question, can i farm wither skeletons ? Because i tried with zombies and it works ...

**Comment by Azuneer** [comment]
Yeah i figured out that actually we can, but we can't farm skeleton head

**Comment by Ipsis** [comment]
Wither skeletons need a higher tier of factory.
You can use the decapitate upgrade to increase the chances of getting a skull drops.
Heart will only show the gui when you have a valid, formed factory.

**Comment by Azuneer** [comment]
Oh okay thx, can we upgrade the chance of looting head skulls, beacuase i only got 2% of chance to drop them

**Comment by Ipsis** [comment]
The Headhunter enchant doesn't work with Wither Skeleton skulls but does for all other skulls.  The drop chance is configured in the config as headhunterXDropChance - default to 30/50/80%
(X = 1,2,3)

The Decapitate upgrade chances are in the config under decapXParam - default to 20/40/80%
