### ISSUE TITLE
The blood tank life essence 1-2-3 upgrade, how exatly do they work?

### ISSUE THREAD

**Issue by EldarAlvik** [Ipsis/Woot#423]
I read the manual for the ritual and I read the config and it said it could use up to 24 runes of sacrifice. However, I couldn't find out how to add it or make it work. Some clarification would gladly help.

**Comment by Ipsis** [comment]
The ritual and Blood Magic alter have to be within range of the factory, the range will be specified in the Woot boot.
It will then output life essence into tanks adjacent to the export block of the factory.
The amount of life essence is determined by the mob and rune of sacrifice count.

**Comment by EldarAlvik** [comment]
what if I used the other ritual? the ritual of the sanguine urn. As it doesn't require a blood altar

**Comment by Ipsis** [comment]
The Infernal Machine ritual requires the Blood Altar. The Sanguine Urn does not.
