### ISSUE TITLE
Drops not being created.

### ISSUE THREAD

**Issue by Thekingofeverything** [Ipsis/Woot#424]
I edited the config file to add drops from other mods (green hearts from baubley heart canisters) to the ender dragon but they don't drop. The vanilla items drop so is this a compatibility error?

**Comment by Ipsis** [comment]
Can you show me the updated config file so I can see how the drops were defined.

**Comment by Thekingofeverything** [comment]
{
          "drop": {
            "item": "mysticalAgradditions:Dragon_scale"
          },
          "sizes": [ 2, 4, 6, 8 ],
          "chances": [ 25, 50, 75, 90 ]
        },
        {
          "drop": {
            "item": "baubleyHeartCanisters:green_heart"
          },
          "sizes": [ 1, 2, 3, 4 ],
          "chances": [ 100, 100, 100, 100 ]
        },
        {
          "drop": {
            "item": "immersiveengineering:Epic_shader_grabbag"
         },
          "sizes": [ 1, 1, 1, 1 ],
          "chances": [ 1, 1, 1, 1 ]
        },
        {
          "drop": {
            "item": "minecraft:elytra"
	    },
          "sizes": [ 1, 1, 1, 1 ],
          "chances": [ 5, 25, 30, 50 ]
        },

**Comment by Ipsis** [comment]
When I load up your file then the logs show the following:

[19:11:43] [Client thread/ERROR]: Woot: getItemStack: unknown item mysticalAgradditions:Dragon_scale
[19:11:43] [Client thread/INFO]: Woot: Ignoring invalid itemstack
[19:11:43] [Client thread/ERROR]: Woot: getItemStack: unknown item baubleyHeartCanisters:green_heart
[19:11:43] [Client thread/INFO]: Woot: Ignoring invalid itemstack
[19:11:43] [Client thread/ERROR]: Woot: getItemStack: unknown item immersiveengineering:Epic_shader_grabbag
[19:11:43] [Client thread/INFO]: Woot: Ignoring invalid itemstack
[19:11:43] [Client thread/INFO]: Woot: Added custom drop Elytra for minecraft:ender_dragon

**Comment by Ipsis** [comment]
```
{
"drop": {
"item": "mysticalAgradditions:stuff",
"data": 3
},
"sizes": [ 2, 4, 6, 8 ],
"chances": [ 100, 100, 100, 100 ]
},
{
"drop": {
"item": "bhc:green_heart_canister"
},
"sizes": [ 1, 2, 3, 4 ],
"chances": [ 100, 100, 100, 100 ]
},
{
"drop": {
"item": "immersiveengineering:shader_bag",
"nbt":"{rarity:\"EPIC\"}"
},
"sizes": [ 1, 1, 1, 1 ],
"chances": [ 100, 100, 100, 100 ]
},
{
"drop": {
"item": "minecraft:elytra"
},
"sizes": [ 1, 1, 1, 1 ],
"chances": [ 100, 100, 100, 100 ]
}
```

**Comment by Ipsis** [comment]
The above worked for me when plugged into my test works. Basically the names were not correct and the Epic shader bag needed NBT defined to make it drop correctly.
