### ISSUE TITLE
[1.12.2] Wither farm does not generate anything but shards

### ISSUE THREAD

**Issue by LixYt** [Ipsis/Woot#427]
Hi there ! 

First of all, it's never enough said : nice work on woot !

**Woot version** : 1.12.2-1.4.11
**Forge version** : 14.23.5.2846

**Issue** : I don't get any other loot than shards as shown in the screen capture
![image](https://user-images.githubusercontent.com/45044873/82990617-c2620480-9ffc-11ea-8732-291fdea29893.png)

I don't know if it was the thing to do, but i /flush it.
Also, my previous use of woot in 1.12.2 required input (soul sand & wither skull) but it does not anymore. So my first guess would have to be a config issue... Maybe... Maybe not. 

Regards
Lix

**Comment by Ipsis** [comment]
Could you post the Woot config files - 
custom_drops.json
factory_config.json
factory_ingredients.json

And the drops file -
woot/loot.json

Also is this a mod pack and if so could you let me know which and the version.

**Comment by LixYt** [comment]
FTB Revelation 1.12.2 v3.2.0 + custom mods (unrelated i think)

attached files : 
config/woot/custom_drops.json
config/woot/factory_config.json
config/woot/factory_ingredients.json
config/woot/woot.cfg
[woot cgf files.zip](https://github.com/Ipsis/Woot/files/4697743/woot.cgf.files.zip)

and woot/loot.json
[loot.zip](https://github.com/Ipsis/Woot/files/4697746/loot.zip)

**Comment by Ipsis** [comment]
I've loaded up your config with 1.12.2 v3.2.0 and with a Tier IV factory I'm seeing the correct drops and ingredients in the GUI. So your config files are good and so is the loot file.

There is an error on startup with those configs which makes it ignore the end of factory_config.json, but that wont impact the Wither.

What other mods are installed and how did you get the controller for the Wither?
My best guess would be that the controller says "Wither" but the NBT attached to it is incorrect.

You could try - assuming you have permissions:
/woot give <username> minecraft:wither Wither
That will give you a new controller and see if that works correctly.

**Comment by LixYt** [comment]
You are right. Bad controler. Requires now Tier IV. 
I can't remember how we get this controler but I think it wasn't the 'normal' way.
We are gonna upgrade the farm.

I'm gonna close this issue. Thx for your support.
