### ISSUE TITLE
1.15 - Can't craft Mob Controller

### ISSUE THREAD

**Issue by ofseaandstars** [Ipsis/Woot#429]
Forgive me if I'm missing something, but on the 1.15 version I cannot seem to craft the Mob Controller.

The recipe shows up in JEI as expected, but placing the fully programmed mob shard on the Stygian Anvil and right-clicking with the YA Hammer does absolutely nothing.

woot-1.0.0.0
forge-1.15.2-31.1.87

**Comment by Ipsis** [comment]
My JEI plugin is no longer showing the full recipe.
Base item - programmed shard
Item 1 - prism
Item 2 - cobblestone

(Shouldn't actually be cobblestone but I haven't updated the recipe)

**Comment by Ipsis** [comment]
Fixed in 1.15.2-1.1.0 0 - which has just been uploaded to CurseForge
