### ISSUE TITLE
[1.9.4] Removing redstone signal drains power but no loot

### ISSUE THREAD

**Issue by tommyTT** [Ipsis/Woot#43]
I have a tier 3 factory running and stop it from working with a redstone signal through a lever on the block at the back of the factory block. The spawning stops and the factory doesn't drain any more power. If I then remove the redstone signal, the power is drained again and it seems like it is running, but no loot is generated. Unfortunately I couldn't reproduce it in my test pack (see other issue with the multi block not forming), but in my main pack with Version 0.1.0-beta I can. If I break the controller and reattach it, everything works fine again.

Forge Version 12.17.0.1940

**Comment by Ipsis** [comment]
That one got fixed this morning. It only generated loot when the number of spawn ticks was exactly equal to the required spawn time. Suffice to say it has been changed from == to >=. So that will be in todays(?) 1.9.4-0.2.0-beta release

**Comment by Ipsis** [comment]
fde9ea9e94c0318369f3c0831f176779e6e63a50
