### ISSUE TITLE
[1.15.2] Woot crashes after completing Tier 5 woot with Wither boss 

### ISSUE THREAD

**Issue by remplerus** [Ipsis/Woot#430]
Im not 100% sure if its a problem with Woot, but it happened directly after finishing tier 5 building with hammer.

Here's crashlog: https://pastebin.com/P1kkA9H5

If you need any more information, just ask.

**Comment by Ipsis** [comment]
Which modpack are you running Woot with?
Did you successfully run factories with other mobs ? (I'm guessing that you did).

It is some interaction between the Woot mob learning sequence and the FTBQuest mod. When the Wither is first killed to learn it's drops, then the FTBQuestsEventHandler.playerKill/QuestFile.getData seems to be unhappy.

Cannot say if its Woot's fault, FTBQuest or just the two not playing nicely together.
It could be the fact that Woot is using a FakePlayer - but not sure why it would only impact the Wither. I'll take a look at their code and see if I can spot some interoperability issue.

**Comment by remplerus** [comment]
it just crashes if i have ftb quest installed, without it, everything works fine. so i think its a weird interaction with ftb quest, that mod has some bugs with rendering stuff but isnt "easy to fix" cause it takes very long time (i requested it 2 months ago lol).

**Comment by Ipsis** [comment]
I've had another look at the code and I'm not clear on why FTBQuests is okay with the FakePlayer on other mobs but the Wither causes an crash. (Did you manage to farm other mobs okay with Woot - it is just the Wither?)
They are looking up the player data for the player that killed the Wither (FakePlayer), not finding it and that causes the crash. I just don't know why.

You might want to ask FTBQuests.
I'm happy to fix the problem if it is a Woot issue, but I just don't see what it wrong with Woot.

**Comment by remplerus** [comment]
i have asked the dev of ftbquests. they have a lot of things to do inside ftbquest, so thats their problem. i have just changed the quest mod to another one and there everything works fine. so its definitely ftbquests fault. they already know about those things, so i close this until i have more information. but thanks so far
