### ISSUE TITLE
Dye Liquifier does not produce output

### ISSUE THREAD

**Issue by wgyde** [Ipsis/Woot#433]
Hi!

I'm running Woot as part of a modpack, and ran into an issue where the Dye Liquifier consumes R/G/B/W dyes, but does not produce any output. I'm not sure if this is an issue with the modpack, or with woot itself.

Gif:
![DyeLiquifier](https://user-images.githubusercontent.com/9455436/85097817-970ea780-b1ad-11ea-8978-0d4132783e8a.gif)

A few Notes:
- I've tested the Dye Liquifier in chunkloaded, claimed, and unclaimed chunks
- I've tested the Dye Liquifier in the presence and absence of other dye-holding machines
- I'm running woot as part of a modpack, which I acquired through the twitch desktop app (versions below)
- None of the woot config should have been modified from the defaults

Any help or insights you can offer are appreciated!

Versions:
**woot:** woot-1.15.2-1.1.0.0.jar
**Minecraft:** 1.15.2 (modded)
**Forge:** forge-31.2.9
**modpack**: All the Mods 5 (Version: 2.1)

**Comment by Ipsis** [comment]
Fixed in 1.15.2-1.1.0.1 - Fixed gui with tanks not updating [#431]
https://github.com/Ipsis/Woot/issues/431 is the same issue but with the VAT.
Don't know if ATM5 has bumped that yet.

**Comment by wgyde** [comment]
Confirmed, this is just a graphical issue. Thanks!
