### ISSUE TITLE
Server Crash When making Dye Plate and Conatus Fluid

### ISSUE THREAD

**Issue by QuantumConcious101** [Ipsis/Woot#434]
WOOT Ver1.15.2-1.1.0.1
Mod Pack RAM Really Awesome Mods

Server Crash very repeatable
Make Dye Liquifier Connected to Injection Press
Add Dyes to Liquifier
Add Casing to Injection Press
Server Crash upon Completion of any Plate this has happened every time
So i spawned a stack of every plate in and that was fine
Crash Report:
https://pastebin.com/Pi64DW4f

Continued to make the rest of the Basic stuff

Basic Conatus Cell
Causes a crash when you make Conatus Fluid to fill it
Server crashes upon the creation of the Fluid every time repeatable
Crash Report:
https://pastebin.com/Hu3RrFTQ

**Comment by Ipsis** [comment]
Both of these crashes seem to be an interaction with another mod.

First crash is with dev.latvian.kubejs.player.InventoryListener
java.lang.ClassCastException: dev.latvian.kubejs.player.InventoryListener cannot be cast to net.minecraft.entity.player.ServerPlayerEntity

Send crash is with com.feed_the_beast.ftbquests.util.FTBQuestsInventoryListener
java.lang.ClassCastException: com.feed_the_beast.ftbquests.util.FTBQuestsInventoryListener cannot be cast to net.minecraft.entity.player.ServerPlayerEntity

Both of these are triggered off the Woot InfuserContainer class.

As of yet I don't know if I'm doing something wrong (possible) or the other mod is wrong (also possible).

**Comment by Ipsis** [comment]
Looks like these mods add a new listener to listeners list. I just walk over them and cast them to (ServerPlayerEntity) which clearly, as the crash shows, they are not. So I'll need to check for the correct type and ignore those ones. 

So this is a deficiency in Woot. I'll get it patched up.

**Comment by Ipsis** [comment]
Fixed in 1.15.2-1.1.0.3
