### ISSUE TITLE
Controller Not Found - ATM5 1.15

### ISSUE THREAD

**Issue by LD8Charon** [Ipsis/Woot#435]
When trying to create a new tier 1 Zelator factory, I am told that there is "No valid primary controller at (x,y,z)". 

Searching through the issues and various videos/forum posts, I've gathered a skeleton programmed mob shard. My issue is, I can't seem to attach the shard to the controller. I've tried placing both items on the stygian anvil and then right-clicking with the YA hammer, but this does nothing. 

If there happens to be any updated documentation for the mod, then I'm happy to review it and give that a shot!

**Comment by Ipsis** [comment]
On an empty anvil, right click the programmed shard. Then right click on the anvil with a prism and a stygian anvil plate. Finally right click with the Ya Hammer and the controller should be dropped into your inventory. The shard needs to be fully programmed (normally needs 5 kills of the particular mob)
