### ISSUE TITLE
Minor Issue with Referencing Invalid Block

### ISSUE THREAD

**Issue by FallenEagle1** [Ipsis/Woot#436]
Talked briefly about this, just recording it down. Chat output of x,y,z is outputting x,z,z. Linked the spot as well for easy access to it.

https://github.com/Ipsis/Woot/blob/59c586dc5b56e308abea3b18044df2595cb70968/src/main/java/ipsis/woot/modules/factory/layout/FactoryScanner.java#L105

**Comment by Ipsis** [comment]
https://github.com/Ipsis/Woot/commit/76a8319e8ccc6031bb82f835171dcf3f5020fa46

**Comment by Ipsis** [comment]
Fixed in 1.15.2-1.1.1.0
