### ISSUE TITLE
Am I missing something? What is a valid base item?

### ISSUE THREAD

**Issue by Jaeiya** [Ipsis/Woot#437]
I'm on MC 1.15.2

There is no up-to-date information on the stygian anvil or how to make it work properly. Is there a wiki that I'm not able to find where it shows how to do this? 

![image](https://user-images.githubusercontent.com/2054218/86854561-7ed3cf00-c06d-11ea-848e-8c0bb317aa91.png)

**Comment by Jaeiya** [comment]
Okay, so I figured it out. The base item is the item being worked on in the anvil, which has to be right-clicked onto it. However the fact that there's no documentation for this makes it very ambiguous.

**Comment by Ipsis** [comment]
The in-game docs are a bit light just now and will be improved in future releases.

Currently I rely on the JEI-plugins to add that extra information - so there are Anvil specific JEI entries that show for each recipe which item is the base item.
