### ISSUE TITLE
[1.15.2] Woot farm wont accept Iron golem controller

### ISSUE THREAD

**Issue by brendan612** [Ipsis/Woot#438]
My woot farm is built correctly. It runs well with multiple other mob controllers, but wont form when I put in an Iron Golem controller

**Comment by Ipsis** [comment]
The tooltip that shows the correct tier on the controller block seems to be broken.
The Iron Golem should be set to Tier IV, which is what the factory is using as its health is 100.
However when displaying the tooltip is gets a health of -1 and there displays Tier I instead.

My code is returning the health of -1 when ran on the client but the correct health on the server.

**Comment by Ipsis** [comment]
Moved tier information to a right-click on a placed controller block. This should now display the correct tier. No longer displays in the tooltip - which is client based and was always returning -1.
