### ISSUE TITLE
[1.9.4] Accessability of the factory block

### ISSUE THREAD

**Issue by tommyTT** [Ipsis/Woot#44]
The accessability and function of the factory block should be reviewed, because if I have level one upgrades on both sides and a full block inventory in front of it to output to (e.g. the modular storage from RFTools for wirless transport across dimensions), I have absolutely no way of accessing it.
Either the functionality with the click should be on the controller instead of the factory or the output needs to be on another block (the one right behind the factory doesn't really have a purpose).

**Comment by Ipsis** [comment]
I'll see about interaction with the mob controller giving the effect of interacting with the factory block. I've always tested with chests so I can always access the factory block, so I had not considered this.
