### ISSUE TITLE
Perks

### ISSUE THREAD

**Issue by invaderzer** [Ipsis/Woot#441]
Hi I have built the wisdom perks and put the in the perk slot but when i open the heart I dont see the perks under the ui "perks" in the heart I wanted to know if I was doing something wrong

**Comment by Ipsis** [comment]
I think I've introduced a bug somewhere regarding perks.
Do you have any other perks on the factory?
From a quick test it looks like it is only registering some of the perk slots on the factory, where it should handle all four.

If you put a perk in each slot then it seems to register all of them.
If some perk slots are not filled then depending on the order it might stop looking them. So you could try swapping the perk onto different slots.
It looks like if you fill the perk slots clockwise from the heart then it registers them correctly.

**Comment by invaderzer** [comment]
I see what you mean now I put the perks in clockwise and they all worked before i just had 1 slot filled i get that now. Also if I wanted to use a upgraded perk do I need a higher tier factory? If I also wanted to use another mob controller how do i go about adding that or is it added with higher tier factory? The current factory im using is Theoricus 2. Thank you for the answers as well helped greatly

**Comment by Ipsis** [comment]
Every factory - apart from the first one - accepts four perks and four mob controllers. The level of perk and controller that are accepted depends on the factory tier.
They are described in the Woot manual in the "Factory Tiers" section. (Patchouli-based book)
IIRC - Tier II - 4 x Perk I, Tier III - 4 x Perk II, Tier IV,V - 4 x Perk III

There are primary and secondary controller base blocks in the factory on which you can place controllers.
Primary controller is the one below the hearts and must always be present.

The perk issue - I think if you break and replace the heart then it will find all of the perks, regardless of order. That at least is what I'm seeing during debugging.

**Comment by Ipsis** [comment]
1fe023c5b95ce6bd5fb74f073edd5b65c4103956

**Comment by invaderzer** [comment]
I see what you are talking about now I am blind thank you very much for the help
