### ISSUE TITLE
Shard Kills Issue

### ISSUE THREAD

**Issue by The-Tarkol** [Ipsis/Woot#442]
I set the "Shard Kills" to 1, but it looks like that may not be reflecting correctly? I've got someone on my server testing with other mobs currently, but the first one he tried (Ender Dragon) is requiring 5 to trap.

In addition to this, we've killed the dragon 4 additional times, but none of them have registered in the shard. Is there a command I can use to directly give a programmed shard?

**Comment by Ipsis** [comment]
I'll need to try the Shard Kills to see why it is not having any impact in the game.

In the meantime:
You cannot give a programmed shard, but you can give a programmed controller.

/woot give <player> minecraft:ender_dragon

(You can tab out the last argument to select any in-game entity you want)

**Comment by Ipsis** [comment]
For the "Shard Kills", could you post the woot-common.toml so I can see how you are setting it. I did a quick test with my woot-common.toml and it changed the number of kills for a simple test with a cow.

The Ender Dragon dies in an unusal way and I have some special handling to prevent one kill counting multiple times. This was ported from the older version of Woot, so could we have some problems.

**Comment by The-Tarkol** [comment]
I think I've figured it out. It worked properly once the config on the server matched the client config.

As far as the Ender Dragon not being registered, I think that may be due to a potential incompatibility with the "Equal Dragons" mod, which treats every encounter with the Ender Dragon as the first. That's my best guess, anyway.

I'll keep that command in mind for the future, thank you so much!

**Comment by The-Tarkol** [comment]
On the topic of the Ender Dragon; where can I modify its loot table? I saw it uses a custom table, but I can't figure out where it's located. Bountiful Baubles adds scales as a drop, so I just wanted to add that in.

**Comment by Ipsis** [comment]
All recipes in Woot are in datapacks including the custom drops.
https://github.com/Ipsis/Woot/tree/1.15.x/src/main/resources/data/woot/recipes/factory
That link shows you the two default custom drops.

Granted I've never tried, as a user, to use datapacks to override/add/change these items, but that was the intended route.

**Comment by The-Tarkol** [comment]
Gotcha, I'll check it out. Thanks!

**Comment by DMCK96** [comment]
This issue has occurred on the latest 1.16 branch. How are server owners supposed to adjust the config if it requires the clients to match? Is this a known issue or intended?
