### ISSUE TITLE
Question on Perks

### ISSUE THREAD

**Issue by The-Tarkol** [Ipsis/Woot#444]
Hello again! Unsure if this is a bug or intended. 

Can perks be stacked? ie multiple "Frenzy" perks, rather than 1 of each perk. 

I tried multiple of the same perk, but the Heart just showed the 1 perk bonus and the other slots appeared empty. Unsure if it's related in any way to the ongoing perk bug, or if it's intended to only be able to use 1 of each perk. Thanks!

**Comment by Ipsis** [comment]
Apart from getting to tier 3 of a perk in the same slot, there is no stacking beyond that.
Unfortunately nothing gained by doubling up on the same perk.

**Comment by The-Tarkol** [comment]
Sorry, thought I closed this. Thanks for clarifying!
