### ISSUE TITLE
Unable to Configure Custom Mob Drops

### ISSUE THREAD

**Issue by zergstarmaster** [Ipsis/Woot#445]
I am trying to configure the Gaia Guardian AKA botania:doppleganger to drop gaia_spirit for version 1.12.2 (current release of Project Ozone 3 Kappa mode to be specific). I removed Botania from the blacklist in the factory_config.json and was then able to create a factory controller for the mob. However, gaia_spirit is not one of the drops the   factory is producing. From what I know about Botania, this drop is player specific when initiating the Gaia fight and is not tied directly into the drops of the mob, hence why it was not automatically found by Woot. I have made several changes to the 5 config files I can find, and none of them have had any effect (yes I made sure to restart the server each time).

1.  To the custom_drops.json I added: 

	{
	  "mobName": "botania:doppleganger",
      "drops": [
	    {
          "drop": {
            "item": "botania:gaia_spirit"
          },
          "sizes": [ 1, 2, 4, 8 ],
          "chances": [ 100, 95, 90, 80 ]
        }
	  ]
    }

2. To the factory_config.json I added:

	{
      "mobName": "botania:doppleganger",
      "configs": [
        {
          "tag": "factory_tier",
          "value": 4
        },
        {
          "tag": "customDropsOnly",
          "value": true
		}
      ]
    },

3. To the factory_ingredients.json I added:

	{
      "mobName": "botania:doppleganger",
      "items": [
        {
          "item": "botania:terrasteel_ingot",
          "count": 1
        }
      ],
      "fluids": []
    }

I also found a loot.json file that was in \woot and not the config folder. I tried modifying that, but it would overwrite my changes on a server restart. I very well may be missing something and this is not a bug, but the Wiki seems to have outdated information about the names of the config files and the values within so I don't think I can trust it. I have attached the 4 config files as well if needed.
[woot_configs.zip](https://github.com/Ipsis/Woot/files/5147095/woot_configs.zip)

**Comment by Ipsis** [comment]
That gave the Gaia Spirit - however the item name is not "botania:gaia_spirit"
It is "botania:manaresource" with metadata of 5. I've included my example custom_drops.json config below. I just bumped it to 100% drop rate for testing.

`

    {
      "mobName": "botania:doppleganger",
      "drops": [
        {
          "drop": {
            "item": "botania:manaresource",
            "data": 5
          },
          "sizes": [ 1, 2, 4, 8 ],
          "chances": [ 100, 100, 100, 100 ]
        }
      ]
    }

`

**Comment by zergstarmaster** [comment]
That did the trick, and it looks like the Terrasteel is also botania:manaresource but with a metadata of 4. Thanks for the help!
