### ISSUE TITLE
Heart Factory not opening

### ISSUE THREAD

**Issue by Maximelie** [Ipsis/Woot#446]
I try to right-click the woot heart factory but nothing happens. It is supposed to open but it doesn't.

Also I crafted a tier 3 woot factory but when I right-click with the hammer it says that it is a factory tier 1.

I really don't know what to do.

**Comment by Ipsis** [comment]
Can you show me a picture of your built factory?
Plus what mob controller are you trying to use?
Which version of Minecraft? (1.12/1.15/1.16)

The Intern has a mode to validate your structure. You can sneak right-click in the air to change modes and then use it on the heart and it will tell you what is wrong with your setup.
