### ISSUE TITLE
Poor/broken interaction with refined storage crafters

### ISSUE THREAD

**Issue by Letoric** [Ipsis/Woot#451]
woot-1.16.2-1.0.0.0
forge-1.16.3-34.1.17
refinedstorage-1.9.7
refinedstorageaddons-0.7.2

When setting up processing recipes for the injection press, if the crafter has multiple to do and inserts multiple of the supplies to craft, the injection press stops working. If you remove the stacks and put them back in 1 at a time, it will begin working. It seems like either it needs to throttle the input it takes, or it needs to work with stacks,, but perhaps it's intended, thus why I listed it as poor/broken. The same thing occurs if I manually put in a stack of items.

**Comment by Ipsis** [comment]
I'll need to try this out, as I had only tested some simple interaction with droppers.
Is that really forge-1.16.3 you are running? (Just curious really as I hadn't tried it yet)

**Comment by AndromeHyperion** [comment]
I've been having this same issue while playing the ATM 6 pack, I used a hopper from which I can get a redstone signal so it's possible to make the refined storage crafter just insert 1 of each item into the injection press
While for me it's just the items with the liquid enchant. the dye ones can be stacked.

**Comment by Ipsis** [comment]
I can replicate this issue with the Liquid Enchant recipes and I have a rough idea of what is going on. It should work - so it is a bug.

There are two slots in the injection press, one is the input stack and one is the augment.
Looks like if the augment stack count is greater than the recipe needs then no valid recipes are found.
But if you have a stack of input and a single recipe worth of augment then it is fine.

I'll try and get this fixed up so it works correctly.

**Comment by Ipsis** [comment]
I've changed the recipe lookup to check for at least the correct number of augment rather than an exact match. That manually allows me to run with both input slots fully stacked.
The only real issue I've come across is the enchanted books recipes now having multiple matches which I'll have to differentiate between - so I'll probably change those recipes a bit.

https://github.com/Ipsis/Woot/commit/2e88f5a62e81a70d9c1450ea66856ea38fdfe2cc

**Comment by Ipsis** [comment]
Fixed in 1.0.2.1
