### ISSUE TITLE
Byzantium Essence

### ISSUE THREAD

**Issue by Rithenar** [Ipsis/Woot#452]
Are there any specific mobs that produce more of the Byzantium essences on an Exemptus (IV) lvl factory? I have gotten more than 1K of each, the Celadon and Cerulean essences, but only 8 Byzantium essences. I know they are rare but the ratio seems awful low.

**Comment by Ipsis** [comment]
Byzantium drop rates are controlled only by the factory tiers and the level of perk you have installed.

Looking at the config I think level 3 perk for the shard drops is sitting at a constant value for all tiers, but I'll need to look at that and possibly bump it. It looks like the Byzantium always has a weight of 1 for all different factory tiers, which isn't correct and should increase with higher tiers.

**Comment by Rithenar** [comment]
Cool. Thank you for the clarification Ipsis.

**Comment by Ipsis** [comment]
Check and the default config is a bit mean:
```
#Weights of the Celadon, Cerulean, Byzantium shard from a Tier 1 factory
t1DropWeights = [80, 20, 1]
#Weights of the Celadon, Cerulean, Byzantium shard from a Tier 2 factory
t2DropWeights = [70, 25, 1]
#Weights of the Celadon, Cerulean, Byzantium shard from a Tier 3 factory
t3DropWeights = [60, 30, 1]
#Weights of the Celadon, Cerulean, Byzantium shard from a Tier 4 factory
t4DropWeights = [50, 40, 1]
#Weights of the Celadon, Cerulean, Byzantium shard from a Tier 5 factory
t5DropWeights = [40, 50, 1]
```

This is from woot-common.toml (factory.perks.tierShard.
As you can see the third weight is 1 for every tier of factory.
So a fair amount would be 1,4,8,12,16.

You can fix this by updating the config file and I'll update the defaults in a future release.

**Comment by Ipsis** [comment]
Default config values bumped  in 1.16.3-1.0.0.0 to be fairer.
