### ISSUE TITLE
Woot factory loot pool UI congestion

### ISSUE THREAD

**Issue by Skriton** [Ipsis/Woot#456]
Describe your issue, what happened?
Woot factory heart has icons and tooltips overlapping with multiple mob controllers installed.

To Reproduce
add enough mob controllers so that the possible loot options exceed the number of slots available.

Expected behavior
Possibly extend the loot window or add pages or scrolling option.

Screenshots
![2020-10-26_02 04 30](https://user-images.githubusercontent.com/36782597/97156994-3fcda480-1756-11eb-82d8-151ca9507cd4.png)

Crash Reports & Logs (Don't paste entire crash reports here.)
No Crash

Affected Version
Pack Version: TNP Limitless 3 ver. 1.6.3
On a server?: Yes
Woot Version: woot-1.16.3-1.0.0.0
Forge Ver: forge-1.16.3-34.1.25

**Comment by Ipsis** [comment]
I'll need to put a couple of extra rows onto the gui. Should be relatively simple.

**Comment by Ipsis** [comment]
Fixed in 1.16.3-1.0.1.0
