### ISSUE TITLE
Crash when clicking the heart

### ISSUE THREAD

**Issue by DinnerBeef** [Ipsis/Woot#457]
my game crashed when I clicked the heart https://pastebin.com/Bw6r1eRL

**Comment by Ipsis** [comment]
Looks like I have a bit of dodgy maths going on in the tank renderer for the heart gui.
I've put some guards round the division in the render to catch any instances of divide by zero.
There is a small possibility of these being called with a zero divider which is probably what you are seeing.

**Comment by Ipsis** [comment]
Fixed (hopefully) in 1.16.3-1.0.0.1
