### ISSUE TITLE
[1.9.4] EnderIO increased head drops makes decapitation upgrade unnecessary

### ISSUE THREAD

**Issue by tommyTT** [Ipsis/Woot#46]
With Ender IO installed the rate of the head drops seems to be increased significantly since they use the mob heads in a few of the recipes. This makes the decapitation upgrade not so useful anymore, since looting seems to do a very good job in itself. I think that needs some sort of adjustment, otherwise there is no reason to use those upgrades.
In my single player world I also have the mod BaublesStuff installed, which adds a few drops from pigmen (a book and a translator) that I feel should only drop from a true player kill, but I'm not 100% sure. Having it run for a few hours I got about 3000 of those items (and you only ever need about 2 of them in an entire playthrough), so I feel that needs some adjustment.

Versions:
Forge 12.17.0.1952
Woot 0.2.0-beta
EnderIO 3.0.0.36_alpha
EnderCore 0.4.0.23-alpha

**Comment by Ipsis** [comment]
I didn't think EnderIO changed any drop rates, unless you killed something with The Ender, which it then increased the head drop rate depending on beheading level of The Ender. Is that what you mean, that if you are using The Ender you will get enough head drops without resorting to the factory? 

The way the mod works, is that all other mods are allowed to process the fake kill that I do with a FakePlayer. They therefore all get the chance to add their own drops. It also means that I don't need to have mod-specific handling. I've had a look at the code for BaublesStuff and in that particular case the spellbook drops from any Zombie Pigman with a 5% chance. The same with the Translator, although it is a user configurable chance.

**Comment by tommyTT** [comment]
No, I'm not talking about the The Ender. I did a quick demonstration and took two screenshots for you:

http://imgur.com/a/vzaZb

The one picture shows the result of a tier 3 factory for zombies with the rate III, mass III and looting III upgrades installed (no decapitation), but no EnderIO. The other picture shows the exact same factory and setup but with EnderIO installed. The result is very different, so they must do something with the mobs. I remember, that in 1.7.10 they for some reason made big changes to the wither skelly that broke a few things, so something must also going on here. Maybe it's EnderCore, their base library that does that? The mobs also dropping their tools is also completely different.

The BaublesStuff thing makes sense, I haven't looked at that. Maybe I will file a bug there, that this should only be a true player drop. But since this mod is a bit broken with balance anyway, I most likely remove it from my pack.

**Comment by Ipsis** [comment]
This is going to take some work to try and work out what is going on.

EnderIO does have the following:

 vanillaSwordSkullChance defaults to 0.05

"The base chance that a skull will be dropped when using a non dark steel sword (0 = no chance, 1 = 100% chance)"

vanillaSwordSkullLootingModifier defaults to 0.05
"The chance per looting level that a skull will be dropped when using a non-dark steel sword (0 = no chance, 1 = 100% chance)"

fakePlayerSkullChance  defaults to 0.5
The ratio of skull drops when a mob is killed by a 'FakePlayer', such as Killer Joe. When set to 0 no skulls will drop, at 1 the rate of skull drops is not modified")

These are hooked into the LivingDropsEvent, which then generates skull drops.

So there is special handling in EnderIO for skull drops from vanilla tools.

Doesn't explain the equipment drops though, still looking at that.

**Comment by Ipsis** [comment]
For the equipment, I think this is just down to RNG over the 100 fake spawns.
eg.
Zombies will have a sword or shovel 0.05% on hard, 0.01% on normal/easy

In my 100 fake spawns, you would need to have a spawn with a sword/shovel/armour for you to have any chance of generating them in the factory.

I don't believe EnderIO does anything with those percentages.

**Comment by tommyTT** [comment]
Makes sense, only testing it once isn't sufficient to blame EnderIO and it only being shovels would attest to your discovery. I think woot should somehow handle the fact that this might happen and a reset of the factory (?) would change the outcome. I think many people would make the mistake of trying to filter out items they don't want, expecting only these items to drop, but a reset completely messes up the processing pipeline because instead of e.g. shovels they now drop armor or swords as well. 

The simples solution would be to include that fact in the description of the mod or the wiki in more simple terms. The wiki tells me about the algorithm you use, but the consequences are not as clear, especially for less technical players. A more complicated solution could be somehow including it into the game, so you can see the possible drops (maybe an included auto filter), but I think that would confuse people even more.

**Comment by Ipsis** [comment]
The increased skull drops are down to EnderIO increasing the chance of a skull drops, which I have no problems with.
Without EnderIO you are down to vanilla mechanics for skull drops which are:
creeper/zombie/skeleton head - charged creeper explosion
wither skeleton head - 2.5% chance on player kill

So the decapitation upgrade allows you to get creeper/zombie/skeleton skulls without the charged creeper requirement.

The equipment drops are down to the way my mod works and how you at the mercy of RNG for those 100 learning spawn drops. In normal mob traps you would have still only have a small percentage chance of those equipment drops, so you still have to plan for extra drops in your filtering.

The difference with this mod is that you wont get items spawning in the world when you processing line jams up. I just stop filling the inventory attached to the factory until you sort it out.

What I want to do is to refresh the loot tables, such that every so often, a configurable percentage 
of the loot table is cleared and some more fake spawns occur, to hopefully give you the full spread of items that a mob can drop.

**Comment by tommyTT** [comment]
Seems reasonable. I still think, an easy example in the wiki would help prevent a lot of questions later on. I guess it is now time to finally look at the zombie generators from EnderIO, since getting the heads for nutrient distillation became very easy :)

**Comment by Ipsis** [comment]
I'll update the wiki with a better explanation of how the loot generation works and indicate that you might not see the same look over multiple game starts, depending on your luck.
