### ISSUE TITLE
[1.16.3] CTD: Cannot get property DirectionProperty

### ISSUE THREAD

**Issue by Flatts3000** [Ipsis/Woot#461]
Modpack: All the Mods 6 - 1.2.1 on a multiplayer server

Crash to desktop after breaking a Layout Guide. Broke the guide successfully a few times and it crashed the last time I broke it.

[https://pastebin.com/NN9uK3uF](https://pastebin.com/NN9uK3uF)

**Comment by Ipsis** [comment]
I think that the tile entity renderer on the client is still being called just after the block is removed from the world. Therefore when it is broken, I try to get the direction that the layout block is facing and it is air so fails.

I cannot replicate the issue, but I'll  put some protection round it to prevent this from causing any issues.

**Comment by Ipsis** [comment]
Fixed (hopefully) in 1.16.3-1.0.1.0
