### ISSUE TITLE
Add Support for HWYLA? (1.16.x)

### ISSUE THREAD

**Issue by SephirothWS** [Ipsis/Woot#464]
In the upcoming 1.0.2.0 version for 1.16.3 you've got it noted that you're updating your The One Probe display for factory blocks. Is it possible to also provide support for HWYLA/WAILA?

**Comment by Ipsis** [comment]
Really depends on how HYWLA works - ie if it is as "simple" as TOP support was. I'll take a look and see what the options are.

...
So after looking at this it is fairly straightforward. I've got the controller and perk blocks implemented so far with little difficultly.  This should therefore be supported, in some form, in the next release.

**Comment by Ipsis** [comment]
https://github.com/Ipsis/Woot/commit/8a94c79fe44da5aaffd30b4de9eddd80f9db3971

Support added and it will be present in the next release of Woot.
