### ISSUE TITLE
Scale of the Summit Perk Item Icons

### ISSUE THREAD

**Issue by SephirothWS** [Ipsis/Woot#465]
Tier 2 and Tier 3 are sharing the same Perk Icons. Is this intended? Or does Scale of the Summit 3 use the wrong item icon?

![image](https://user-images.githubusercontent.com/9165737/100394945-cc88ae00-2ff3-11eb-8fcb-efb188238040.png)
![image](https://user-images.githubusercontent.com/9165737/100394910-a9f69500-2ff3-11eb-864c-899f320da7c2.png)

Woot - 1.16.3-1.0.1.0

**Comment by Ipsis** [comment]
Error on my part - I have the same texture saved for both level II and level III.
Will be fixed in the next release.
