### ISSUE TITLE
[1.16.x] Shard will not clear in crafting table like tooltip suggests

### ISSUE THREAD

**Issue by ArcanoxDragon** [Ipsis/Woot#466]
I hit the wrong mob with a Mob Shard I'm trying to program, and I want to clear it to change mobs. According to the tooltip, I should be able to clear the shard by putting it in a crafting table, but it doesn't appear to be recognized as a recipe. I tried both my in-inventory crafting grid and an actual crafting table, and nothing happens when I place the shard in the crafting grid.

**Comment by Ipsis** [comment]
Looks like when I moved from manually generated recipes to datagen ones, I forgot to add the second recipe for the mob shard that allows it to be cleared. I'll add that back in.

Will be in 1.0.2.0 release when it is made.
