### ISSUE TITLE
Slime other than small generate no loot

### ISSUE THREAD

**Issue by SephirothWS** [Ipsis/Woot#467]
![image](https://user-images.githubusercontent.com/9165737/100528893-86b81b00-3196-11eb-9c8b-262d20cf3dda.png)
![image](https://user-images.githubusercontent.com/9165737/100528896-8f105600-3196-11eb-8543-de8d1dd2b4bd.png)

It is currently possible to attune a mob shard to large slimes along with small ones. Large slimes produce no loot (As evidenced by Dee's Oracle above), where small ones do. Not sure if this would be a problem with Magma Cubes, but I assume since they're essentially the same base entity, that might be the case there.

Minecraft 1.16.4 - Forge 35.1.4 - Woot 1.16.3-1.0.1.0

**Comment by Ipsis** [comment]
There is custom handling in Woot to ensure that when learning loot drops the size of both slimes and magma cubes is correctly used during spawning. This means that Woot learns via the standard vanilla mechanics and treats slimes and magme cubes as two different entities (small/large) 

ie. Slime balls will only drop from small slimes, magma cream only from large magma cubes.

**Comment by SephirothWS** [comment]
So, large slimes producing no loot is an intended behavior?

**Comment by Ipsis** [comment]
Yes. Vanilla mechanics do the same.
Of course if another mod adds a real drop to a large slime then that will be generated.
You are free to add custom drops for the large slime if you want to override this.
