### ISSUE TITLE
Injection Press doesn't function when multiple items inserted

### ISSUE THREAD

**Issue by Based199** [Ipsis/Woot#468]
![image](https://user-images.githubusercontent.com/32063145/100547060-9dec1c80-3219-11eb-9483-ab5ba0499ad0.png)

note that it will function if only 1 set of items is inserted.

**Comment by SephirothWS** [comment]
#451 - Already being worked on.

**Comment by Based199** [comment]
oh i didn't realize it was already reported, i'll go ahead and close this one then.
