### ISSUE TITLE
[1.9.4] Factory sound while being deactivated with redstone

### ISSUE THREAD

**Issue by tommyTT** [Ipsis/Woot#47]
When the factory is formed but deactivated, the sound of the factory should not be playing. A config option to disable the sound all together would also be appreciated. An in-game solution would be to click a piece of wool onto the controller like you do in Botania.

Versions:
Forge 12.17.0.1952
Woot 0.2.0-beta

**Comment by Ipsis** [comment]
This is a bit strange. I didn't add any sounds to the factory. Could you tell me what kind of sound you can hear.

**Comment by tommyTT** [comment]
This is very strange, indeed. I don't recognize the sound, so here is a short video demonstration https://youtu.be/uxkhgOW9M4s

I also installed RFTools version 4.51, McJtyLib 1.8.7 and have JEI 3.4.3.207.

**Comment by Ipsis** [comment]
I've heard that sound before!
It happened in a creative world, in peaceful mode and sounds like a small slime landing.
I'll need to see if I can recreate with just my mod in place.

**Comment by tommyTT** [comment]
I've uninstalled RFTools so only Woot is there and the sound still happens. I also switched the game difficulty to hard, but nothing changed. You're right, the slime landing sounds similar.

**Comment by tommyTT** [comment]
Weird thing getting even weirder: I let the factory run to demonstrate something for the other issue and after a while it suddenly stopped playing the sound.

**Comment by Ipsis** [comment]
I think I know what it is. It is the fake spawning that is causing it. It stops after all the fake spawns have occurred for that particular mob/looting level, which will be 100 I think. I can turn it on and off in my dev environment by turning on and off the fake spawn.

I will have to dig about to see what I can do about turning it off!

**Comment by Ipsis** [comment]
Finally tracked down the sound.

Basically when the FakePlayer is called to kill the fake entity, I have to equip it with an iron sword with the correct looting level, which will cause it to drop the appropriate loot.

The sound you are hearing is the sound of the FakePlayer equipping his sword!

I'll see if I can change this, such that it only equips the item when the looting level is different from the previous level. However this will only reduce the frequency of the sound being played, not remove it completely, This is mainly because the one fake player is shared between all the factories.

**Comment by tommyTT** [comment]
Nice. From what I understand, the whole sound handling in 1.9 leaves a lot to be desired... I tried out a sound muffler from extra utilities 2, but that didn't change anything. If it only happens some of the times I don't think it is a problem, but in the future I will build the factory away from my main work area, just to be safe.

**Comment by Ipsis** [comment]
It might be possible to create 3 fake players, each equipped with one of the looting levels and then use that. That would hopefully completely remove the sound effect as after the game starts, the equipment would never change.
