### ISSUE TITLE
[1.16.4] Perk recipe errors with Industrial Foregoing

### ISSUE THREAD

**Issue by YOYOK9** [Ipsis/Woot#471]
Not sure If this has been posted or not, couldn't find anything in the initial search about it. Any who, there seems to be a crafting issue / confusion within the guide book. The industrial foregoing perks are un-craftable while the mod is in the pack.  However, when I look at them in the guide book it states otherwise, well sort off. 
Tested in creative mode to make sure cards still work: they do. Recipes for the 2 in question make the Stoke the Boiler Perk: also tested.

All screen shots are from their respective guide book pages. 
1. Pressing Engagement show stoke the boiler as the output: https://puu.sh/GWKa8/148e4b4200.png
2. Stoke the oiler seems fine on its own page: https://puu.sh/GWKgr/7b759547bc.png 
3. Tumbling Doll of Flesh shows the boiler as the output again: https://puu.sh/GWKhr/166beca4b9.png

Something else I noticed is with the perks each new upgrade changes the colour of the perk symbol. The doll of Flesh and Pressing Engagement stay the tier 1 colour: https://puu.sh/GWKiM/70ff1328b6.png

Mods & Versions:
MC: 1.16.4
Forge: 35.1.11
Woot: 1.16.4-1.0.2.1
Industrial Foregoing: 1.16.4-3.2.5-74675d6

**Comment by Ipsis** [comment]
Perk textures when placed:
A mistake on my side as I'm incorrectly using the same model for when placed on the factory for each perk. 
TOP/Hwyla will show it find but visually it is incorrect.

I think the recipes for those two are just wrong.
From a quick look at those images, they are all producing efficiency perk items, so the duplicates are probably being dropped on boot as invalid.

I'll get these patched up and push out a new 1.16.4-1.0.2.2.

**Comment by Ipsis** [comment]
Fixed in 1.16.4-1.0.2.2 which is now available on CurseForge.
I've manually crafted both set of perks with I/F installed, so it should all be good now.
