### ISSUE TITLE
Sliem Large

### ISSUE THREAD

**Issue by Skar78** [Ipsis/Woot#473]
ATM6 1.3.3 here with woot 1.0.1.0

Not sure if it is wanted behavior that you must capture Slime [small] for drops, thought better mention it here.

**Comment by Ipsis** [comment]
Vanilla Minecraft only drops slimes from small slimes so Woot only learns them from that specific size.
When loot learning I spawn slimes and magma cubs with a specific size, just to cover any other mod added drops.
eg. if a mod adds slime pearls only to large, then you would need to capture a large.
