### ISSUE TITLE
Confusing Tooltip, Shard Perk

### ISSUE THREAD

**Issue by crioll** [Ipsis/Woot#474]
Hello,

Minor inconsistency in tooltip. When I click on one of the Essences in JEI it says "Generated from the factory with the Shard perk installed". But the Scale the Summit perks calls the essences. Which now that I figured it out makes sense but when you don't it's confusing.

My suggestion would be to change the tooltip text from "Shard perk" to "Essence Shard perk" and it'd help guide new players to the correct perk.

Thanks, have a good day.

**Comment by Ipsis** [comment]
Couldn't find it for a minutes - but I found the text you are referring to.
I had a big rename a few versions ago and the old naming scheme still has some usage that I've missed.

I'll update that text to refer to the "Scale The Summit perk"

**Comment by Ipsis** [comment]
https://github.com/Ipsis/Woot/commit/1b7004ae1cabed9663d31408daeae69512bb1a20
