### ISSUE TITLE
Conatus Fluid enable/disable config request

### ISSUE THREAD

**Issue by Shadowfire86** [Ipsis/Woot#475]
I understand you may want to move away from just RF to power your mod, but the fluids are rather troublesome to automate and some people prefer a set and forget kind of mob spawner. So as a compromise maybe include a config option to switch between the fluid method and an RF method? Temporarily have Creative Conatus fluid tank attached to an ender tank to bypass this issue on my server.

**Comment by Ipsis** [comment]
There is no longer any support for calculating or balancing RF costs for the mobs. So unfortunately I cannot support both RF and fluids. The RF costs were also getting completely out of hand.

If you do want and set and forget method. Then the simplest thing would be to add a VAT recipe for water+easy resource-> conatus. That then bypasses all the multi-step fluids process. 
I've given an example below of coal, but it could be any resource - even cobblestone it you really wanted.

```
eg
{
  "type": "woot:fluidconvertor",
  "catalyst": {
    "item": "minecraft:coal"
  },
  "catalyst_count": 1,
  "input": {
    "fluid": "minecraft:water",
    "amount": 1000
  },
  "result": {
    "fluid": "woot:conatus_fluid",
    "amount": 5000
  },
  "energy": 1000
}
```

**Comment by Shadowfire86** [comment]
Fair enough. Thank you for taking the time to reply
