### ISSUE TITLE
injeciton press broken and cheesable

### ISSUE THREAD

**Issue by TheOne20001** [Ipsis/Woot#477]
I am playing in Direwolf20 1.16 pack, and the injection press will perform the recipe regardless of the amount of liquid it has. Therefore I am able to perform this recipe with only 500ml of liquid and then produce 3 lvl1 enchanted books from it. Thus tripping my books each time.

![image](https://user-images.githubusercontent.com/476475/103324739-03dce700-4a06-11eb-9762-7c4cad33032f.png)

**Comment by Ipsis** [comment]
Looks like I'm checking for the fluid being equal and not also checking the actual amounts are valid for the recipe.

**Comment by Ipsis** [comment]
All recipes for both enchant fluid and pure dye tested in the updated injection press.
