### ISSUE TITLE
Woot farm not listing perk 3 upgrade in perks

### ISSUE THREAD

**Issue by danriduk** [Ipsis/Woot#479]
I have upgraded my 'Scale The Smmit' perk to level 3, but the heart still shows it at lvl 1, unsure if its a visual thing and is using the lvl 3 perk or not.

minecraft 1.16.4
dw20 1.16 modpack

**Comment by Ipsis** [comment]
Think this is the issue you are seeing - https://github.com/Ipsis/Woot/issues/478
