### ISSUE TITLE
1.16 and pink slime

### ISSUE THREAD

**Issue by kieeps** [Ipsis/Woot#481]
im not sure if i'm doing it wrong or if it's actually a bug but i have a Magister woot farm with lvl 3 Tumbling doll of flesh but i get 0 pink slime, i do get liquid flesh though but no pink slime.

The pack i'm playing is the DW20 1.16 (1.2.0) modpack.

**Comment by Ipsis** [comment]
Going to update my DW20 and try this out.
Which particular mob(s) are you using?
A silly question, but I gather you have two output tanks at the exporter(?)

**Comment by MichaelNZ404** [comment]
I just got both out by placing mekanism basic tanks next to the exporter on the latest version of the 1.16 direwolf pack.

**Comment by kieeps** [comment]
> A silly question, but I gather you have two output tanks at the exporter(?)

Not a silly question at all, i had 2 tanks connected with pipes... After reading your question i removed the pipes and now it all works :-P it seems i was overcomplicating it :-)

It works as intended now i guess :-D sorry for npt testing it forst, i just thought i needed pipes to exttact fluids
