### ISSUE TITLE
Bug: Dye Liquifier labels both Blue and White dye with "Blue"

### ISSUE THREAD

**Issue by Cerbrus** [Ipsis/Woot#482]
When I hover over the white bar in the Dye Liquifier, the tooltip says "Blue".

The "WAILA" popup correctly identifies it as "White":

![image](https://user-images.githubusercontent.com/2911988/104121799-6658b000-5341-11eb-8f05-a19d5a2d448b.png)

Sadly, I can't grab the actual tooltip in a screenshot, it doesn't render then...

**Comment by Ipsis** [comment]
I've got my translation string wrong in the gui.
Will be fixed in the next release.
