### ISSUE TITLE
problem whit my factory 1.16.4-1.0.2.2

### ISSUE THREAD

**Issue by DarCuter** [Ipsis/Woot#484]
i finish to build the factory but the game dont let me go in the interface of the heart
![2021-01-13_17 06 05](https://user-images.githubusercontent.com/77416217/104516368-2b18e400-55c2-11eb-990a-bd14cdac2840.png)
![2021-01-13_17 06 27](https://user-images.githubusercontent.com/77416217/104516385-33711f00-55c2-11eb-8545-3062a62c7da9.png)
![2021-01-13_17 06 41](https://user-images.githubusercontent.com/77416217/104516394-379d3c80-55c2-11eb-997b-f9dd512eee90.png)
![2021-01-13_17 11 07](https://user-images.githubusercontent.com/77416217/104516670-bc885600-55c2-11eb-9217-9748eab17df9.png)
![2021-01-13_17 13 45](https://user-images.githubusercontent.com/77416217/104516675-bf834680-55c2-11eb-900b-d33ddd50b2df.png)

**Comment by cainamar** [comment]
you need at least one mob controller on the primary base and a conatus cell at the bottom
