### ISSUE TITLE
Suggestion: increase enchant liquifier internal liquid buffer/allow to dump excess

### ISSUE THREAD

**Issue by cainamar** [Ipsis/Woot#486]
version: 1.16 (dw20 modpack)

I know it's probably not an intended interaction but an in-world mob farm I have going drops a lot of enchanted gear and it works well to get a lot of liquid enchant

the main issue is when one of the items has too many enchant levels and just sits in the liquifier

example:
![image](https://user-images.githubusercontent.com/53030836/104689499-9e108080-56d0-11eb-8c05-7dd771efde31.png)

I have two suggestions for possible solutions:

1. either make the liquifier's internal tank larger
2. or enable an upper limit to how much liquid enchant is gained (e.g. cap it at the current 5k mb so any item can be liquified no matter how strongly it is enchanted)

**Comment by Ipsis** [comment]
Think my default tank capacity is larger (10K) and it has been capped in DW20 to 5K. But then I did update the defaults a short while ago so they might have an older default - granted that doesn't make the problem go away permanently.

I'll go with something similar to your second suggestion:

- max extract 4 x level 5 enchants 
- not to exceed to current Enchant Liquifier tank capacity

**Comment by Ipsis** [comment]
cb637648b4080f53a4e8d7771d567cdff98c8775
Will be in next release.
