### ISSUE TITLE
Rampage 2&3 tooltips are inconsistent.

### ISSUE THREAD

**Issue by Slyklaw** [Ipsis/Woot#488]
Tested with Wither controller in DW20 1.3.1 modpack, Woot version 1.0.3.0.

Rampage 1 works as expected.

Rampage 2 perk tooltip in the controller GUI says "Spawn 4 mobs" and "Wither : 3 mobs". 3 nether stars are exported.

Rampage 3 perk tooltip in the controller GUI says "Spawn 6 mobs" and "Wither : 4 mobs". 4 nether stars are exported.

**Comment by Ipsis** [comment]
I'll need to check the DW20 configs. The tooltip is the standard mob multiplier, however there is a config option to specify a different multiplier for a certain mob. I it possible that they are limiting Wither Rampage 2 to 3 mobs and Wither Rampage 3 to 4 mobs.

Just checked, they have limited the mob count for Ender Dragon and Wither.
Rampage 1 - Ender Dragon 2, Wither 2
Rampage 2 - Ender Dragon 3, Wither 3
Rampage 3 - Ender Dragon 4, Wither 4

**Comment by Slyklaw** [comment]
Makes sense. Thanks.
