### ISSUE TITLE
Question: How does the Pressing Engagement perk work?

### ISSUE THREAD

**Issue by Lodran** [Ipsis/Woot#489]
It's probably just a documentation issue, but how are we supposed to get the Essence generated by the Pressing Engagement perk out of the factory?

**Comment by Ipsis** [comment]
The export block on the factory can have chests or tanks placed beside it.
For the Pressing Engagement perk an adjacent tank will be filled with essence.
For the Tumbling Doll perk you need two tanks, one for liquid meat and one for pink slime.

I've not actually made it clear in the docs for that specific perk.
I'll add an extra line to the Woot manual for that.

**Comment by Lodran** [comment]
I had tried connecting using pipes, which doesn't work.

**Comment by Ipsis** [comment]
The Woot factory has no internal tanks so pipes wont work. You meed to put tanks beside the exporter block in the same way as the output chests. I think I tried with Mekanism(?) tanks.
