### ISSUE TITLE
Boss mob controller with insufficient materials shuts down all other controllers

### ISSUE THREAD

**Issue by quietust** [Ipsis/Woot#491]
Mod version: 1.16.4-1.0.3.0
Forge version: 1.16.4-forge-35.1.36
Other info: Direwolf20 1.16 pack.

If a Tier 5 Woot farm is built and provided with multiple controllers such that _one_ of them is a Boss which requires input items, then failing to provide those items will prevent **all** other controllers from functioning.

In my case, I tried running a farm with a Wither Skeleton controller and a Wither controller, expecting that the former would gradually produce wither skeleton skulls and allow the latter to consume them (and some soul sand) to produce nether stars. Instead, the farm simply did nothing at all, and once I removed the Wither controller the others started working.

The in-game documentation says nothing about this behavior, so I don't know whether it's a bug or a feature.

**Comment by Ipsis** [comment]
Basically the factory success depends on the recipe (across all the controllers) being satisfied and all the ingredients being present. Woot didn't support this feature before so the documentation is a lacking in this area and needs updated.

I'll add some information to the manual to make it clear that all ingredients must be present.
