### ISSUE TITLE
Ingredient Importer accepts items from Storage Drawers but fails to consume them

### ISSUE THREAD

**Issue by quietust** [Ipsis/Woot#493]
Mod version: 1.16.4-1.0.3.0
Forge version: 1.16.4-forge-35.1.36
Other mods: StorageDrawers 1.16.3-8.2.1
Other info: Direwolf20 1.16 pack version 1.4.0

If a Tier 5 Woot farm with a Boss controller is provided with non-Chest containers adjacent to its Ingredient Importer which contain sufficient quantities of the necessary ingredients, it will spawn the boss mob(s) without actually consuming any of the ingredients.

In my case, I used two 1x1 oak drawers from the Storage Drawers mod, one containing wither skulls and the other containing soul sand. Every cycle, the farm produced nether stars but none of the ingredients were consumed (aside from the Conatus fluid).

Upon replacing one of the drawers with a chest, the ingredients from the chest started getting consumed while the ones in the drawer remained unchanged.

**Comment by quietust** [comment]
It's possible that this has already been fixed in 1.0.3.1, but that version isn't yet available on CurseForge (and there's nothing in the changelog describing such a bugfix).

**Comment by Ipsis** [comment]
I'll need to test with Storage Drawers specifically. I'm using standard mechanics to remove items from inventories, so I'm not sure why Storage Drawers are different.

**Comment by Ipsis** [comment]
Retested this with Direwolf 1.16 V1.6.1 and this still seems to be happening.
And it looks very much like I'm violating the IItemHandler getStackInSlot rules.
I'll need to rewrite this properly as it currently looks like it is a miracle that it works!

**Comment by Ipsis** [comment]
Retested with correct use of IItemHandler.getStackInSlot.
64 soul sand and 64 wither skulls in the T5 factory.
At the end I had 16 nether stars, 0 soul sand and 16 wither skulls.

Fixed in the next release of Woot.
