### ISSUE TITLE
[1.9.4] Tier 4 factory

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#50]
New factory tier allowing more upgrades, also costs more RF per tick to run.
Size of 11x11 and probably cap stones created with nether stars.

This is probably where the Ender Dragon would go and maybe move the Wither Boss into here as well.
So you would have to kill the Wither Boss the correct number of times to get the nether stars to build this tier.

This tier would probably be the one that would allow two mob controllers.

**Comment by Mohron** [comment]
I'd love to see another tier or two just given the fact that the more mods you add the harder it becomes to balance all the mobs within just 3 tiers. But looking at just vanilla, a tier for the bosses would be a nice addition.

**Comment by Ipsis** [comment]
Current plan. The next release, along with all the other changes, will add tier 4. By default tier 3 will be needed for Enderman, Wither Skellys, Ghast and tier 4 will be the Wither boss. Of course that is all configurable in the config files.
