### ISSUE TITLE
Factory doesn't work all the time

### ISSUE THREAD

**Issue by Rithenar** [Ipsis/Woot#502]
On 1.16.5 using 1.0.3.0. I have a Tier V factory with lvl 3 Perks and 3 controllers.  I can see the progress bar going to 100% and no loot is produced. Sometimes after 10-12 cycles it will produce loot and goes back to nothing for a few cycles. I have an Ultimate Conatus cell so it has enough as it requires 10752 mB. I can see it using the Conatus fluid every cycle though.
![image](https://user-images.githubusercontent.com/9939332/107276002-12141f00-6a18-11eb-859f-f02ac78b1b21.png)

![image](https://user-images.githubusercontent.com/9939332/107276056-1c361d80-6a18-11eb-94bc-c894eb08c449.png)

![image](https://user-images.githubusercontent.com/9939332/107276089-26581c00-6a18-11eb-9a1d-9f93a0adbda9.png)

**Comment by Ipsis** [comment]
Some mods need ingredients provided in a chest beside the importer.
Are you providing the correct amount of wither skulls and soul sand?

**Comment by Rithenar** [comment]
Yeah, I thought all the other mobs would spawn if the withers had no ingredients. Since then I have a constant flow of skulls and soul sand coming so the issue is gone. Thanks Ipsis.
