### ISSUE TITLE
[1.16.5] Empty tile when creatures share a drop

### ISSUE THREAD

**Issue by OscarAblinger** [Ipsis/Woot#505]
When I have a witch (primary) and a creeper (secondary) mob controller a tile is left empty in the GUI:

![image](https://user-images.githubusercontent.com/25868587/108249307-35944380-7155-11eb-85e3-e0056342e816.png)

I assume this is because the tile is reserved for the gunpowder originally (as the creepers drop order alone is gunpowder then the gland).

The tooltip for the gunpowder correctly shows the drop chances for both mobs.

Technical information:
Mincraft: 1.16.5
Woot: 1.16.4-1.0.3.0
Other relevant mods: Reliquary (added another drop to both the creeper and the witch)
Complete mod list: See Direwolf20 1.16 mod pack

**Comment by OscarAblinger** [comment]
Actually not sure if this merging is intended (I like it, though, so I assumed it's a feature), so here is a screenshot of that, too:
![image](https://user-images.githubusercontent.com/25868587/108249923-f4506380-7155-11eb-9b57-504986b35a40.png)

**Comment by Ipsis** [comment]
I merged together the items to try and make the loot pool display a bit cleaner, but clearly something isn't working quite right. I'll try with the two mobs you show and see if I can work out what is going on.
The merged tooltip is supposed shown each mob individually, although it could be a bit cleaner.

**Comment by Ipsis** [comment]
This was relatively simple. I was still treating the slot as filled when the stack was merged with a previous slot. When the next stack was added it couldn't use the filled (empty) slot.
Fixed in the next release.
