### ISSUE TITLE
[Documentation Clarification] Conatus cell / fluid interactions

### ISSUE THREAD

**Issue by novantis** [Ipsis/Woot#506]
I'm currently using FTB direwolf20 1.16. As it stands, the Conatus cell doesn't seem to play nicely with many other fluid systems featured in the modpack. It's not documented which fluid systems will and won't work in the in-game Woot manual.

I've only been able to get Conatus fluid into the Conatus cell via mekanism pipes. Exporter from Refined Storage doesn't work at all as do other pipes I've tried. 

I'm also trying to get industrial foregoing essence out of the factory. Pipes out of the Conatus cell only seems to draw out the conatus fluid, so I'm not sure how to get access to this essence, especially as the mekanism pipes don't connect to the export/import blocks.

Could we get some clarification on the available behavior for fluid in/out with respect to the common fluid pipe mods?

**Comment by Ipsis** [comment]
The Conatus cell uses the standard Forge fluid interface.
For IF Essence and all other outputs from the factory, they work in the same way as loot chests.

The Woot factories have no internal storage so all outputs depend on a storage block of the appropriate type beside the exporter.
For item output then a chest-style block beside the exporter.
For fluid output then a tank-style block beside the exporter - more than one if there are multiple fluids.
(The fluid output for the two IF perks is described in the guide book on the perk page)

I would expect any mod that supports the Forge fluid interface to work with Contaus cells, however I've not validated which ones work and dont work.

**Comment by Ipsis** [comment]
- Conatus Cell Output
  - Mekanism mechnical pipes in pull mode will extract fluid
  - Refined Pipes fluid pipe with extractor will extract fluid
  - Cyclic fluid cable wrenched to extract will extract fluid

- Conatus Cell Input
  - Mekanism mechanical pipe will insert fluid - as long as there is fluid in the pipe
  - Refined Pipes fluid pipe will insert fluid - as long as there is fluid in the pipe
  - Cyclic fluid cable will insert fluid - as long as there fluid in the pipe

I had no luck with Immersive Engineering pipes.
Refined Storage allowed me to connect an external storage connection and showed the tank in the fluid grid.
