### ISSUE TITLE
T4 farm not accepting modules

### ISSUE THREAD

**Issue by the-creamster** [Ipsis/Woot#507]
As the title states; the T4 farm isn't accepting T3 modules but will accept T1 ones despite the guide book saying it can accept T3 modules. You aware of this??

FTB Custom Client Direwolf20 1.16 modpack(latest version)

**Comment by Ipsis** [comment]
Just for my clarification - since I've not seen this issue - are you applying the T1, T2 then T3 module to the T4 farm? It requires all previous module tiers of that type to be applied first.
If you are doing the above can you let me know which specific module is causing problems and I can retry it.

**Comment by the-creamster** [comment]
![2021-02-28_15 09 51](https://user-images.githubusercontent.com/2037833/109408710-c1b92d00-79d7-11eb-80bb-594cf6983a14.png)
![2021-02-28_15 09 58](https://user-images.githubusercontent.com/2037833/109408713-ca116800-79d7-11eb-93fa-3b82fc122dc0.png)

To be very specific if those 2 pictures aren't enough:
- This is my first time playing with this mod but i did properly look into it with current videos on youtube and referenced the T5 farm of another player on server at the time of reporting just to make sure i wasn't doing something wrong(the T5 one on server has 4 different T3 modules installed so hence my confusion).
- Secondly i just now read through the relevant sections of the book and there is zero mentions of "the previous tier must be installed for the next higher one to work"(some of the videos i watched were by testing conclusive that having multiple of the same type does nothing extra).

So the conclusion i obviously came to was "it's bugged" and thus here i am. Any further thoughts now??

**Comment by Ipsis** [comment]
The bottom picture shows what is wrong - only level 1 perks can be added to an empty upgrade block.
For example to add Scale The Summit III to a perk block.

- apply Scale The Summit I to the empty perk block
- apply Scale The Summit II to the  perk block with Scale The Summit I
- apply Scale The Summit III to the perk block with Scale The Summit II

The reference to multiple copies relates only to two perk blocks with the same perk applied.

This is documented in the guide at 

- TLDR 
  - Must apply all the previous tiers of a perk to use higher tier ones".
- Perk Slot
  - An empty PerkSlot can take any level I perk. All previous levels of perk must be applied before the next level is accepted

The chat message also provides feedback as to why something will not apply.

Unless a video shows the process of applying the perks, then it will look like they have applied a T3 perk directly to an empty perk slot, so I can see why that could be somewhat misleading.

**Comment by the-creamster** [comment]
Oh, so you mean you install all 3 tiers of module to the same block consecutively; that makes so much more sense now; but yes it is a little misleading/not prominent enough to the player when reading the book unless you study it in-depth.

Thanks for the clarification on this especially being new to the mod and all given some procedures even in videos not being fully displayed to the person watching.
