### ISSUE TITLE
The mob farm cannot handle "Slime [Large]" controllers

### ISSUE THREAD

**Issue by JeljoGb** [Ipsis/Woot#508]
I created a controller from large slimes, but it does not populate a loot pool.
When I programmed the shard on a small slime, it did work.
I am now stuck with an unusable large slime controller.

**Comment by Ipsis** [comment]
Large slimes do not drop any loot - only small slimes drop slime balls - as per vanilla mechanics.

However I split large and small slimes, as there may be mods that have large slime specific drops  eg. ModX might have only large slimes drop a "ModX slime pearl".

**Comment by JeljoGb** [comment]
Oh that makes sense.
I just didn't know there was a distinction.
