### ISSUE TITLE
Fabric support?

### ISSUE THREAD

**Issue by Forbidden-A** [Ipsis/Woot#509]
Any plans on supporting the fabric modloader?

**Comment by Ipsis** [comment]
Unfortunately if is difficult enough to find the time for the Forge support that I just cannot do Fabric as well.
Sorry.

**Comment by Forbidden-A** [comment]
> Unfortunately if is difficult enough to find the time for the Forge support that I just cannot do Fabric as well.
> Sorry.

No problem, thanks for the response.
