### ISSUE TITLE
[BUG] Rampage Perk breaks Wisdom Perk

### ISSUE THREAD

**Issue by Gamogamer** [Ipsis/Woot#510]
As the title says. After installing the rampage perk the farm no longer produces any experience shards/splinters.

Latest version of Direwolf20 1.7.0, MC1.16
comes with woot-1.16.4-1.0.3.2.jar

**Comment by Ipsis** [comment]
Can you tell me the following please:

- Mobs used
- Level of Rampage
- Level of Wisdom

I've tried this locally and not seeing any issues.
eg. With a Wither and Tier I perks I end up with 6xnether stars, 33 shard, 3 splinters

**Comment by Gamogamer** [comment]
- Mobs: Blaze, Enderman, Witch, Wither Skeleton (had a cow in there before too)
- I am using Level 3 Wisom 
- Tried combining it with Rampage 1 and 3

**Comment by Gamogamer** [comment]
So I tried fiddling with it again and I got it to work by putting wisdom in again. Then it was working for a day or two. And now I just noticed I am out of conatus fluid again. After replacing the shards with Redstone in that process I am not getting any experience shards anymore again.

**Comment by Ipsis** [comment]
I've built a tier V factory with the mobs you mention and level 3 wisdom, level 1 rampage and a creative conatus cell. Unfortunately I'm getting lots of experience shards in that setup.
Checking the code, as long as you have Conatus fluid to finish the spawning, then the loot items are added to chests first, then the XP shards (if correct perk), then the tier shards (if correct perk).
So I'm at a bit of a loss as to why you are seeing. 
Does the GUI report the correct xp perks being present when they stop being generated?

**Comment by Gamogamer** [comment]
Yea the gui checked out. Does that check in the code check for fluid again? Or do these additional perks even consume fluid?

**Comment by Ipsis** [comment]
The factory needs Conatus fluid to run.
When the spawn time expires then it checks that enough Conatus fluid exists and if it does it then generates loot and processes all perks eg. experience shards, tier shards etc. On the higher tier mobs, you therefore have time to produce that fluid before it is required and not stall long spawn timeouts because you haven't got it ready yet.

If there is no fluid at the end of the spawn time then nothing happens.

**Comment by Gamogamer** [comment]
As I can't really re-verify this anymore,  I suggest we chalk it up to user error and close this. Mightve just been something out of mind
