### ISSUE TITLE
Machine keeps processing even when full, using resources, but voiding produced stuff

### ISSUE THREAD

**Issue by WhitePhant0m** [Ipsis/Woot#512]
[![Image from Gyazo](https://i.gyazo.com/8c3149804cadb17702477223509e2af8.gif)](https://gyazo.com/8c3149804cadb17702477223509e2af8)
version: 1.16.5 - 1.0.4.1

**Comment by Ipsis** [comment]
I've recreated that in my dev environment and I'm seeing the same issue.
Not sure why yet, but definitely a bug.
