### ISSUE TITLE
[Request] Ether gas from Industrial Foregoing 

### ISSUE THREAD

**Issue by YOYOK9** [Ipsis/Woot#513]
Request/Question
Wondering if it would be possible to add a perk for the Ether gas that is generated from withers using the laser fluid drill? The drill currently does 10mb per cycle. Be kinda neat if it could be collected as well when a wither is killed by woot. 

I have tried to add it manually with a data pack but not sure how to add a fluid as a factory output result. If even possible?

**Comment by Ipsis** [comment]
The only way - without me adding a specific perk - would be to add a custom drop for a bucket (or other fluid container) of Ether gas.
Adding a new perk is certainly possible, there are a few extra perks that I need to add.
Not promising anything but I'll keep it in mind.

**Comment by YOYOK9** [comment]
Thanks for the quick response, I will give the bucket method a try. As for the perks sounds good :) hopefully it eventually becomes one

**Comment by Ipsis** [comment]
I've got the basic of this in and working so hopefully I can roll it into the next release of Woot.
It generates 10mb per Wither (with slightly more mb on higher tiers).
Running with the other IF perks you can generate all three fluid outputs.
Just need to add the localisation and some recipes.

**Comment by Ipsis** [comment]
20ed47216040d3a0af75f01def60141ecc3991b3

**Comment by Ipsis** [comment]
In 1.0.5.0
