### ISSUE TITLE
custom intergration for Ender Dragon

### ISSUE THREAD

**Issue by tyler489** [Ipsis/Woot#518]
I understand that the ender dragon cannot be "learned" but would it be possible to have different preprogramed drops when certain mods are installed by default? specifically Green hearts from baubly heart canisters Dragon sinew from silent gear and dragon scales from quark?

**Comment by Ipsis** [comment]
You can use datapacks to modify the custom drops., however I have previously supported Draconic drops by default.
I'll take a look at Baubly Heart, Silent Gear and Quark and see about adding their dragon based drops.

**Comment by Ipsis** [comment]
Quark: 1xDragon Scale on death. (quark:dragon_scale)
Baubly: Dragon 1% chance
                    if (random.nextDouble() < ConfigHandler.greenDropRate) {
                        entity.dropItem(ModItems.GREEN_HEART, 1);
                    }

Silent Gear: Not seeing Dragon Sinew anywhere - could you give me the full item name of that ie mod:name

**Comment by tyler489** [comment]
my apologies it's Tetra that adds dragon sinew.

**Comment by Ipsis** [comment]
Thanks - tetra:dragon_sinew. The latest code for Tetra is not an Github, but there is a config log change indication "buff dragon drops to 2 sinew" so I'll go with that.

**Comment by Ipsis** [comment]
![image](https://user-images.githubusercontent.com/5602759/118356896-3a5b6e80-b56f-11eb-9fae-5d126144f8dc.png)

**Comment by Ipsis** [comment]
Dragon Sinew - 100% drop chance of 1
Dragon Scale - 100% drop chance of 1
Green Heart - 1% drop chance of 1

That keeps to the mod authors intended drop rate - ie looting has no impact.

**Comment by tyler489** [comment]
huh i believe that when BHC says 1. that means 100% as ive never failed to get a green heart from the dragon or a yellow heart from the wither.

**Comment by Ipsis** [comment]
You are correct, nextDouble < 1 will always be true as nextDouble return a number between 0.0 and 1.0 - I incorrectly read that as 1%. I'll fix that up.

**Comment by tyler489** [comment]
Thank You.
