### ISSUE TITLE
Items with NBT break after certain conditions.

### ISSUE THREAD

**Issue by tyler489** [Ipsis/Woot#519]
I'm not sure on the full conditions but I'm playing Stacia's expert 1.16.5 pack. I noticed that the enderdragon did not have green hearts (forgot it was hard coded) so I asked our server admin to flush the enderdragon loot table.
He ran the command woot simulation flush minecraft:enderdragon

Today I logged in and all the items from reiquary and rftools were broken. Previously mobs would give their mob fragments. Skeleton would give skeleton fragments phantom would give phantom fragments etc... now all mobs give pig fragments .
enderman were previously giving 2 dimlets. a plains biome dimlet and another random dimlet. now they are giving unidentified dimelers that cannot be used. I speculate that flushingg the ender dragon table somehow deleted NBT off these items in other loot tables. However this may have happened because of the server restart as well. I am not sure.

**Comment by Ipsis** [comment]
Could you let me see the loot.json file from your server. That will give me a better idea of what items have been learned.

**Comment by tyler489** [comment]
Where might I find this file?

**Comment by Ipsis** [comment]
In the main instance directory there will be a directory called woot that has the loot.json.
The directory is the same place with the logs/mods/saves directories.

**Comment by tyler489** [comment]
https://sverd.eu/loot.json Enderman or phantoms are a good example Enderman dimlets have no data and Phantoms charm fragments also have no data.

**Comment by Ipsis** [comment]
Both Enderman dimlets and the Xreliquary charms both have NBT which means that Woot cannot really generate them. When they are first learned and before the server is restarted, they will probably generate correctly. But when I save the NBT information will vanish - simply because they are so many variations that the loot.json would be massive.

**Comment by tyler489** [comment]
So is this a Won't fix?

**Comment by Ipsis** [comment]
Pretty much - though I am looking at something for Xreliquary mob charm fragments - just trying to get the NBT data to work correctly as it is just an entity name I need to store.

**Comment by Ipsis** [comment]
https://github.com/Ipsis/Woot/commit/feb044f02c46ccf0f995858cd4c8ff83ca5d3d08

**Comment by Ipsis** [comment]
1.16.5.1.0.7.0 has Mob Charm Fragments fixed .... I hope.

**Comment by tyler489** [comment]
> Pretty much - though I am looking at something for Xreliquary mob charm fragments - just trying to get the NBT data to work correctly as it is just an entity name I need to store.

I got to say for a mod that prides itself on being "server friendly" not being able to get certain mob drops that have nbt data or getting drops with no data is BAD. While reliquary and Rftools have a default "no data" state other mods may not and will crash the server or the client. I remember in 1.12 this happening with a few different mods that relied on nbt data. Please reconsider leaving the nbt data for all mob drops on it and not deleting it. Even if it does make that file huge it still means that players can get the drops they need with woot rather than relying on other methods that leave mobs and items in the world.

At the very worse if you refuse to support nbt data then you should delete any item from the drop table that has nbt data (minus reliquary fragements) as you have no way of knowing what negative effects these items may have on the game.

**Comment by Ipsis** [comment]
Woot is not perfect - I never claimed that it was.

I am not refusing to support nbt, it is not feasible to support it. As I learn of specific drops that will cause issues then they will get blacklisted like dimlets. I do not delete nbt data - it is never saved in the first place.

Any player of the mod also has the option of blacklisting specific mods or items via the config.
When I can support nbt - such as in the Reliquary instance - I will.
