### ISSUE TITLE
Woot causes worlds to be flaged as using experimental settings.

### ISSUE THREAD

**Issue by The-Arcanian** [Ipsis/Woot#521]
Creating or loading a world with Woot installed causes said world to be forever flagged as using experimental settings. Even if Woot is removed.

Woot-1.16.5-1.0.6.0
Forge-36.1.2

**Comment by Ipsis** [comment]
AFAIK this is standard when custom dimensions have been used when creating the world. I think some of the modpacks use an override to make it go away.

**Comment by The-Arcanian** [comment]
1.16 added the Custom world type, which if what you saying is true, then I guess every dimension using mod has plugged into for ease of development. And yes, there is [Shutup Experimental Settings!](https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings), but having to install one mod so that another is not annoying is very irritating, especially since it is an irrevocable flag. But I guess this is more of a Forge issue than any particular mod.
