### ISSUE TITLE
Ritual of The Martyr Not Drawing Life Essence

### ISSUE THREAD

**Issue by Maldorrin** [Ipsis/Woot#524]
I'm using Woot and Blood Magic in 1.16.5 and the tier two Woot Factory with a tier one Flayed perk isn't outputting Life Essence to a tank nor nearby altar while running. I have the Ritual of the Martyr situated above the factory and activated, and the Altar should be within range. I have tried moving the ritual and factory about, but can't seem to get it to work. Help would be greatly appreciated.

**Comment by WillisShek** [comment]
I am facing the same issue as well. Have you solved it?
