### ISSUE TITLE
ingredient importer wont import and entire factory shuts down 1.16.5-1.0.6.0

### ISSUE THREAD

**Issue by falizure** [Ipsis/Woot#525]
im playing tnp limitless 3 and i have set up a tier 5 woot farm successfully, it was running every controller i placed on it just fine until i added the wither controller, it now says it needs required ingredients but wont take them in from adjacent blocks, i have a hopper trying to push in, a storage drawer and a chest all 3 have skulls and soul sand in them and it wont take any of them it just hits 100% and skips not only producing the wither drops but all other mob drops its supposed to be generating as well.

**Comment by Ipsis** [comment]
When ingredients fail then no mobs drops are generated for any mob in the factory - it is an all or nothing.
Could you post an image of your factory and I'll create the same thing here to test against.

**Comment by falizure** [comment]
![image](https://user-images.githubusercontent.com/20368517/118358337-ec7d4100-b543-11eb-80d6-e010b3ca780a.png)
![image](https://user-images.githubusercontent.com/20368517/118358344-f606a900-b543-11eb-8572-d00e790c4217.png)
![image](https://user-images.githubusercontent.com/20368517/118358370-146ca480-b544-11eb-82a3-07136af3a9db.png)
the wither controller is on back and appears as the 4th 1 on the list, wither skeleton is on front as primary endermen on the right and creeper on the left

**Comment by Ipsis** [comment]
I've created the same setup as your on the same modpack and I have both vanilla chests and storage drawers working on the importer. - this is with the same perk/controller combination that you have.

![2021-05-15_12 49 25](https://user-images.githubusercontent.com/5602759/118359577-05a1e400-b57c-11eb-98c9-6337348c020c.png)

You don't have any mass perks so it should only be looking for "3xwither skull", "4xsoul sand".
I'll ask an obvious question - it is "soul sand" that you have and not "soul soil"? (I know it wont be but I nearly used the wrong one so I thought I would check).

**Comment by falizure** [comment]
im ashamed to admit but ya i was using soil, this is the first pack i have played past 1.12 and im still not used to all the new blocks and textures, sorry for wasting your time

**Comment by Ipsis** [comment]
I'm just glad it was something simple.
The whole soul soil is new to me and they should have maybe made it a little bit more unique in terms of texture.
