### ISSUE TITLE
[1.9.4] Factory not formed when doDaylightCycle is false

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#53]
@tommyTT

So, I figured out the problem I had yesterday with the factory not forming. I updated to the newest version 0.2.0-beta but it wouldn't work and the error log didn't report a problem either. I started a new test world and there I had no problem. I tried a few things and found out, that the problem occurs when the gamerule doDaylightCycle is false. I thought I would let you know, maybe there is some sort of way around that.

**Comment by Ipsis** [comment]
Right I can reproduce this.
The reason is simple. To stop the factory block from checking every time one of its multiblock entries is added, it only checks the structure every second and if it is dirty. It is dirty when a block says hello or goodbye. (I do not scan the whole structure every tick, I just scan when something changes).

However that 1 second timer is checked against getWorldTime, which doesn't move when doDaylightCycle is false.

So I'll try and find some way of fixing that to not use world time.

**Comment by edwardsdean** [comment]
@Ipsis  this issue is present in the 1.10.2 1.40v release

**Comment by Ipsis** [comment]
I'll reopen and make sure I've not undone the fix!

**Comment by Ipsis** [comment]
I've not broken the fix, however a different fix is causing issues.
I need worldtime to increment to stop people using tick acceleration methods on the factory - eg Torcherino, Acceleration Wands.

However this fix is based off the worldtime which of course wont move when doDaylightCycle=false.

I'll try and come up with a solution which works for both scenarios.

**Comment by Ipsis** [comment]
Looks like there are two "world times".
getWorldTotalTime increments per tick
getWorldTime only increments per tick if doDaylightCyle = true

So if I change over to getWorldTotalTime, then both features should start working again.

**Comment by Ipsis** [comment]
Moving this to a new bug, so as not to confuse the issue [#218]
