### ISSUE TITLE
Can't not input the ingredient for ender dragon simulation

### ISSUE THREAD

**Issue by kingdom84521** [Ipsis/Woot#532]
Mod Version: 1.16.5-1.0.7.0
Problem Encountered: Can't not input the ingredient for ender dragon simulation
Situation Describe: I am using the master class simulator, and I'm in creative mode. First, I tried is using Mekanism's cable, and found that there is no place that cable could be connect to. So I tried just put a simple chest next to the importer, but it did not work, too. Also, I can't find any description about what ingredient ender dragon's simulator would need, I found someone says it need end crystal for default, so I only try end crystal for ingredients. I had also tried those mobs which don't need ingredients, and it works well on the same factory.

**Comment by Ipsis** [comment]
When you open the Heart gui it will show you which ingredients you need. They should be played in a chest beside the importer block. When the Dragon is ready to generate loot, it will check the import chest for the items and if they are present it will consume them and then put your drops in a chest beside the exporter block.
Woot needs adjacent inventories for input/output.

**Comment by kingdom84521** [comment]
I fix it at last accidentally, but I still not sure what cause the error. 
And yes, I have tried to put a vanilla chest a the side of the importer box, and also fill some ingredients( end crystal ) in it, but it did not work at that moment.
What I do after I post the issue is: I change the controller to skeleton one which should not need any ingredients, and after testing it was working, I break the controller and change it to the ender dragon one, and then everything just magically fixed.
At first I put the controller on, I cannot see any information about how to get ender dragon's drops, the information I mean is the ingredients and the drop list, I didn't see anything display in those block, so I wonder if there is a instruction of what ingredients I need.
