### ISSUE TITLE
[1.16.5-1.0.7.0] Machine processing speed still low

### ISSUE THREAD

**Issue by ludwigthron** [Ipsis/Woot#535]
Hey Ipsis!

Just wanted to report that the change you wrote about in the latest update is still not correct in the mod config.
"Changed
Slight bump to machine processing speed (20->40RF/tick so recipes finish faster)"

But it says "energyUsePerTick = 20" for every machine such as infuser/squeezer and so on.

Hope you can check so you actually changed it correctly!

**Comment by Ipsis** [comment]
The configs are not updated if they already exist. So you have to delete the existing woot-common.toml and it will generate a new one with the updated values.
So when I delete mine I get the following

[infuser]
	#Energy used per tick (RF)
	#Range: > 0
	energyUsePerTick = 20

Becomes
[infuser]
	#Energy used per tick (RF)
	#Range: > 0
	energyUsePerTick = 20

**Comment by ludwigthron** [comment]
Sorry to ask then but should you deleting the toml not update the lower one to become "energyUsePerTick = 40" ?

**Comment by ludwigthron** [comment]
A new install of TNP 3 and opening the woot-common.toml shows these values
 
 "#Settings for the infuser
[infuser]
	#Energy used per tick (RF)
	#Range: > 0
	energyUsePerTick = 20"

**Comment by ludwigthron** [comment]
Gbergz creator of TNP3 said he has not regenerated the files from woot since he added it to the pack, only updating it to latest version. We can see this issue as closed since the solution was just to regenerate the .toml file.
