### ISSUE TITLE
draconic evolution mod item drop does not work

### ISSUE THREAD

**Issue by rafaelg300** [Ipsis/Woot#552]
when I try to create an ender dragon factory to get the draconic evolution mod items, it doesn't drop even one of the mod items
![2021-10-10_14 17 34](https://user-images.githubusercontent.com/72635140/136706553-d7346cf7-eb44-4374-85c8-e848a706039c.png)
to some configuration I should do? if yes which one? It is like? I know almost nothing about programming

minecraft version: 1.16.5
forge version: 36.2.0
woot version: 1.0.8.0
draconic evolution version: 3.0.16.417

**Comment by zoller27osu** [comment]
Unlike most mobs, whose drops are found by killing them in a test dimension, the Ender Dragon's drops are hard-coded. I assume there's a config somewhere for changing the dragon's drops.

**Comment by Einhornyordle** [comment]
Possible Duplicate, see #544

**Comment by Ipsis** [comment]
Fixed in #544
