### ISSUE TITLE
Head Start not stacking with Rampage?

### ISSUE THREAD

**Issue by zoller27osu** [Ipsis/Woot#553]
(Playing "FTB University 1.16" version 1.2.0, with woot 1.16.5-1.0.8.0)

Specifically for Wither Skeletons, Head Start III usually causes x Wither Skeleton Skulls to drop, where x is the number of Wither Skeleton controllers - this makes sense, as Head Start III gives skulls an 80% (additional?) chance to drop.

However, adding Rampage III (which multiplies the number of Wither Skeletons being "killed" by 6) has no noticeable effect on the number of Wither Skeleton Skulls dropped - whereas I would expect the average number of skulls dropped to also be multiplied by 6.

As far as I remember, they did stack as I would expect back in 1.0.6.0 (FTB Endeavour 1.4). The mod config for the pack looks completely normal:
[woot-common.txt](https://github.com/Ipsis/Woot/files/7404040/woot-common.txt)

Please advise.

**Comment by Ipsis** [comment]
Looks like the code for the skull generation doesn't use the Rampage mob count. It just runs the head perk per controller.
