### ISSUE TITLE
[Crash] Ritual of the Martyr crash on all the mods 6

### ISSUE THREAD

**Issue by TheInfamousAlk** [Ipsis/Woot#557]
Upon activating my "ritual of the martyr" with an activation crystal, the server crashed. I had a blood altar a few blocks above the ritual and a woot multiblock maybe 15 blocks away. Now the server also crashes upon world load. 
[crash.txt](https://github.com/Ipsis/Woot/files/7777501/crash.txt)

**Comment by MarioCakeDev** [comment]
It seems like woot is using the old method `getBlockPos()` from `IMasterRitualStone`. This was renamed to `getMasterBlockPos()`

**Comment by MarioCakeDev** [comment]
Duplicate of #550

**Comment by TheInfamousAlk** [comment]
TRUE thank you
