### ISSUE TITLE
Occasional Startup Crashes (ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by Freebi85** [Ipsis/Woot#561]
Hey there :)

Now and then woot crashes on startup during the sided_setup event phase.

Minecraft: 1.16.5
Forge: 36.2.22 and 36.2.23
Woot version: 1.0.8.1

Feel free to ask if more information is needed. 😃 

[crash-2022-01-09_15.57.43-fml.txt](https://github.com/Ipsis/Woot/files/7858436/crash-2022-01-09_15.57.43-fml.txt)

**Comment by Ipsis** [comment]
I'm seeing a similar report on another mod (ArrayIndexOutOfBoundsException). I'll see what their fix was and try to understand why it sometimes causes an issue.

For my reference:
Periodic-Table-Reforged/issues/71
sodium-forge/issues/63

**Comment by Ipsis** [comment]
I'll roll that out in the next release -hopefully it makes the problem go away.

**Comment by Ipsis** [comment]
"Fixed" in 1.0.8.3
