### ISSUE TITLE
[1.16.5] Ender Dragon does not drop Dragon Heart(draconic evolution)

### ISSUE THREAD

**Issue by Breniim** [Ipsis/Woot#562]
I have a modpack 1.16.5 to play and I installed the Woot mod and it doesn't drop Dragon Heart from Draconic Evolution, can you help me?
OBS: Sorry if any word is wrong, I used Google Translate to translate, I'm Brazilian '-'

**Comment by Ipsis** [comment]
The Draconic support is currently not in Woot and will be in the next release (1.16.5-1.0.8.2)
