### ISSUE TITLE
[1.9.4] Weapon drops are not stored in chest, dropped on the ground

### ISSUE THREAD

**Issue by Gepett0** [Ipsis/Woot#62]
Hi Ipsis,

me again.
With woot-1.9.4-0.3.0-beta on forge 1976 weapon drops are dropped in front of the factory/controller block instead to be stored into the chest.
Tried both vanilla and ironchest chests.

https://pl.vc/btzip

Greetings

**Comment by Ipsis** [comment]
This is something that I haven't seen before. My weapons drops are all being put in the chest.

Can you tell me what other mods you have installed.

My guess is that another mod is dropping mod weapons directly in the world when a mod is killed. Generally you add them to a list when the LivingDropsEvent is called and then at the end MC spawns all the loot that has been added to that list. If someone is spawning directly in world from that event or on the LivingDeath then you would see items in the world.

If that is the case then I'll have to think if there is some way I can stop that from happening.

**Comment by Gepett0** [comment]
Actually i think it's a problem with levels again.
There's a config option:

# Enables mob drops. Mobs will now randomly drop weapons and armor. Default true
    B:enableMobDrops=false

After the initial 100 mobs creating the table i didnt see any more weapons dropping, used enderman to test.

Test environment:
Forge 1976
Ender IO (for unlimited power)
EnderCore
JEI
Levels 3.0.8
xlib 1.01.
woot 0.30

**Comment by Ipsis** [comment]
I had a quick look at the code. The LivingDropsEvent handler is dropping the items in the world when a mob gets killed. The config option when false just disables the event handler which will stop the spawning.

If it is configurable then that sounds like a good solution.

**Comment by Gepett0** [comment]
Even when set to false weapons drop from the factory while building the intern table, I guess.
Not a big problem at all, max amount I collected in this time out of 6 test setups was like 30 weapons.

**Comment by Ipsis** [comment]
That shouldn't be happening. I'll have a look at this. I wanted this mod to be one where entities didn't spawn :)

**Comment by Ipsis** [comment]
That commit has nothing to do with this bug, I added the wrong bug number to the commit list :(

**Comment by Ipsis** [comment]
See #75 for a possible solution for mods that directly drop loot into the world.
