### ISSUE TITLE
[1.10] New Branch

### ISSUE THREAD

**Issue by gitgud-software** [Ipsis/Woot#63]
It seems that [1.10's Forge](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.html) is now starting to see builds. Can we get a 1.10 branch of Woot going?

**Comment by Ipsis** [comment]
Allegedly a lot of mods will just work without a rebuild, however I've not tried Woot yet.
Suffice to say, that once I've finished with re-implementing the loot learning system, 1.10 will be started.

**Comment by Ipsis** [comment]
84615ff21e1768d967aa8984e047c1907cedda1c
1.10 branch created and initial "make it compile" commit made

**Comment by Ipsis** [comment]
New release updated to CurseForge. 1.10-0.1.0-beta, based off 1.9.4-0.3.0-beta
