### ISSUE TITLE
Tweak recipes

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#71]
Couple of reports that the new release is very expensive.
Just need to know why and then I can try to rebalance a bit.

**Comment by Ipsis** [comment]
One possible tweak is to only require one enchanted book for level of upgrade.

**Comment by Ipsis** [comment]
Decided against this as I have no real feedback as to what is meant by expensive.

**Comment by Rated01010010** [comment]
Recipes are fine. It is basically a void miner. The RF costs however are extremely cheap.
