### ISSUE TITLE
Add in-game manual

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#72]
Add a text based, in-game manual.
Basically if it is good enough for RWTema then it is good enough for me :)

**Comment by Protheus** [comment]
If you can make it like botania, where it display each layer of the structure for building.

**Comment by Ipsis** [comment]
I would love to have a Botania style manual, but it is probably beyond what I could manage. For building the structure the best I can offer is the Layout Block, which I'm trying to update to show textured blocks rather than just the colored version.

**Comment by Protheus** [comment]
Well good luck with it and if the manual is going to be good as the mod i'm already excited 😀

**Comment by Rated01010010** [comment]
@Ipsis The idea of updating the layout block is a perfect fix. But there should still be an in game book showing information about each tier such as RF costs, mobs it supports, etc. You simply just make a vanilla book for that. Nothing fancy needed.

**Comment by Ipsis** [comment]
When I looked at a vanilla book it turned out not to quite as simple as I had hoped, or I didn't look properly. I think I need to start writing a json handler and mapping that to NBT for the book. It is however one of the things to go back to .... eventually.

**Comment by Ipsis** [comment]
First attempt at the manual not going well. Using a Minecraft written book isn't going to work. Too much text and not a lot on a single book page. Going to have to look at a different solution

**Comment by Ipsis** [comment]
So the manual is now happening. My first aim is the text. That means the first version will be a very basic manual. And I'm not kidding with the basic bit.

Hopefully once it is in place, I can start making it prettier over time.

Turns out I'm really bad at writing documentation ...... so be warned :)

**Comment by Ipsis** [comment]
0d5d19b3e6f34cc5ca3e8b149b949f8c87881cd5

**Comment by Ipsis** [comment]
f6db18d4e7a51312c01de8961cee54f30b68052a

The actual branch with the manual, not the wrong one that I merged :(

**Comment by ShaCraft** [comment]
I'm no Shakespeare either, but I'd be glad to help anyway I can.

**Comment by Ipsis** [comment]
You can see my first, very basic attempt in the latest release.
It is not pretty ...... in any way :)
