### ISSUE TITLE
[1.10.2] Crash: Ticking entity

### ISSUE THREAD

**Issue by Mohron** [Ipsis/Woot#78]
Version: woot-1.9.4-0.3.0-beta.jar
Crash Log: http://pastebin.com/EEqwWD6p
```
java.lang.NoSuchMethodError: net.minecraft.entity.monster.EntitySkeleton.func_82202_m()I
	at ipsis.woot.manager.MobRegistry.createWootName(MobRegistry.java:43)
```
I know you don't officially support 1.10.2 in you latest release but I wanted to make sure you were aware.  Do you have a plan to upload a newer version to Curse in the near future? I really enjoy this mod!

**Comment by Ipsis** [comment]
There are 1.10.2 versions as alphas on Curse, but they may now shown up in the launcher when they are alpha. (http://minecraft.curseforge.com/projects/woot/files)

If you are trying to run the 1.9.4 version under 1.10.X then you will get this error if you interact with Wither Skeletons. The code changed between the two versions which means I have to handle Wither Skeletons in a new way for 1.10.X.

My 1.10.2 version will move to beta release very soon, so should start appearing in the Curse launcher.

But thanks for the bug report, I was wondering if someone was going to be brave enough to try the 1.9.4 version in 1.10.X :)

**Comment by Mohron** [comment]
That's my bad for not seeing that. I knew you've been hard at work thanks to Github but Curse likes to hide alpha builds! I'll go ahead and update to your alpha build so I can have my mod pack team test it!

**Comment by Ipsis** [comment]
No problem, I've been keeping the alphas quiet :)
One of the biggest changes is that the mob learning is now persistent and store the information in a json file when the server is stopped. So it should be a lot more reliable in terms on mob drops. The next alpha should improve that even further.

**Comment by Mohron** [comment]
You're doing great work! Modded MC needed a good mob factory that wouldn't be so taxing on servers an Woot is it :)

**Comment by Ipsis** [comment]
Closing as 1.10.2 versions are available on Curse ... even though they are hidden alphas :)
