### ISSUE TITLE
[1.10.2] Tier 3 upgrade recipes not correct

### ISSUE THREAD

**Issue by kwpugh** [Ipsis/Woot#79]
Forge: 2018
Mod: woot-1.10.2-0.2.3-alpha.jar

for example, T3 looting recipe actually gives you Mass T3.

**Comment by Ipsis** [comment]
This is a bit strange, JEI is correct but the actual crafting bench output is wrong. Not quite sure what is going on there, but it will probably be something to do with the enchanted books.

**Comment by Ipsis** [comment]
Haven't solved it yet, but I think it is because all the T3 upgrade recipes use the exact same items, except the different enchanted books. If I reorder the books it still gives a valid recipe even though it is wrong.

**Comment by Ipsis** [comment]
So I need to subclass IRecipe as I think normal recipe classes don't handle tags in recipe input items.

**Comment by Ipsis** [comment]
Sort of got this working ... but there is a catch to my solution.
The recipe will match the NBT tag of the recipe book against the crafting table book.
It has to be EXACT.
I've tested with books from an enchantment table and they seem to be fine. Books from the /give command wont work as the data types inside the NBT are different.
eg.
Enchantment table book id:21s, lvl:1s
Give command book id:21 lvl:1

**Comment by kwpugh** [comment]
I think many players use the EnderIO Enchanter to make the books.   Would that work as well?

**Comment by Ipsis** [comment]
I will have to look at the enderio code to check but I'm guessing it will be correct.

**Comment by Ipsis** [comment]
Looks like EnderIO is using ENCHANTED_BOOK.addEnchantment, so it should be fine.

**Comment by Ipsis** [comment]
Added custom IRecipe for enchanted book recipes. Tested creating Looting I, II and III upgrades.
