### ISSUE TITLE
Blood Magic Integration?

### ISSUE THREAD

**Issue by 666lumberjack** [Ipsis/Woot#81]
The fact that this mod allows you farm mobs without dealing with a bunch of entities in the world is awesome, but I still end up having to deal with a ton of mobs to produce Life Essence in Blood Magic. Perhaps you could add an upgrade that causes the factory to produce life essence as a liquid instead of the standard mob drops?

**Comment by Ipsis** [comment]
I will, excuse the pun, be adding BM support for mobs dropping wills, once I work out the best way to handle this.

For life essense I'm considering it. I want to be really careful not to impact Way's BM progression. So it will probably need a high tier factory AND a relatively advanced BM object.

So it is being considered, but just in a way that will respect Way's mod.

**Comment by 666lumberjack** [comment]
Yeah it should definitely require a high level of Blood Magic progression. It's just frustrating if you want to produce a very large amount of LP that you run into lots of issues with entity limits and lag.

**Comment by Rated01010010** [comment]
@666lumberjack 

I've had no issues with lag having a small 5x5 cursed earth farm. Blood Magic is full of automation to begin with get LP supplied easily.

**Comment by 666lumberjack** [comment]
@Rated01010010 

It's not big deal with light use of Blood Magic, but I like to do a lot with it and when you have a mark of the falling tower activating and being mined every 30 seconds - 1 minute the LP drain is insane, requiring multiple altars. If each altar is contributing an average of 8-10 mobs at a time (as is the case for the most optimized production altars) you end up running into issues quite fast. 

@Ipsis 

Perhaps you could balance it by having it continuously require reagents and/or wills to operate so that it's only really viable when you're far into Blood Magic and just looking for a way to reduce the performance impact of a big build?

**Comment by ShadowDrakken** [comment]
Suggestion for BM support would be to require the BM ritual to occupy the same space as the factory, integrating it into the factory build. If necessary, it could even cause it to be a custom shaped T3/T4 factory as a result. It should then only produce LP based on the altar that's within the ritual's assigned area, as per normal.

This would of course require that BM has a way to query an altar to see what tier it is and how many of a given rune it has, or setting up a quick scan for the altar and counting it yourself...

Just some semi-random thoughts though, as I don't know how accessible this information is at the code level.

**Comment by Ipsis** [comment]
I've started to look at this, now that I have V1.0.0 of the mod out of the way.

I'm going to poke at BM to see if I can:

Detect an active BM ritual in range of the factory
Detect the BM altar and see what kind of runes it has to duplicate the exact LP generation that it would normally produce when killing mobs

So the idea would be that this factory upgrade would be the equivalent of the Well Of Suffering but without the mobs. I'm still not sure if this is possible or not, but I'll give it a try.

**Comment by Ipsis** [comment]
BloodMagic support is now working.
There is a now a Ritual Of The Infernal Machine that you have to create above the factory. When you add the Blood Magic upgrades to the factory it will push Life Essence into any adjacent IFluidHandlers eg. Tanks.

The different upgrade tiers apply a different number of sacrifice runes to each mob kill.

It does not need an Altar, it just acts as any other ritual an requires LP in your network to run.

As long as testing goes okay and I get some textures added for the upgrades, this should be in the next release.

This does NOT put any dependency of Blood Magic, If it is present these upgrades will be available,. If it is not present, then the upgrades will not be available.

**Comment by Ipsis** [comment]
0f76af5f18ec5f31cce984891b15e098e9bfd0cb
