### ISSUE TITLE
Add config to disable RF?

### ISSUE THREAD

**Issue by Rated01010010** [Ipsis/Woot#82]
I really like the mod and wanted to use it in a mod pack I'm making for a friend, but it requires RF to function, even after I set all the current settings to 0. 

He's wanting a modded Factions pack to host a server on. That is basically Factions with Tinkers Construct, Vanilla Magic, etc. type of mods. He doesn't want any tech or magic. I was really wanting to use Woot over Soul Shards because of the fact that it doesn't spawn any entities for server stability reasons, but I can't disable RF.

**Comment by Ipsis** [comment]
The trouble is if I disable RF then you basically get everything for free.
However, this is a command that I use to do this.
/woot dev true

I use that in development to test the mod without trying to add RF mods into my dev area.
The command is not persistent so you would have to run it after a server restart.

**Comment by Rated01010010** [comment]
I'll try that. And you still need to craft the items, and it still has the delays and all right?

**Comment by Ipsis** [comment]
Everything should work as normal, it just pretends that every tick that it received the RF that it needed. Suffice to say it is an unsupported feature - but feel free to abuse it :)

**Comment by Rated01010010** [comment]
It works. Thanks. 

Also, is there a reason the RF costs are so low to begin with?

For example, in Ender IO, the powered spawner costs 3,000 rf/tick to spawn 22 mobs a minute, with the octadic capacitor upgrade. With this, I can spawn 240 mobs a minute with Looting III and +80% XP, running 1,760 rf/tick. I haven't compared it to the RFTools spawner, but it caused some initial unbalance. Had to increase RF costs in the config by x20.

**Comment by Ipsis** [comment]
In the next update I've reworked all the RF costings to be a bit more expensive. However even after than I'll still be tinkering with trying to get it more balanced.

**Comment by Rated01010010** [comment]
Good to know. Not trying to say you should use other mods as a base point. It's good to have your own thing. But it should at least be in the same ball park.
