### ISSUE TITLE
Mob controller getting eaten after break

### ISSUE THREAD

**Issue by misterfixit** [Ipsis/Woot#88]
The new update that eats mob drops that spawn outside of the inventory in front of the factory is eating the mob controller when I break it.

**Comment by Ipsis** [comment]
Can you check that you are running 1.10.2-0.2.5-alpha, as that has a fix in it specifically for that issue. If you are running that, then it is not as fixed as I had hoped.

**Comment by misterfixit** [comment]
I am using 1.10.2-0.2.4-alpha ill test with the 0.2.5-alpha and get back to you

**Comment by misterfixit** [comment]
its working with 0.2.5-alpha, thanks.
