### ISSUE TITLE
Mod Spotlight

### ISSUE THREAD

**Issue by ShaCraft** [Ipsis/Woot#94]
Hey Ipsis I'd like to do a mod spotlight on this great mod! Would you like to do a collaboration video? 
My channel is RG_Sha on Youtube.  I think it would be great for both of us and the mod.  If you don't have time or our times are not in line enough I'll understand.  Also I want to make sure I am saying your name right for the video if your not available to participate. 

Thanks mate!
Sha

**Comment by Ipsis** [comment]
Please feel free to do a mod spotlight. Unfortunately I will not be able to collaborate, I just don't have the time. As for pronunciation of Ipsis, I'll leave that up to you. Just be glad I didn't go for the full length version of the name ;)

**Comment by ShaCraft** [comment]
Cheers! I'll send you a link to the video once it is done. I hope I get your name right like Ip-sis.

**Comment by ShaCraft** [comment]
Do you have a patreon page? I have the area setup for the video. I'll record it after work in the morning. I'll be sure to link to your patreon page if you have one. I'll of course link to the project you have on Curse.

**Comment by Ipsis** [comment]
No patreon, I just mod for fun ;) Well it is supposed to be fun .....

**Comment by ShaCraft** [comment]
https://www.youtube.com/watch?v=yc1PknjbZtU&feature=youtu.be

Yea I make videos for the fun of it also. It's not like I'll ever make anything off youtube. I'm too big of a dork.. hahaha .. but it is fun to see my friends kids laugh at my videos. 

Would you mind embedding the video on the curse page?  I might gain a few subs and gain a few likes to help grow my channel. I'll look at your other mod too, I'm not sure if any spotlights have been done on it, even if there has been. It was fun making this one. I hope I did a good job presenting your very cool mod. I truly think it is great!

RG_Sha

**Comment by Ipsis** [comment]
I've added an embedded video link to the CurseForge page and a link in the Wiki.
(I'm assuming that the embedded links still count towards your view count. If not I can change it just to be a link)

And thankyou for creating the spotlight. It is really weird seeing your mod on YouTube. Even more so hearing someone describe how it works!
You get extra points for pointing out the extender and proxy :)

**Comment by ShaCraft** [comment]
Hehe I was thing the same thing about seeing my artwork on the Curse launcher via your amazing mod.
Thanks so much! Also glad to see you can clean the Mob Prism now! Well done. One thing, did I say your name right? 

Cheers!

PS: I'm going to do a short Spotlight on BuildersGuides. I don't think I can stretch it to 30 mins... lol, but it will be fun to do no matter how long it is. 

RG_Sha

**Comment by Ipsis** [comment]
Next version with the Prism cleaning is stalled while I try to code an in-game manual. Hopefully soon .... ish
