### ISSUE TITLE
CyberwareZombie not dropping Cyberware-Upgrades in Factory

### ISSUE THREAD

**Issue by ChrisCrisis** [Ipsis/Woot#99]
I tried testing Cyberzombies and they don't seem to generate /drop any of the upgrades within the factory.
Prism registers them as Woot:none:cyberware.cyberzombie, but when clicked inside the factory it only labels zombie there.

**Comment by ChrisCrisis** [comment]
I notice I was simply wrong, I just needed its time to get the factory to register its drops

**Comment by Ipsis** [comment]
They way that I learn drops means that it will take a short while before they show up. It also depends on the drop rarity as well. Glad to see it started working, means one less bug to fix ;)
